! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE FPTRDTOA(KFPXFLD,YDFPGEO_DEP,YDFPGIND,YDFPGEO,KFLDS,PFIELD_DEP,PFIELD_ARR)


!**** *FPTRDTOA*  - FULL-POS TRANSPOSITION.
!                   Departure geometry DM-distribution towards
!                   arrival geometry DM-distribution.

!     PURPOSE.
!     --------

!**   INTERFACE.
!     ----------
!       *CALL* *FPTRDTOA*

!        EXPLICIT ARGUMENTS
!        --------------------
!         INPUT:
!          KFPXFLD : maximum number of fields to extract at a time
!          KFLDS:      number of fields to be transposed.
!          PFIELD_DEP: array with departure geometry DM-distribution.

!         OUTPUT:
!          PFIELD_ARR: array with arrival geometry DM-distribution.

!        IMPLICIT ARGUMENTS
!        --------------------
!        See lower #include.

!     METHOD.
!     -------
!        SEE DOCUMENTATION

!     EXTERNALS.
!     ----------

!     REFERENCE.
!     ----------
!        ECMWF Research Department documentation of the IFS
!        Documentation about FULL-POS.

!     AUTHOR.
!     -------
!        K. Yessad (CNRM/GMAP)
!        ORIGINAL : 21-Mar-2007

!     MODIFICATIONS.
!     --------------
!        P.Marguinaud : 26-Apr-2012 : Fix array dimension in call
!        R. El Khatib 17-Sep-2012 rewrite
!        R. El Khatib 12-Feb-2013 Size security check
!        R. El Khatib 09-Aug-2013 rewrite again
!        T. Wilhelmsson and K. Yessad (Oct 2013) Geometry and setup refactoring.
!        R. El Khatib 12-Aug-2016 waitany
!        R. El Khatib 16-Sep-2020 NSTACK_MEMORY_FP
!        R. El Khatib 06-Oct-2020 NFP_SYNC_LEVEL
!     End modifications
!     ------------------------------------------------------------------

USE PARKIND1  , ONLY : JPIM     ,JPRB
USE YOMHOOK   , ONLY : LHOOK, DR_HOOK, JPHOOK

USE YOMMP0    , ONLY : MYPROC   ,NPRCIDS, NPROC
USE YOMFPC    , ONLY : NSTACK_MEMORY_FP, NFP_SYNC_LEVEL
USE YOMFPGEO, ONLY : TFPGEO
USE YOMFPGIND, ONLY : TFPGIND
USE MPL_MODULE, ONLY : MPL_SEND, MPL_RECV, MPL_WAIT, JP_NON_BLOCKING_STANDARD, MPL_WAITANY, JP_BLOCKING_STANDARD

!     ------------------------------------------------------------------

IMPLICIT NONE

INTEGER(KIND=JPIM), INTENT(IN) :: KFPXFLD
TYPE (TFPGEO),  INTENT(IN) :: YDFPGEO_DEP
TYPE (TFPGIND),  INTENT(IN) :: YDFPGIND
TYPE (TFPGEO),  INTENT(IN) :: YDFPGEO
INTEGER(KIND=JPIM),INTENT(IN)  :: KFLDS
REAL(KIND=JPRB)   ,INTENT(IN)  :: PFIELD_DEP(YDFPGEO_DEP%NFPROMA,KFLDS,YDFPGEO_DEP%NFPBLOCS)
REAL(KIND=JPRB)   ,INTENT(OUT) :: PFIELD_ARR(YDFPGEO%NFPROMA,KFLDS,YDFPGEO%NFPBLOCS)

!     ------------------------------------------------------------------

INTEGER(KIND=JPIM) :: JROC, IOFF, JI, IFLDLOC, ISTACK
INTEGER(KIND=JPIM) :: IOFFPROC_SND(NPROC), IOFFPROC_RCV(NPROC)
INTEGER(KIND=JPIM) :: IFLDSCH, JCH, IFLDOFF, IFIELDS, IFLDG
INTEGER(KIND=JPIM) :: ILENBUFRECV, ILENBUFSEND, IGP2SEND, IGP2RECV, ICOUNT
INTEGER(KIND=JPIM) :: ISENDS(NPROC), IRECVS(NPROC), IREQRCV(NPROC), IOFFSEND(NPROC), IOFFRECV(NPROC)
INTEGER(KIND=JPIM), ALLOCATABLE :: IBLOC_DEP(:), IBLOC_ARR(:) ! bloc number
INTEGER(KIND=JPIM), ALLOCATABLE :: IGP_DEP(:), IGP_ARR(:) ! location in the current bloc

REAL(KIND=JPRB), TARGET, ALLOCATABLE :: ZBUFSEND_HEAP(:), ZBUFRECV_HEAP(:)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE


!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('FPTRDTOA',0,ZHOOK_HANDLE)
ASSOCIATE(NFPROMA_DEP=>YDFPGEO_DEP%NFPROMA, &
 & NFP2SEND=>YDFPGIND%NFP2SEND, NFP2RECV=>YDFPGIND%NFP2RECV, NFPSOURCE=>YDFPGIND%NFPSOURCE, &
 & NFPTARGET=>YDFPGIND%NFPTARGET, &
 & NFPBLOCS=>YDFPGEO%NFPBLOCS, NFPROMA=>YDFPGEO%NFPROMA)

IGP2SEND=SUM(NFP2SEND(:))
IGP2RECV=SUM(NFP2RECV(:))
ALLOCATE(IBLOC_DEP(IGP2SEND))
ALLOCATE(IBLOC_ARR(IGP2RECV))
ALLOCATE(IGP_DEP(IGP2SEND))
ALLOCATE(IGP_ARR(IGP2RECV))

IOFFSEND(1)=0
IOFFRECV(1)=0
DO JROC = 1, NPROC-1
  IOFFSEND(JROC+1)=IOFFSEND(JROC)+NFP2SEND(JROC)
  IOFFRECV(JROC+1)=IOFFRECV(JROC)+NFP2RECV(JROC)
ENDDO

!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JROC,JI)
DO JROC = 1, NPROC
  DO JI=1,NFP2SEND(JROC)
    IBLOC_DEP(JI+IOFFSEND(JROC))=(NFPSOURCE(JI,JROC)-1)/NFPROMA_DEP+1
    IGP_DEP  (JI+IOFFSEND(JROC))=NFPSOURCE(JI,JROC)-((IBLOC_DEP(JI+IOFFSEND(JROC))-1)*NFPROMA_DEP)
  ENDDO
  DO JI=1,NFP2RECV(JROC)
    IBLOC_ARR(JI+IOFFRECV(JROC))=(NFPTARGET(JI,JROC)-1)/NFPROMA+1
    IGP_ARR  (JI+IOFFRECV(JROC))=NFPTARGET(JI,JROC)-((IBLOC_ARR(JI+IOFFRECV(JROC))-1)*NFPROMA)
  ENDDO
ENDDO
!$OMP END PARALLEL DO

IF (KFPXFLD <= 0) THEN
  IFLDSCH=KFLDS
ELSE
  IFLDSCH=KFPXFLD
ENDIF

IF (NSTACK_MEMORY_FP == 0) THEN
  ISTACK=0
ELSE
  ISTACK=1
ENDIF

DO JCH=1,(KFLDS-1)/IFLDSCH+1

  IFLDOFF=(JCH-1)*IFLDSCH
  IFIELDS=MIN(JCH*IFLDSCH,KFLDS)-IFLDOFF

  DO JROC = 1, MYPROC-1
    IRECVS(JROC)=NFP2RECV(JROC)*IFIELDS
    ISENDS(JROC)=NFP2SEND(JROC)*IFIELDS
  ENDDO
  IRECVS(MYPROC)=0
  ISENDS(MYPROC)=0
  DO JROC = MYPROC+1,NPROC
    IRECVS(JROC)=NFP2RECV(JROC)*IFIELDS
    ISENDS(JROC)=NFP2SEND(JROC)*IFIELDS
  ENDDO

  ILENBUFRECV=SUM(IRECVS(:))
  ILENBUFSEND=SUM(ISENDS(:))

  IF (ISTACK == 0) THEN
    IF (.NOT.ALLOCATED(ZBUFSEND_HEAP)) THEN
      ALLOCATE(ZBUFSEND_HEAP(ILENBUFSEND))
      IF (ILENBUFSEND >=1) ZBUFSEND_HEAP(1)=HUGE(1._JPRB) ! ensures the buffer is allocated right here
    ELSE
      IF (SIZE(ZBUFSEND_HEAP) /= ILENBUFSEND) THEN
        DEALLOCATE(ZBUFSEND_HEAP)
        ALLOCATE(ZBUFSEND_HEAP(ILENBUFSEND))
      IF (ILENBUFSEND >=1) ZBUFSEND_HEAP(1)=HUGE(1._JPRB) ! ensures the buffer is allocated right here
      ENDIF
    ENDIF
    IF (.NOT.ALLOCATED(ZBUFRECV_HEAP)) THEN
      ALLOCATE(ZBUFRECV_HEAP(ILENBUFRECV))
      IF (ILENBUFRECV >=1) ZBUFRECV_HEAP(1)=HUGE(1._JPRB) ! ensures the buffer is allocated right here 
    ELSE
      IF (SIZE(ZBUFRECV_HEAP) /= ILENBUFRECV) THEN
        DEALLOCATE(ZBUFRECV_HEAP)
        ALLOCATE(ZBUFRECV_HEAP(ILENBUFRECV))
        IF (ILENBUFRECV >=1) ZBUFRECV_HEAP(1)=HUGE(1._JPRB) ! ensures the buffer is allocated right here 
      ENDIF
    ENDIF
  ENDIF

  CALL FPTRDTOA_COMM

ENDDO

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('FPTRDTOA',1,ZHOOK_HANDLE)

CONTAINS

SUBROUTINE FPTRDTOA_COMM

INTEGER(KIND=JPIM) :: IREQSND(NPROC), IREQINDX(NPROC)
INTEGER(KIND=JPIM) :: JNR, INR, IRRCV

REAL(KIND=JPRB), TARGET :: ZBUFSEND_STACK(ILENBUFSEND*ISTACK), ZBUFRECV_STACK(ILENBUFRECV*ISTACK)
REAL(KIND=JPRB), POINTER :: ZBUFSEND(:), ZBUFRECV(:)

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('FPTRDTOA:FPTRDTOA_COMM',0,ZHOOK_HANDLE)
ASSOCIATE(NFP2SEND=>YDFPGIND%NFP2SEND, NFP2RECV=>YDFPGIND%NFP2RECV)

IF (ISTACK == 1) THEN
  ZBUFSEND => ZBUFSEND_STACK(:)
  ZBUFRECV => ZBUFRECV_STACK(:)
ELSE
  ZBUFSEND => ZBUFSEND_HEAP(:)
  ZBUFRECV => ZBUFRECV_HEAP(:)
ENDIF

!      1.1 Post recv first

IOFFPROC_RCV(1)=0
IOFFPROC_SND(1)=0
DO JROC = 1, NPROC-1
  IOFFPROC_RCV(JROC+1)=IOFFPROC_RCV(JROC)+IRECVS(JROC)
  IOFFPROC_SND(JROC+1)=IOFFPROC_SND(JROC)+ISENDS(JROC)
ENDDO

IRRCV=0
DO JROC = 1, NPROC
  IF (IRECVS(JROC) > 0 .AND. JROC /= MYPROC) THEN
    IRRCV=IRRCV+1
    IREQINDX(IRRCV)=JROC
    IF (NFP_SYNC_LEVEL > 0) THEN
      CALL MPL_RECV(ZBUFRECV(IOFFPROC_RCV(JROC)+1:IOFFPROC_RCV(JROC)+IRECVS(JROC)), &
       & KMP_TYPE=JP_NON_BLOCKING_STANDARD,KREQUEST=IREQRCV(IRRCV), &
       & KOUNT=ICOUNT,KSOURCE=NPRCIDS(JROC),KTAG=JROC,CDSTRING='FPTRDTOA:FPTRDTOA_COMM')
    ENDIF
  ENDIF
ENDDO

!      1.2 Sends

DO JROC = 1, NPROC
  IF (ISENDS(JROC) > 0 .AND. JROC /= MYPROC) THEN
!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(IFLDLOC,IOFF,IFLDG,JI)
    DO IFLDLOC=1,IFIELDS
      IOFF=IOFFPROC_SND(JROC)+(IFLDLOC-1)*NFP2SEND(JROC)
      IFLDG=IFLDLOC+IFLDOFF
      DO JI=1,NFP2SEND(JROC)
        ZBUFSEND(JI+IOFF)=PFIELD_DEP(IGP_DEP(JI+IOFFSEND(JROC)),IFLDG,IBLOC_DEP(JI+IOFFSEND(JROC)))
      ENDDO
    ENDDO
!$OMP END PARALLEL DO
    CALL MPL_SEND(ZBUFSEND(IOFFPROC_SND(JROC)+1:IOFFPROC_SND(JROC)+ISENDS(JROC)), &
     & KMP_TYPE=JP_NON_BLOCKING_STANDARD,KREQUEST=IREQSND(JROC), &
     & KTAG=MYPROC,KDEST=NPRCIDS(JROC),CDSTRING='FPTRDTOA:FPTRDTOA_COMM')
  ENDIF
ENDDO

!      1.3 Local contribution

!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JI,IFLDLOC,IFLDG)
DO IFLDLOC=1,IFIELDS
  IFLDG=IFLDLOC+IFLDOFF
  DO JI=1,NFP2RECV(MYPROC)
    PFIELD_ARR(IGP_ARR(JI+IOFFRECV(MYPROC)),IFLDG,IBLOC_ARR(JI+IOFFRECV(MYPROC)))= &
    & PFIELD_DEP(IGP_DEP(JI+IOFFSEND(MYPROC)),IFLDG,IBLOC_DEP(JI+IOFFSEND(MYPROC)))
  ENDDO
ENDDO
!$OMP END PARALLEL DO

!      1.4 Actual recv

DO JNR=1,IRRCV
  IF (NFP_SYNC_LEVEL > 0) THEN
    CALL MPL_WAITANY(KREQUEST=IREQRCV(1:IRRCV),KINDEX=INR,CDSTRING='FPTRDTOA:FPTRDTOA_COMM: WAIT FOR RECVS')
    JROC=IREQINDX(INR)
  ELSE
    JROC=IREQINDX(JNR)
    CALL MPL_RECV(ZBUFRECV(IOFFPROC_RCV(JROC)+1:IOFFPROC_RCV(JROC)+IRECVS(JROC)), &
     & KMP_TYPE=JP_BLOCKING_STANDARD,KREQUEST=IREQRCV(JNR), &
     & KOUNT=ICOUNT,KSOURCE=NPRCIDS(JROC),KTAG=JROC,CDSTRING='FPTRDTOA_COMM')  
  ENDIF
!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JI,IFLDLOC,IOFF,IFLDG)
  DO IFLDLOC=1,IFIELDS
    IOFF=IOFFPROC_RCV(JROC)+(IFLDLOC-1)*NFP2RECV(JROC)
    IFLDG=IFLDLOC+IFLDOFF
    DO JI=1,NFP2RECV(JROC)
      PFIELD_ARR(IGP_ARR(JI+IOFFRECV(JROC)),IFLDG,IBLOC_ARR(JI+IOFFRECV(JROC)))=ZBUFRECV(JI+IOFF)
    ENDDO
  ENDDO
!$OMP END PARALLEL DO
ENDDO

!      1.5 Wait completion of sends

DO JROC = 1, NPROC
  IF (ISENDS(JROC) > 0 .AND. JROC /= MYPROC) THEN
    CALL MPL_WAIT(KREQUEST=IREQSND(JROC),CDSTRING='FPTRDTOA:FPTRDTOA_COMM: WAIT FOR SENDS')
  ENDIF
ENDDO

! ---------------------------------------------------------------------

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('FPTRDTOA:FPTRDTOA_COMM',1,ZHOOK_HANDLE)

END SUBROUTINE FPTRDTOA_COMM

END SUBROUTINE FPTRDTOA
