! (C) Copyright 2011- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE CPG_GP_NHEE(YDGEOMETRY, YDCPG_BNDS, YDCPG_OPTS, YDTMP, YDVARS, YDCPG_DYN0, YDCPG_DYN9, &
& YDMODEL, YDGMV, LDGPXX, LDLDIAB, LDMPA, POROG, PGFL, PATND)
USE GEOMETRY_MOD, ONLY : GEOMETRY
USE FIELD_VARIABLES_MOD,ONLY : FIELD_VARIABLES
USE CPG_TYPE_MOD,ONLY : CPG_DYN_TYPE, CPG_GP_TMP_TYPE
USE CPG_OPTS_TYPE_MOD , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE YOMGMV, ONLY : TGMV
USE TYPE_MODEL, ONLY : MODEL
use parkind1 , only:&
 & jprb
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(CPG_BNDS_TYPE),INTENT(IN) :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE),INTENT(IN) :: YDCPG_OPTS
TYPE(CPG_GP_TMP_TYPE),INTENT(INOUT) :: YDTMP
TYPE(FIELD_VARIABLES),INTENT(INOUT) :: YDVARS
TYPE(CPG_DYN_TYPE),INTENT(INOUT) :: YDCPG_DYN0
TYPE(CPG_DYN_TYPE),INTENT(INOUT) :: YDCPG_DYN9
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
TYPE(TGMV) ,INTENT(INOUT) :: YDGMV
LOGICAL ,INTENT(IN) :: LDGPXX
LOGICAL ,INTENT(IN) :: LDLDIAB
LOGICAL ,INTENT(IN) :: LDMPA
REAL(KIND=JPRB) ,INTENT(IN) :: POROG(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGFL(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_GCONF%YGFL%NDIM)
REAL(KIND=JPRB) ,INTENT(OUT) :: PATND(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG, &
 & YDMODEL%YRML_DYN%YRDYNA%YYTTND%NDIM)
call abor1("CPG_GP_NHEE should never be called with this build configuration - EXITING")
END SUBROUTINE CPG_GP_NHEE
