! (C) Copyright 2011- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE GNHEE_SVDINCR13(&
 & YDGEOMETRY,KFLEV,KPROMA,KST,KEND,POROGL,POROGM,PUH,PVH,&
 & PLNPR,PRT,PNHPPI,&
 & PDGWINCR13,PSVDINCR13)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KST
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
REAL(KIND=JPRB) ,INTENT(IN) :: POROGL(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: POROGM(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PUH(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVH(KPROMA,0:KFLEV)
REAL(KIND=JPRB),OPTIONAL,INTENT(IN) :: PLNPR(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL,INTENT(IN) :: PRT(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL,INTENT(IN) :: PNHPPI(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL,INTENT(OUT) :: PDGWINCR13(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL,INTENT(OUT) :: PSVDINCR13(KPROMA,KFLEV)
call abor1("GNHEE_SVDINCR13 should never be called with this build configuration - EXITING")
END SUBROUTINE GNHEE_SVDINCR13
