! (C) Copyright 2011- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE SUNHSI(YDGEOMETRY,YDRIP,YDDYN,YDDYNA,YDEDYN,LDNESC,KULOUT,LDEB)
USE GEOMETRY_MOD , ONLY : GEOMETRY
use parkind1 , only:&
 & jpim
USE YOMDYN , ONLY : TDYN
USE YOMDYNA , ONLY : TDYNA
USE YEMDYN , ONLY : TEDYN
USE YOMRIP , ONLY : TRIP
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TDYN) ,INTENT(INOUT):: YDDYN
TYPE(TDYNA) ,INTENT(INOUT):: YDDYNA
TYPE(TEDYN) ,INTENT(INOUT):: YDEDYN
TYPE(TRIP) ,INTENT(INOUT):: YDRIP
LOGICAL ,INTENT(IN) :: LDNESC
INTEGER(KIND=JPIM),INTENT(IN) :: KULOUT
LOGICAL ,INTENT(IN) :: LDEB
call abor1("SUNHSI should never be called with this build configuration - EXITING")
END SUBROUTINE SUNHSI
SUBROUTINE NH_MATRIX(YDGEOMETRY,YDDYN,YDDYNA,LVERB,KFLEV,PKWAVE, &
 &PSITR,PSITRAM,PSIPR,MDIM,MM)
USE PARKIND1 , ONLY : JPRB, JPIM
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMDYN , ONLY : TDYN
USE YOMDYNA , ONLY : TDYNA
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TDYN) ,INTENT(INOUT) :: YDDYN
TYPE(TDYNA) ,INTENT(INOUT) :: YDDYNA
LOGICAL ,INTENT(IN) :: LVERB
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
REAL(KIND=JPRB) ,INTENT(IN) :: PKWAVE
REAL(KIND=JPRB) ,INTENT(IN) :: PSITR
REAL(KIND=JPRB) ,INTENT(IN) :: PSITRAM(KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSIPR
INTEGER(KIND=JPIM),INTENT(IN) :: MDIM
REAL(KIND=JPRB) ,INTENT(OUT) :: MM(MDIM,MDIM)
call abor1("NH_MATRIX should never be called with this build configuration - EXITING")
END SUBROUTINE NH_MATRIX
