! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE SUEDRD(YDCAT)

! Purpose :
! -------
!    To setup the user type "TYPES_FPCAT" for the post-processing of individual CAT/MTW indices
!    and the final combinaison of indices to compute diagnostic EDR.
!    Also print this configuration

! Interface :
! ---------
!    Empty.

! External :
! --------
!    None.

! Method :
! ------
!    See Documentation.

! Reference :
! ---------
!    Fullpos technical & users guide.

! Author :
! ------
!    Olivier Jaron *METEO-FRANCE*

! Modifications :
! -------------
! Original : 2019-08-01

!-----------------------------------------------------------------------------

USE TYPES_FPCAT, ONLY : ALL_FPCAT_TYPES, SUCATIND, PRINT_CONFIG_EDRD
USE YOMHOOK    , ONLY : LHOOK, DR_HOOK, JPHOOK
USE PARKIND1   , ONLY : JPRB
USE YOMMP0     , ONLY : NPRINTLEV
USE YOMLUN     , ONLY : NULOUT

IMPLICIT NONE

TYPE(ALL_FPCAT_TYPES), INTENT(INOUT) :: YDCAT

LOGICAL :: LLT,LLF
LOGICAL , DIMENSION(1:3)          :: LLCOMB
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('SUEDRD',0,ZHOOK_HANDLE)

LLT=.TRUE.
LLF=.FALSE.


! ------------
! SETUP
! ------------
CALL SUCATIND(YDCAT%DFR, 'Def/Ri', LLF, &
    & PDELTA=(/2.35163717253_JPRB,2.23517296052_JPRB,1.00094636815_JPRB/), &
    & PRATIO=(/0.223277549752_JPRB,0.213033895181_JPRB,0.157519690395_JPRB/) , &
    & LDCOMB=(/LLT,LLF,LLF/)  )
CALL SUCATIND(YDCAT%EDR, 'EDR', LLF, &
    & PDELTA=(/-0.475573069676_JPRB,-0.305349522203_JPRB,-0.794018002766_JPRB/), &
    & PRATIO=(/0.116116504969_JPRB,0.122061332051_JPRB,0.143149857397_JPRB/) , &
    & LDCOMB=(/LLF,LLF,LLT/)  )
CALL SUCATIND(YDCAT%TKE, 'TKE', LLF, &
    & PDELTA=(/-1.03487570956_JPRB,-1.05311036477_JPRB,-1.45280290972_JPRB/), &
    & PRATIO=(/0.131655726795_JPRB,0.106064342474_JPRB,0.292271551348_JPRB/) , &
    & LDCOMB=(/LLT,LLT,LLT/)  )
CALL SUCATIND(YDCAT%INVRITW, '1/RITW', LLF, &
    & PDELTA=(/-1.60996064358_JPRB,-1.65123315647_JPRB,-1.83605932933_JPRB/), &
    & PRATIO=(/0.342009871582_JPRB,0.288248526425_JPRB,0.148823807769_JPRB/) , &
    & LDCOMB=(/LLT,LLF,LLF/)  )
CALL SUCATIND(YDCAT%VVSQ, 'SQVV', LLF, &
    & PDELTA=(/-1.33091926488_JPRB,-1.4719180236_JPRB,-1.37426201147_JPRB/), &
    & PRATIO=(/0.236510730915_JPRB,0.251288250253_JPRB,0.207641539387_JPRB/) , &
    & LDCOMB=(/LLT,LLT,LLF/)  )
CALL SUCATIND(YDCAT%WND, 'FF', LLF, &
    & PDELTA=(/-6.37740258318_JPRB,-5.33099570917_JPRB,-4.16707385062_JPRB/), &
    & PRATIO=(/1.19963148918_JPRB,1.10378909_JPRB,0.904855366681_JPRB/) , &
    & LDCOMB=(/LLF,LLF,LLT/)  )
CALL SUCATIND(YDCAT%DUT, 'Dutton', LLF, &
    & PDELTA=(/-4.25109589636_JPRB,-3.8060204266_JPRB,-2.83877204459_JPRB/), &
    & PRATIO=(/0.593663634293_JPRB,0.538202071898_JPRB,0.202734000606_JPRB/) , &
    & LDCOMB=(/LLT,LLF,LLF/)  )

CALL SUCATIND(YDCAT%EDRDC, 'EDRDC', LLT, &
    & PDELTA=(/1.43351368634_JPRB,0.955070867915_JPRB,1.39415096046_JPRB/), &
    & PRATIO=(/1.80310818439_JPRB,1.60048290663_JPRB,1.56254898122_JPRB/) , &
    & LDCOMB=(/LLF,LLF,LLF/)  )
! Global key controlling conversion of individual indices into EDR unit
YDCAT%LCONVEDR=.TRUE.

! -------
! PRINT CONFIG
! --------

IF (NPRINTLEV > 0) THEN
  WRITE(NULOUT,FMT='(''ALL_FPCAT_TYPES STRUCTURE: LCONVEDR='', L2,1X,''PRESH='',F9.0, &
    & ''PRESM='',F9.0, ''PRESL='',F9.0,'' PDELTA='', F9.0)') &
    & YDCAT%LCONVEDR, YDCAT%PPRESH, YDCAT%PPRESM, YDCAT%PPRESL, YDCAT%PPDELTA
  WRITE(NULOUT, FMT ='(1X,''CAT and MTW combinaison configuration for EDRD computation'')')
  WRITE(NULOUT, FMT ='(4X,''TFP_NAME'',4X,''YCA_NAME'',4X, ''ID'',4X,''DELTA_HIG'',1X,''RATIO_HIG'',&
    & 1X,''DELTA_MED'',1X, ''RATIO_MED'',1X, ''DELTA_LOW'',1X,''RATIO_LOW'',1X, ''LCOMBH'',1X, ''LCOMBM'', &
    & 1X,''LCOMBL'',1X,''LLCOMB'',1X,''LEDR'' )') 
  CALL PRINT_CONFIG_EDRD(YDCAT%BR1     ,   'CATBR1      '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%BR1R    ,   'CATBR1R     '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%BR1PV   ,   'CATBR1PV    '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%BR2     ,   'CATBR2      '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%DUT     ,   'CATDUT      '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%LAZ     ,   'CATLAZ      '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%TI1     ,   'CATTI1      '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%TI1PV   ,   'CATTI1PV    '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%TI2     ,   'CATTI2      '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%TI2PV   ,   'CATTI2PV    '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%CP      ,   'CATCP       '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%RI      ,   'CATRI       '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%INVRI   ,   'CATINVRI    '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%INVRIM  ,   'CATINVRIM   '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%HSR     ,   'CATHSR      '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%LRT     ,   'CATLRT      '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%DF      ,   'CATDF       '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%DFR     ,   'CATDFR      '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%DFPV    ,   'CATDFPV     '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%INVRITW ,   'CATINVRITW  '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%DVR     ,   'CATDVR      '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%AGI     ,   'CATAGI      '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%F2D     ,   'CATF2D      '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%F2DR    ,   'CATF2DR     '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%F2DPV   ,   'CATF2DPV    '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%NG1     ,   'CATNG1      '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%NG2     ,   'CATNG2      '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%NG1R    ,   'CATNG1R     '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%NG2R    ,   'CATNG2R     '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%TKER    ,   'CATTKER     '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%TGR     ,   'CATTGR      '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%IAW     ,   'CATIAW      '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%IAWPV   ,   'CATIAWPV    '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%IAWR    ,   'CATIAWR     '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%SV      ,   'CATSV       '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%BV      ,   'CATBV       '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%BVM     ,   'CATBVM      '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%VSQR    ,   'CATVSQR     '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%DPV     ,   'CATDPV      '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%VVSQRI  ,   'CATVVSQRI   '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%VVSQ    ,   'CATVVSQ     '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%WND     ,   'WND         '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%EDR     ,   'EDR         '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%TKE     ,   'TKE         '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%VVSQMW  ,   'CATVVSQMW   '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%F2DMW   ,   'CATF2DMW    '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%WNDMW   ,   'CATWNDMW    '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%DVRMW   ,   'CATDVRMW    '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%NG1MW   ,   'CATNG1MW    '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%IAWMW   ,   'CATIAWMW    '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%DFMW    ,   'CATDFMW     '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%EDRDC   ,   'EDRDC       '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%EDRDW   ,   'EDRDW       '  )
  CALL PRINT_CONFIG_EDRD(YDCAT%EDRDM   ,   'EDRDM       '  )

ENDIF

IF (LHOOK) CALL DR_HOOK('SUEDRD',1,ZHOOK_HANDLE)


END SUBROUTINE SUEDRD
