! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE SUNUDGLH(YDRIP)

!**** *SUNUDGLH*  - Initialize NUDGLH handling (namelist defaults)

!     Purpose.
!     --------

!**   Interface.
!     ----------
!        *CALL* *SUNUDGLH

!        Explicit arguments :
!        --------------------
!        None

!        Implicit arguments :
!        --------------------

!     Method.
!     -------
!        See purpose above

!     Externals.
!     ----------
!        None

!     Reference.
!     ----------

!     Author.
!     -------
!        ADAPTATION by FLorian Meier *ZAMG*
!        based on SUIAU from
!        Pierre BROUSSEAU *CNRM/GMAP*

!     Modifications.
!     --------------
!        Original :    fev-204
!        ADAPTATION:   nov-2015
!     ------------------------------------------------------------------

USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK
USE YOMLUN   , ONLY : NULOUT   ,NULNAM
USE YOMNUDGLH   , ONLY : LNUDGLH, LNUDGLHREAD, LNUDGLHSTEPH,&
 & LNUDGLHCLIM, LNUDGLHENVI, LNUDGLHSUBSAT,&
 & RDAMPNUDGLH, TTAUNUDGLH, NTAUNUDGLH,&
 & NSTARTNUDGLH, NSTOPNUDGLH, NINTNUDGLH, &
 & TSTARTNUDGLH, TSTOPNUDGLH, TINTNUDGLH,&
 & NBOTTOMNUDGLH, NTOPNUDGLH, RPRTOPSNUDGLH, RFACNUDGLH,&
 & RPRTOPCNUDGLH, RPRTOPSTABNUDGLH, RPRMAXSNUDGLH,&
 & RPRMAXCNUDGLH, RPRBOTTOMSNUDGLH, RPRBOTTOMCNUDGLH,&
 & RPRBOTTOMANUDGLH, RPRBOTTOMBNUDGLH, RPRBOTTOMDNUDGLH,&
 & RPRBOTTOMTNUDGLH, RPRBOTTOMWNUDGLH, RPRTOPANUDGLH,&
 & RPRTOPBNUDGLH, RPRTOPDNUDGLH, RPRTOPTNUDGLH,&
 & RPRTOPWNUDGLH, RPRBOTTOMSTABNUDGLH, RHEATSNUDGLH,&
 & RHEATCNUDGLH, RHEATANUDGLH, RHEATBNUDGLH, RHEATDNUDGLH,&
 & RHEATTNUDGLH, RHEATWNUDGLH, RHEATSTABNUDGLH, RAMPLIFY,&
 & RMAXNUDGLH, RMINNUDGLH, RPRMAXANUDGLH, RPRMAXBNUDGLH,&
 & RPRMAXDNUDGLH, RPRMAXTNUDGLH, RPRMAXWNUDGLH,&
 & RORONUDGLH, RALPHANUDGLH, REPSILONNUDGLH, LNUDGLHCOMPT,&
 & NTIMESPLITNUDGLH
USE YOMCT0   , ONLY : NCONF    ,LELAM
USE YOMRIP   , ONLY : TRIP

IMPLICIT NONE
TYPE(TRIP),INTENT(INOUT):: YDRIP
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE


#include "namnudglh.nam.h"

#include "abor1.intfb.h"
#include "posnam.intfb.h"
!     ------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('SUNUDGLH',0,ZHOOK_HANDLE)

ASSOCIATE(TSTEP=>YDRIP%TSTEP)
WRITE(NULOUT,*) ' *** SUNUDGLH : SETUP NUDGLH Term LAM forecast'
!     2. READ NAMELIST AND CHECK CONSISTENCY
!     --------------------------------------
! set default values
LNUDGLH=.FALSE.
LNUDGLHCOMPT=.FALSE.
LNUDGLHREAD=.FALSE.
LNUDGLHSTEPH=.FALSE.
LNUDGLHCLIM=.FALSE.
LNUDGLHENVI=.FALSE.
LNUDGLHSUBSAT=.FALSE.
NTAUNUDGLH=0_JPIM
TTAUNUDGLH=0._JPRB
TSTARTNUDGLH = 0.0_JPRB
TSTOPNUDGLH = 3600.0_JPRB
TINTNUDGLH = 900.0_JPRB 
NSTARTNUDGLH = 0_JPIM
NSTOPNUDGLH = 61_JPIM
NINTNUDGLH = 15_JPIM
NBOTTOMNUDGLH = 1000_JPIM
NTOPNUDGLH = 0_JPIM
RDAMPNUDGLH = 0.0_JPRB
NTIMESPLITNUDGLH=1_JPIM

RPRTOPSNUDGLH = 85000.00_JPRB
RPRTOPANUDGLH = 55000.00_JPRB
RPRTOPBNUDGLH = 60000.00_JPRB
RPRTOPCNUDGLH = 70000.00_JPRB
RPRTOPDNUDGLH = 80000.00_JPRB
RPRTOPTNUDGLH = 200000.00_JPRB
RPRTOPWNUDGLH = 200000.00_JPRB
RPRTOPSTABNUDGLH = 20000.00_JPRB
RPRMAXSNUDGLH = 95000.00_JPRB
RPRMAXANUDGLH = 70000.00_JPRB
RPRMAXBNUDGLH = 78000.00_JPRB
RPRMAXCNUDGLH = 82000.00_JPRB
RPRMAXDNUDGLH = 88000.00_JPRB
RPRMAXTNUDGLH = 200000.00_JPRB
RPRMAXWNUDGLH = 200000.00_JPRB
RPRBOTTOMSNUDGLH = 99900.00_JPRB
RPRBOTTOMANUDGLH = 90000.00_JPRB
RPRBOTTOMBNUDGLH = 90000.00_JPRB
RPRBOTTOMCNUDGLH = 99900.00_JPRB
RPRBOTTOMDNUDGLH = 95000.00_JPRB
RPRBOTTOMTNUDGLH = 200000.00_JPRB
RPRBOTTOMWNUDGLH = 200000.00_JPRB
RPRBOTTOMSTABNUDGLH = 90000.00_JPRB
RHEATSNUDGLH = 14.0_JPRB
RHEATANUDGLH = 14.0_JPRB
RHEATBNUDGLH = 14.0_JPRB
RHEATCNUDGLH = 14.0_JPRB
RHEATDNUDGLH = 14.0_JPRB
RHEATTNUDGLH = 0.0_JPRB
RHEATWNUDGLH = 0.0_JPRB
RHEATSTABNUDGLH = 0.3_JPRB
RAMPLIFY = 1.0_JPRB
RMAXNUDGLH = 6.0_JPRB
RMINNUDGLH = -6.0_JPRB
RORONUDGLH = 1.5_JPRB
RALPHANUDGLH = 0.5_JPRB
REPSILONNUDGLH = 0.3333_JPRB
RFACNUDGLH = 1.0_JPRB

CALL POSNAM(NULNAM,'NAMNUDGLH')
READ(NULNAM,NAMNUDGLH)
IF (LNUDGLH) THEN
  IF (.NOT.LELAM) THEN
     CALL ABOR1('NUDGLH not yet coded for global model ')
  ENDIF
  IF (NCONF /= 1) THEN
     CALL ABOR1('LNUDGLH=.TRUE. only with NCONF==1 ')
  ENDIF
  IF (TSTARTNUDGLH > TSTOPNUDGLH) THEN
        CALL ABOR1('TSTARTNUDGLH>TSTOPNUDGLH, CHECK NUDGLH NAMELIST')
  ENDIF
  ! calculate NUDGINGINTERVAL steps from time in s
  NSTARTNUDGLH=NINT(TSTARTNUDGLH/TSTEP)
  NSTOPNUDGLH=NINT(TSTOPNUDGLH/TSTEP)
  NINTNUDGLH=NINT(TINTNUDGLH/TSTEP)
  NTAUNUDGLH=NINT(TTAUNUDGLH/TSTEP)
  WRITE(NULOUT,*) 'NUDGING switched on: LNUDGLH=',LNUDGLH
  WRITE(NULOUT,*) 'LHN RH kept constant switched on: LNUDGLHCOMPT=',LNUDGLHCOMPT
  WRITE(NULOUT,*) 'Read LHN climatology from FILE switched on: LNUDGLHREAD=',LNUDGLHREAD
  WRITE(NULOUT,*) 'LHN with Stephan 2008 factor: LNUDGLHSTEPH=',LNUDGLHSTEPH
  WRITE(NULOUT,*) 'Nudging interval in s:',TINTNUDGLH
  WRITE(NULOUT,*) 'Nudging interval in timesteps: NINTNUDGLH=',NINTNUDGLH
  WRITE(NULOUT,*) 'number of seconds after observation time, when nudging is applied:'
  WRITE(NULOUT,*) ' TTAUNUDGLH=',TTAUNUDGLH
  WRITE(NULOUT,*) 'number of timesteps after observation time, when nudging is applied:'
  WRITE(NULOUT,*) ' NTAUNUDGLH=',NTAUNUDGLH
  WRITE(NULOUT,*) 'between time ',TSTARTNUDGLH,' (sec.) corresponding to timestep ',NSTARTNUDGLH
  WRITE(NULOUT,*) 'and time ',TSTOPNUDGLH,' (sec.) corresponding to timestep ',NSTOPNUDGLH
  WRITE(NULOUT,*) 'Damping of LH nudging for each consecutive timestep within NTAUNUDGLH:'
  WRITE(NULOUT,*) 'RDAMPNUDGLH=',RDAMPNUDGLH
  WRITE(NULOUT,*) 'LNUDGLHCLIM=',LNUDGLHCLIM
  WRITE(NULOUT,*) 'LNUDGLHENVI=',LNUDGLHENVI
  WRITE(NULOUT,*) 'LNUDGLHSUBSAT=',LNUDGLHSUBSAT
  WRITE(NULOUT,*) 'NBOTTOMNUDGLH=',NBOTTOMNUDGLH
  WRITE(NULOUT,*) 'NTOPNUDGLH=',NTOPNUDGLH
  WRITE(NULOUT,*) 'RPRTOPSNUDGLH=',RPRTOPSNUDGLH
  WRITE(NULOUT,*) 'RPRTOPANUDGLH=',RPRTOPANUDGLH
  WRITE(NULOUT,*) 'RPRTOPBNUDGLH=',RPRTOPBNUDGLH
  WRITE(NULOUT,*) 'RPRTOPCNUDGLH=',RPRTOPCNUDGLH
  WRITE(NULOUT,*) 'RPRTOPDNUDGLH=',RPRTOPDNUDGLH
  WRITE(NULOUT,*) 'RPRTOPTNUDGLH=',RPRTOPTNUDGLH
  WRITE(NULOUT,*) 'RPRTOPWNUDGLH=',RPRTOPWNUDGLH
  WRITE(NULOUT,*) 'RPRTOPSTABNUDGLH=',RPRTOPSTABNUDGLH
  WRITE(NULOUT,*) 'RPRMAXSNUDGLH=',RPRMAXSNUDGLH
  WRITE(NULOUT,*) 'RPRMAXANUDGLH=',RPRMAXANUDGLH
  WRITE(NULOUT,*) 'RPRMAXBNUDGLH=',RPRMAXBNUDGLH
  WRITE(NULOUT,*) 'RPRMAXCNUDGLH=',RPRMAXCNUDGLH
  WRITE(NULOUT,*) 'RPRMAXDNUDGLH=',RPRMAXDNUDGLH
  WRITE(NULOUT,*) 'RPRMAXTNUDGLH=',RPRMAXTNUDGLH
  WRITE(NULOUT,*) 'RPRMAXWNUDGLH=',RPRMAXWNUDGLH
  WRITE(NULOUT,*) 'RPRBOTTOMSNUDGLH=',RPRBOTTOMSNUDGLH
  WRITE(NULOUT,*) 'RPRBOTTOMANUDGLH=',RPRBOTTOMANUDGLH
  WRITE(NULOUT,*) 'RPRBOTTOMBNUDGLH=',RPRBOTTOMBNUDGLH
  WRITE(NULOUT,*) 'RPRBOTTOMCNUDGLH=',RPRBOTTOMCNUDGLH
  WRITE(NULOUT,*) 'RPRBOTTOMDNUDGLH=',RPRBOTTOMDNUDGLH
  WRITE(NULOUT,*) 'RPRBOTTOMTNUDGLH=',RPRBOTTOMTNUDGLH
  WRITE(NULOUT,*) 'RPRBOTTOMWNUDGLH=',RPRBOTTOMWNUDGLH
  WRITE(NULOUT,*) 'RPRBOTTOMSTABNUDGLH=',RPRBOTTOMSTABNUDGLH
  WRITE(NULOUT,*) 'RHEATSNUDGLH=',RHEATSNUDGLH
  WRITE(NULOUT,*) 'RHEATANUDGLH=',RHEATANUDGLH
  WRITE(NULOUT,*) 'RHEATBNUDGLH=',RHEATBNUDGLH
  WRITE(NULOUT,*) 'RHEATCNUDGLH=',RHEATCNUDGLH
  WRITE(NULOUT,*) 'RHEATDNUDGLH=',RHEATDNUDGLH
  WRITE(NULOUT,*) 'RHEATTNUDGLH=',RHEATTNUDGLH
  WRITE(NULOUT,*) 'RHEATWNUDGLH=',RHEATWNUDGLH
  WRITE(NULOUT,*) 'RHEATSTABNUDGLH=',RHEATSTABNUDGLH
  WRITE(NULOUT,*) 'RAMPLIFY=',RAMPLIFY
  WRITE(NULOUT,*) 'RMAXNUDGLH=',RMAXNUDGLH
  WRITE(NULOUT,*) 'RMINNUDGLH=',RMINNUDGLH
  WRITE(NULOUT,*) 'RORONUDGLH=',RORONUDGLH
  WRITE(NULOUT,*) 'REPSILONNUDGLH=',REPSILONNUDGLH
  WRITE(NULOUT,*) 'RALPHANUDGLH=',RALPHANUDGLH
  WRITE(NULOUT,*) 'RFACNUDGLH=',RFACNUDGLH
  WRITE(NULOUT,*) 'NTIMESPLITNUDGLH=',NTIMESPLITNUDGLH

ENDIF
!     ------------------------------------------------------------------
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUNUDGLH',1,ZHOOK_HANDLE)
END SUBROUTINE SUNUDGLH
