! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

!OPTIONS XOPT(HSFUN)
SUBROUTINE RADACA ( YDEAERD,YDERAD,YDRIP, KIDIA , KFDIA , KLON , KLEV,&
 & PAPRS , PGELAM, PSIN  , PCLON, PSLON , PTH,&
 & PAER  , PAERO , POZON , PAERSIG,&
 & PODTO , PODSS , PODDU , PODOM, PODBC , PODSU )  

!***********************************************************************
! CAUTION: THIS ROUTINE WORKS ONLY ON A NON-ROTATED, UNSTRETCHED GRID
!***********************************************************************

!**** *RADACA  - COMPUTES DISTRIBUTION OF AEROSOLS AND OZONE
!                >>> FOR ASSIMILATION AND UV-DIAGNOSTIC PURPOSES <<

!     PURPOSE.!     --------

!**   INTERFACE.
!     ----------
!        CALL *RADACA* FROM *RADINA*
!                      FROM *CALLPAR* for UV diagnostics 

!        EXPLICIT ARGUMENTS :
!        --------------------
!     ==== INPUTS ===
!     ==== OUTPUTS ===

!        IMPLICIT ARGUMENTS :   NONE
!        --------------------

!     METHOD.
!     -------

!     EXTERNALS.
!     ----------

!          NONE

!     REFERENCE.
!     ----------

!        SEE RADIATION'S PART OF THE MODEL'S DOCUMENTATION AND
!        ECMWF RESEARCH DEPARTMENT DOCUMENTATION OF THE "I.F.S"

!     AUTHOR.
!     -------
!      J.-F. MAHFOUF    E.C.M.W.F.    97/07/04
!      Adapted from J.-J. MORCRETTE  E.C.M.W.F.    91/03/15

!     MODIFICATIONS.
!     --------------
!      JJMorcrette  03-05-01     Tegen et al's aerosols
!      J.HAGUE      01/07/03     Modified for bit reproducibility
!      M.Hamrud      01-Oct-2003 CY28 Cleaning
!      JJMorcrette 20080206 revised use of GISS history of volcanic aerosols
!      JJMorcrette 20120813 new 2D (lat-lon) MACC-derived aerosol climatology
!      R.Hogan     20221128 CAMS-climatology from call to CALC_PROFILES; SI units for aerosol extinction
!      R.Hogan     20221216 Removed Tanre aerosols; removed LNEWAER (always true)
!  
!-----------------------------------------------------------------------

USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMCST   , ONLY : RG, RPI
USE YOEAERD  , ONLY : TEAERD
USE YOERAD   , ONLY : TERAD
USE YOMRIP   , ONLY : TRIP

IMPLICIT NONE

TYPE(TEAERD)      ,INTENT(INOUT) :: YDEAERD
TYPE(TERAD)       ,INTENT(INOUT) :: YDERAD
TYPE(TRIP)        ,INTENT(IN)    :: YDRIP
INTEGER(KIND=JPIM),INTENT(IN)    :: KLON 
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEV 
INTEGER(KIND=JPIM),INTENT(IN)    :: KIDIA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KFDIA 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PAPRS(KLON,0:KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGELAM(KLON) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSIN(KLON) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PCLON(KLON) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSLON(KLON) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTH(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PAER(KLON,6,KLEV) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PAERO(KLON,KLEV,YDERAD%YAER_RAD_DESC%NAEROSOL)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: POZON(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PAERSIG(KLON) ! Extinction coefficient of surface aerosols (m-1)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PODTO(KLON), PODSS(KLON), PODDU(KLON)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PODOM(KLON), PODBC(KLON), PODSU(KLON)
!     -----------------------------------------------------------------

INTEGER(KIND=JPIM) :: IINLA1(KLON), IINLA2(KLON)
INTEGER(KIND=JPIM) :: IINLO1(KLON), IINLO2(KLON)

REAL(KIND=JPRB) :: ZAERBC(KLON), ZAEROR(KLON), ZAERSD(KLON)
REAL(KIND=JPRB) :: ZAERSS(KLON), ZAERSU(KLON), ZAERVO(KLON)
REAL(KIND=JPRB) :: ZSILAT(KLON), ZSINR(181), ZLONR(360), ZLON(KLON), ZNLO1(KLON), ZNLO2(KLON)

INTEGER(KIND=JPIM) :: INLA, INLA1, INLA2, INLO1, INLO2, &
 & JLR, ITLATR, ITLONR, JAER , JSW

REAL(KIND=JPRB) :: ZAERBC1, ZAERBC2, ZAEROR1, ZAEROR2, ZAERSD1, ZAERSD2, &
 & ZAERSS1, ZAERSS2, ZAERSU1, ZAERSU2  
REAL(KIND=JPRB) :: ZDLONR, ZGRIDR, ZLATR
!--

REAL(KIND=JPRB) :: ZALP(66,KLON)
REAL(KIND=JPRB) :: ZFOZQ(11,KLON),ZFOZH(11,KLON)

REAL(KIND=JPRB) :: ZDPN (KLON) ,ZDPO (KLON) ,ZQOFN(KLON) ,ZQOFO(KLON)
REAL(KIND=JPRB) :: ZOZH (KLON) ,ZOZQ (KLON)
REAL(KIND=JPRB) :: ZAEQSN(KLON),ZAEQSO(KLON),ZAEQLN(KLON),ZAEQLO(KLON)
REAL(KIND=JPRB) :: ZAEQUN(KLON),ZAEQUO(KLON),ZAEQDN(KLON),ZAEQDO(KLON)
REAL(KIND=JPRB) :: ZAETRN(KLON),ZAETRO(KLON)
REAL(KIND=JPRB) :: ZSIN(KLON)  ,ZSTRDEP(KLON)

!--

INTEGER(KIND=JPIM) :: IMM, IMNC, IMNS
INTEGER(KIND=JPIM) :: JK, JL, JMM, JNN, JV

REAL(KIND=JPRB) :: ZAETR, ZCPHN3, &
     & ZCPHO3, ZDPNMO, ZSDPN3, ZSDPO3
REAL(KIND=JPRB) :: ZCOS1, ZCOS2, ZCOS3, ZCOS4, ZCOS5
REAL(KIND=JPRB) :: ZSIN1, ZSIN2, ZSIN3, ZSIN4, ZSIN5

REAL(KIND=JPRB) :: ZDP

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "abor1.intfb.h"
#include "legtriv.intfb.h"

!     ------------------------------------------------------------------

!*         1.     "NEW AEROSOL DISTRIBUTION" PARAMETERS COMPUTATIONS
!                 --------------------------------------------------


!*         1.1    VOLCANIC AEROSOL DISTRIBUTION PARAMETERS
!                 ----------------------------------------

!                 GISS CLIMATOLOGY, APPLIED TO SULPHATE AEROSOLS 
!                 ----------------------------------------------

IF (LHOOK) CALL DR_HOOK('RADACA',0,ZHOOK_HANDLE)
ASSOCIATE(CVDAED=>YDEAERD%CVDAED, CVDAEL=>YDEAERD%CVDAEL, &
 & CVDAES=>YDEAERD%CVDAES, CVDAEU=>YDEAERD%CVDAEU, RAEDC=>YDEAERD%RAEDC, &
 & RAEDS=>YDEAERD%RAEDS, RAELC=>YDEAERD%RAELC, RAELS=>YDEAERD%RAELS, &
 & RAESC=>YDEAERD%RAESC, RAESS=>YDEAERD%RAESS, RAEUC=>YDEAERD%RAEUC, &
 & RAEUS=>YDEAERD%RAEUS, RCAEOPD=>YDEAERD%RCAEOPD, RCAEOPL=>YDEAERD%RCAEOPL, &
 & RCAEOPS=>YDEAERD%RCAEOPS, RCAEOPU=>YDEAERD%RCAEOPU, &
 & RCSTBGA=>YDEAERD%RCSTBGA, RCTRBGA=>YDEAERD%RCTRBGA, RCTRPT=>YDEAERD%RCTRPT, &
 & RCVOBGA=>YDEAERD%RCVOBGA, &
 & CVDAEBC=>YDERAD%CVDAEBC, CVDAEDU=>YDERAD%CVDAEDU, CVDAEOM=>YDERAD%CVDAEOM, &
 & CVDAESS=>YDERAD%CVDAESS, CVDAESU=>YDERAD%CVDAESU, &
 & LAERADJDU=>YDERAD%LAERADJDU, LHVOLCA=>YDERAD%LHVOLCA, &
 & NAERMACC=>YDERAD%NAERMACC, &
 & YDEOZOC=>YDRIP%YREOZOC, YDEAERC=>YDRIP%YREAERC, YDEAERC_TEGEN=>YDRIP%YREAERC_TEGEN)
IF (LHVOLCA) THEN
  ITLATR=46
  ZGRIDR=180._JPRB/(ITLATR-1)
  DO JLR=1,ITLATR
    ZLATR=90._JPRB-(JLR-1)*ZGRIDR
    ZSINR(JLR)=SIN(ZLATR*RPI/180._JPRB)
  ENDDO

  DO JL=KIDIA,KFDIA
    INLA=0
    ZSILAT(JL)=-9999._JPRB
    DO JLR=1,ITLATR-1
      IF (PSIN(JL) <= ZSINR(JLR) .AND. PSIN(JL) > ZSINR(JLR+1)) THEN
        INLA=JLR
        ZSILAT(JL)=(PSIN(JL)-ZSINR(INLA))/(ZSINR(INLA+1)-ZSINR(INLA))
        ZAERVO(JL)=YDEAERC_TEGEN%RTAEVO(INLA)+ZSILAT(JL)*(YDEAERC_TEGEN%RTAEVO(INLA+1)-YDEAERC_TEGEN%RTAEVO(INLA))
      ENDIF
    ENDDO
    IF (PSIN(JL) <= ZSINR(ITLATR-1) .AND. PSIN(JL) >= ZSINR(ITLATR))THEN
      INLA=ITLATR
      ZSILAT(JL)=(PSIN(JL)-ZSINR(INLA-1))/(ZSINR(INLA)-ZSINR(INLA-1))
      ZAERVO(JL)=YDEAERC_TEGEN%RTAEVO(INLA-1)&
       & +ZSILAT(JL)*(YDEAERC_TEGEN%RTAEVO(INLA)-YDEAERC_TEGEN%RTAEVO(INLA-1))  
    ENDIF
    IF (INLA == 0) THEN
      CALL ABOR1(' Problem with lat. interpolation in radaca!')
    ENDIF
    ZDPO(JL)=PAPRS(JL,0)
    ZAETRO(JL)=1.0_JPRB
    ZSTRDEP(JL)=0.0_JPRB
  ENDDO

!-- define how thick the stratosphere is in pressure units
  DO JK=1,KLEV
    DO JL=KIDIA,KFDIA
      ZDPN(JL)=PAPRS(JL,JK)
      IF (0.5_JPRB*(PAPRS(JL,JK-1)+PAPRS(JL,JK)) < 999._JPRB) THEN
! for models with top above 10hPa
        ZAETRN(JL)=1.0_JPRB
        ZAETRO(JL)=1.0_JPRB
      ELSE
        ZAETRN(JL)=ZAETRO(JL)*(MIN(1.0_JPRB,PTH(JL,JK)/PTH(JL,JK+1)))**RCTRPT
      ENDIF
      ZAETR=SQRT(ZAETRN(JL)*ZAETRO(JL))
      ZDPNMO=ZDPN(JL)-ZDPO(JL)
      ZSTRDEP(JL)=ZSTRDEP(JL)+ZAETR*ZDPNMO
    ENDDO
    DO JL=KIDIA,KFDIA
      ZDPO(JL)  =ZDPN(JL)
      ZAETRO(JL)=ZAETRN(JL)
    ENDDO
  ENDDO
!-- 
  DO JL=KIDIA,KFDIA
    ZAERVO(JL)=ZAERVO(JL)/ZSTRDEP(JL)
  ENDDO

!                 TANRE ET AL. CLIMATOLOGY 
!                 ------------------------

ELSE
  DO JL=KIDIA,KFDIA
    ZAERVO(JL)=RCSTBGA
  ENDDO
ENDIF

!*         1.2    TROPOSPHERIC AEROSOL DISTRIBUTION PARAMETERS
!                 --------------------------------------------

!IF (LNEWAER) THEN

!* -- Tegen et al. 1997 aerosol climatology


!-- latitude       
  ITLATR=46
  ZGRIDR=180._JPRB/(ITLATR-1)
  DO JLR=1,ITLATR
    ZLATR=90._JPRB-(JLR-1)*ZGRIDR
    ZSINR(JLR)=SIN(ZLATR*RPI/180._JPRB)
  ENDDO
  ITLONR=72
  ZDLONR=2._JPRB*RPI/ITLONR
  DO JLR=1,ITLONR
    ZLONR(JLR)=(JLR-1)*ZDLONR
  ENDDO

  DO JL=KIDIA,KFDIA         
    IINLA1(JL)=0
    IINLA2(JL)=0
    ZSILAT(JL)=-9999._JPRB
        DO JLR=1,ITLATR-1
      IF (PSIN(JL) <= ZSINR(JLR) .AND. PSIN(JL) > ZSINR(JLR+1)) THEN
        INLA=JLR
        IINLA1(JL)=JLR
        IINLA2(JL)=JLR+1
        ZSILAT(JL)=(PSIN(JL)-ZSINR(INLA))/(ZSINR(INLA+1)-ZSINR(INLA))
      ENDIF
    ENDDO
    IF (PSIN(JL) <= ZSINR(ITLATR-1) .AND. PSIN(JL) >= ZSINR(ITLATR))THEN
      INLA=ITLATR
      IINLA1(JL)=ITLATR-1
      IINLA2(JL)=ITLATR
      ZSILAT(JL)=(PSIN(JL)-ZSINR(INLA-1))/(ZSINR(INLA)-ZSINR(INLA-1))
    ENDIF    
    IF (INLA == 0) THEN 
      CALL ABOR1(' Problem with lat. interpolation in radaca!')
    ENDIF
  ENDDO  

!-- longitude
  DO JL=KIDIA,KFDIA
    IINLO1(JL)=0
    IINLO2(JL)=0
    ZLON(JL)=-9999.
    DO JLR=1,71
      IF (PGELAM(JL) < ZLONR(JLR+1) .AND. PGELAM(JL) >= ZLONR(JLR))&
         & THEN  
        IINLO1(JL)=JLR
        IINLO2(JL)=JLR+1
        ZNLO1(JL)=ZLONR(JLR)
        ZNLO2(JL)=ZLONR(JLR+1)
      ENDIF
    ENDDO      
    IF (PGELAM(JL) >= ZLONR(72)) THEN
      IINLO1(JL)=72
      IINLO2(JL)= 1
      ZNLO1(JL)=ZLONR(72)
!      ZNLO2(JL)=ZLONR(72)+2.*RPI
      ZNLO2(JL)=ZLONR(72)+ZDLONR
    ENDIF
  ENDDO  
 
  DO JL=KIDIA,KFDIA
    IF (IINLO1(JL) == 0 .OR. IINLO2(JL) == 0) THEN 
      CALL ABOR1(' Problem with long. interpolation in radaca!')
    ENDIF
    ZLON(JL)=(PGELAM(JL)-ZNLO1(JL))/(ZNLO2(JL)-ZNLO1(JL))
    INLO1=IINLO1(JL)
    INLO2=IINLO2(JL)
    INLA1=IINLA1(JL)
    INLA2=IINLA2(JL)
    
    ZAERBC1=YDEAERC_TEGEN%RTAEBC(INLO1,INLA1)&
     & +ZSILAT(JL)*(YDEAERC_TEGEN%RTAEBC(INLO1,INLA2)-YDEAERC_TEGEN%RTAEBC(INLO1,INLA1))    
    ZAERBC2=YDEAERC_TEGEN%RTAEBC(INLO2,INLA1)&
     & +ZSILAT(JL)*(YDEAERC_TEGEN%RTAEBC(INLO2,INLA2)-YDEAERC_TEGEN%RTAEBC(INLO2,INLA1))    
    ZAERBC(JL)=ZAERBC1+ZLON(JL)*(ZAERBC2-ZAERBC1)
        
    ZAEROR1=YDEAERC_TEGEN%RTAEOR(INLO1,INLA1)&
     & +ZSILAT(JL)*(YDEAERC_TEGEN%RTAEOR(INLO1,INLA2)-YDEAERC_TEGEN%RTAEOR(INLO1,INLA1))    
    ZAEROR2=YDEAERC_TEGEN%RTAEOR(INLO2,INLA1)&
     & +ZSILAT(JL)*(YDEAERC_TEGEN%RTAEOR(INLO2,INLA2)-YDEAERC_TEGEN%RTAEOR(INLO2,INLA1))    
    ZAEROR(JL)=ZAEROR1+ZLON(JL)*(ZAEROR2-ZAEROR1)
        
    ZAERSD1=YDEAERC_TEGEN%RTAESD(INLO1,INLA1)&
     & +ZSILAT(JL)*(YDEAERC_TEGEN%RTAESD(INLO1,INLA2)-YDEAERC_TEGEN%RTAESD(INLO1,INLA1))    
    ZAERSD2=YDEAERC_TEGEN%RTAESD(INLO2,INLA1)&
     & +ZSILAT(JL)*(YDEAERC_TEGEN%RTAESD(INLO2,INLA2)-YDEAERC_TEGEN%RTAESD(INLO2,INLA1))    
    ZAERSD(JL)=ZAERSD1+ZLON(JL)*(ZAERSD2-ZAERSD1)
        
    ZAERSS1=YDEAERC_TEGEN%RTAESS(INLO1,INLA1)&
     & +ZSILAT(JL)*(YDEAERC_TEGEN%RTAESS(INLO1,INLA2)-YDEAERC_TEGEN%RTAESS(INLO1,INLA1))    
    ZAERSS2=YDEAERC_TEGEN%RTAESS(INLO2,INLA1)&
     & +ZSILAT(JL)*(YDEAERC_TEGEN%RTAESS(INLO2,INLA2)-YDEAERC_TEGEN%RTAESS(INLO2,INLA1))    
    ZAERSS(JL)=ZAERSS1+ZLON(JL)*(ZAERSS2-ZAERSS1)
        
    ZAERSU1=YDEAERC_TEGEN%RTAESU(INLO1,INLA1)&
     & +ZSILAT(JL)*(YDEAERC_TEGEN%RTAESU(INLO1,INLA2)-YDEAERC_TEGEN%RTAESU(INLO1,INLA1))    
    ZAERSU2=YDEAERC_TEGEN%RTAESU(INLO2,INLA1)&
     & +ZSILAT(JL)*(YDEAERC_TEGEN%RTAESU(INLO2,INLA2)-YDEAERC_TEGEN%RTAESU(INLO2,INLA1))    
    ZAERSU(JL)=ZAERSU1+ZLON(JL)*(ZAERSU2-ZAERSU1)
                 
  ENDDO       
!ENDIF

!- replacing TEGEN climatology by MACC-derived mmr climatology in the 
!  troposphere

DO JV=1,YDERAD%YAER_RAD_DESC%NAEROSOL
  DO JK=1,KLEV
    DO JL=1,KLON
      PAERO(JL,JK,JV)=0._JPRB
    ENDDO
  ENDDO
ENDDO     

!     ------------------------------------------------------------------

!*         2.     OZONE
!                 -----

DO JL=KIDIA,KFDIA
  ZSIN(JL)=PSIN(JL)
ENDDO

!*       2.1     CALL TO LEGTRI.

!***
CALL LEGTRIV(ZSIN(KIDIA),6,66,ZALP,KFDIA-KIDIA+1)
!***

!*       2.2     *LEGENDRE TRANSFORM FOR OZONE.

DO JL=KIDIA,KFDIA
  DO JMM=1,11
    ZFOZQ(JMM,JL)=0.0_JPRB
    ZFOZH(JMM,JL)=0.0_JPRB
  ENDDO
  IMM=0
  IMNC=0
  IMNS=0
  DO JMM=1,6
    IMM=IMM+1
    DO JNN=JMM,6
      IMNC=IMNC+1
      ZFOZQ(IMM,JL)=ZFOZQ(IMM,JL)+ZALP(IMNC,JL)*YDEOZOC%COZQC(IMNC)
      ZFOZH(IMM,JL)=ZFOZH(IMM,JL)+ZALP(IMNC,JL)*YDEOZOC%COZHC(IMNC)
    ENDDO
    IF(JMM /= 1) THEN
      IMM=IMM+1
      DO JNN=JMM,6
        IMNS=IMNS+1
        ZFOZQ(IMM,JL)=ZFOZQ(IMM,JL)+ZALP(IMNS+6,JL)*YDEOZOC%COZQS(IMNS)
        ZFOZH(IMM,JL)=ZFOZH(IMM,JL)+ZALP(IMNS+6,JL)*YDEOZOC%COZHS(IMNS)
      ENDDO
    ENDIF
  ENDDO
ENDDO

!*       2.3     FOURIER TRANSFORM FOR OZONE.

DO JL=KIDIA,KFDIA
  ZCOS1=PCLON(JL)
  ZSIN1=PSLON(JL)
  ZCOS2=ZCOS1*ZCOS1-ZSIN1*ZSIN1
  ZSIN2=ZSIN1*ZCOS1+ZCOS1*ZSIN1
  ZCOS3=ZCOS2*ZCOS1-ZSIN2*ZSIN1
  ZSIN3=ZSIN2*ZCOS1+ZCOS2*ZSIN1
  ZCOS4=ZCOS3*ZCOS1-ZSIN3*ZSIN1
  ZSIN4=ZSIN3*ZCOS1+ZCOS3*ZSIN1
  ZCOS5=ZCOS4*ZCOS1-ZSIN4*ZSIN1
  ZSIN5=ZSIN4*ZCOS1+ZCOS4*ZSIN1
  ZOZQ(JL)=&
   & ZFOZQ(1,JL)+2.0_JPRB*(ZFOZQ(2,JL)*ZCOS1+ZFOZQ(3,JL)*ZSIN1+ZFOZQ(4,JL)*ZCOS2&
   & +ZFOZQ(5,JL)*ZSIN2+ZFOZQ(6,JL)*ZCOS3+ZFOZQ(7,JL)*ZSIN3+ZFOZQ(8,JL)&
   & *ZCOS4+ZFOZQ(9,JL)*ZSIN4+ZFOZQ(10,JL)*ZCOS5+ZFOZQ(11,JL)*ZSIN5)  
  ZOZH(JL)=&
   & ZFOZH(1,JL)+2.0_JPRB*(ZFOZH(2,JL)*ZCOS1+ZFOZH(3,JL)*ZSIN1+ZFOZH(4,JL)*ZCOS2&
   & +ZFOZH(5,JL)*ZSIN2+ZFOZH(6,JL)*ZCOS3+ZFOZH(7,JL)*ZSIN3+ZFOZH(8,JL)&
   & *ZCOS4+ZFOZH(9,JL)*ZSIN4+ZFOZH(10,JL)*ZCOS5+ZFOZH(11,JL)*ZSIN5)  
  ZOZH(JL)=SQRT(ZOZH(JL))**3
ENDDO

!     ------------------------------------------------------------------

!       3.     AEROSOLS
!              --------
! Tanre aerosol calculations removed 2022-12-16

!*         4.      VERTICAL DISTRIBUTION
!*                 ---------------------

DO JL=KIDIA,KFDIA
  ZDPO(JL)=PAPRS (JL,0)
  ZCPHO3=PAPRS (JL,0)**3
  ZSDPO3=SQRT  (ZCPHO3)
  
  ZAEQSO(JL)= ZAERSS(JL)*CVDAES(1)
  ZAEQLO(JL)=(ZAEROR(JL)+ZAERSU(JL))*CVDAEL(1)
  ZAEQUO(JL)= ZAERBC(JL)*CVDAEU(1)
  ZAEQDO(JL)= ZAERSD(JL)*CVDAED(1)
  PODSS(JL)=ZAERSS(JL)
  PODDU(JL)=ZAERSD(JL)
  PODOM(JL)=ZAEROR(JL)
  PODBC(JL)=ZAERBC(JL)
  PODSU(JL)=ZAERSU(JL)
  PODTO(JL)=ZAERSS(JL)+ZAERSD(JL)+ZAEROR(JL)+ZAERBC(JL)+ZAERSU(JL)

  ZAETRO(JL)=1.0_JPRB
  ZQOFO(JL)=ZOZQ(JL)*ZSDPO3 / (ZSDPO3 + ZOZH(JL))
ENDDO

DO JK=1,KLEV
!DIR$ IVDEP
  DO JL=KIDIA,KFDIA
    ZDPN(JL)=PAPRS (JL,JK)
    ZCPHN3=PAPRS (JL,JK)**3
    ZSDPN3=SQRT  (ZCPHN3)

    ZAEQSN(JL)= ZAERSS(JL)*CVDAES(JK+1)
    ZAEQLN(JL)=(ZAEROR(JL)+ZAERSU(JL))*CVDAEL(JK+1)
    ZAEQUN(JL)= ZAERBC(JL)*CVDAEU(JK+1)
    ZAEQDN(JL)= ZAERSD(JL)*CVDAED(JK+1)

    IF (0.5_JPRB*(PAPRS(JL,JK-1)+PAPRS(JL,JK)) < 999._JPRB) THEN
! for models with top above 10hPa
      ZAETRN(JL)=1.0_JPRB
      ZAETRO(JL)=1.0_JPRB
    ELSE
      ZAETRN(JL)=ZAETRO(JL)*(MIN(1.0_JPRB,PTH(JL,JK)/PTH(JL,JK+1)))**RCTRPT
    ENDIF

    ZAETR=SQRT  (ZAETRN(JL)*ZAETRO(JL))
    ZQOFN(JL)=ZOZQ(JL)*ZSDPN3/(ZSDPN3+ZOZH(JL))
    ZDPNMO    =ZDPN(JL)-ZDPO(JL)
    PAER(JL,1,JK)=(1.0_JPRB-ZAETR)*(RCTRBGA*ZDPNMO+ ZAEQLN(JL)-ZAEQLO(JL))
    PAER(JL,2,JK)=(1.0_JPRB-ZAETR)*(ZAEQSN(JL)-ZAEQSO(JL))
    PAER(JL,3,JK)=(1.0_JPRB-ZAETR)*(ZAEQDN(JL)-ZAEQDO(JL))
    PAER(JL,4,JK)=(1.0_JPRB-ZAETR)*(ZAEQUN(JL)-ZAEQUO(JL))
! time variation applied to volcanic sulphate aerosols only - ash is background value
    PAER(JL,5,JK)= ZAETR * RCVOBGA*ZDPNMO
    PAER(JL,6,JK)= ZAETR * ZAERVO(JL)*ZDPNMO
!old RH dependence     
!         AADS(JL,JK)=MAX(RCAEADM, (RCAEADK(1)*PAER(JL,1,JK)
!           + RCAEADK(2)*PAER(JL,2,JK)+RCAEADK(3)*PAER(JL,3,JK))/ZDPNMO)
    POZON(JL,JK)=ZQOFN(JL)-ZQOFO(JL)
  ENDDO
  DO JL=KIDIA,KFDIA
    ZDPO(JL)  =ZDPN(JL)
    ZQOFO(JL) =ZQOFN(JL)
    ZAEQSO(JL)=ZAEQSN(JL)
    ZAEQLO(JL)=ZAEQLN(JL)
    ZAEQUO(JL)=ZAEQUN(JL)
    ZAEQDO(JL)=ZAEQDN(JL)
    ZAETRO(JL)=ZAETRN(JL)
     ENDDO

!-- diagnostics in case of problem  
  DO JAER=1,6
    DO JL=KIDIA,KFDIA
      PAER(JL,JAER,JK)=MAX(PAER(JL,JAER,JK),YDRIP%YREAERC_TEGEN%REPAER)
    ENDDO
  ENDDO   

ENDDO

! Load aerosol climatology, leaving gaps for any other types (prognostic or parametric)
IF (YDERAD%YAER_RAD_DESC%NCLIMATOLOGICAL > 0) THEN
  CALL YDEAERC%CALC_PROFILES(KIDIA,KFDIA,KLON,KLEV,PSIN,PGELAM,PAPRS,PAERO,LDLEAVESPACE=.TRUE.)
ENDIF


!*         5.      EQUIVALENT SCATTERING CROSS-SECTION IN LAYER ABOVE SURFACE
!*                 ----------------------------------------------------------

JSW=10
DO JL=KIDIA,KFDIA
  PAERSIG(JL)=0._JPRB
ENDDO
DO JAER=1,6
  DO JL=KIDIA,KFDIA
    ZDP = PAPRS(JL,KLEV)-PAPRS(JL,KLEV-1)
!-- reference optical depth is already at 550 nm (no need to introduce the RTAUA)
    PAERSIG(JL) = PAERSIG(JL) + PAER(JL,JAER,KLEV)*(RG/ZDP)
  ENDDO
ENDDO
!     ------------------------------------------------------------------

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('RADACA',1,ZHOOK_HANDLE)
END SUBROUTINE RADACA
