! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE GP_MODEL_DRV(YDGEO,YDFIELDS,MDL,CDCONF,LD_DFISTEP,PTRAJEC,PTRAJEC_OOPS)
USE PARKIND1,ONLY: JPIM,JPRB
USE YOMLUN,ONLY: NULERR
USE YOMHOOK,ONLY: LHOOK,DR_HOOK, JPHOOK
USE YOMCT0,ONLY: NOPT_MEMORY
USE GEOMETRY_MOD,ONLY: GEOMETRY
USE FIELDS_MOD,ONLY: FIELDS
USE TYPE_MODEL,ONLY: MODEL
USE YOMTRAJ,ONLY: TRAJ_TYPE
USE YOMTRAJ_OOPS,ONLY: TRAJ_TYPE_OOPS
USE YOMCT3,ONLY: NSTEP
USE YOMCT0,ONLY: L_OOPS

IMPLICIT NONE

TYPE(GEOMETRY),INTENT(IN) :: YDGEO
TYPE(FIELDS),INTENT(INOUT) :: YDFIELDS
TYPE(MODEL),INTENT(INOUT) :: MDL
CHARACTER(LEN=9),INTENT(IN) :: CDCONF
TYPE(TRAJ_TYPE),OPTIONAL,INTENT(INOUT) :: PTRAJEC
TYPE(TRAJ_TYPE_OOPS),OPTIONAL,INTENT(INOUT) :: PTRAJEC_OOPS
LOGICAL,INTENT(IN) :: LD_DFISTEP

INTEGER(KIND=JPIM),SAVE :: NPROMA=0,NFLEVG=0,NGPBLKS=0,NASLB1=0,NFB1=0,NFB2=0,NGR=0
REAL(KIND=JPRB),ALLOCATABLE,SAVE :: ZZB1(:,:),ZZB2(:,:,:),ZZGRADPHY(:,:,:,:)
REAL(KIND=JPRB),ALLOCATABLE :: ZB1(:,:),ZB2(:,:,:),ZGRADPHY(:,:,:,:)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "gp_model.intfb.h"

IF (LHOOK) CALL DR_HOOK("GP_MODEL_DRV",0,ZHOOK_HANDLE)

ASSOCIATE(DIMG=>YDGEO%YRDIM,DIMV=>YDGEO%YRDIMV,MDLDYN=>MDL%YRML_DYN,MDLMF=>MDL%YRML_PHY_MF)
ASSOCIATE(YDSL=>MDLDYN%YRSL,YDPTRSLB1=>MDLDYN%YRPTRSLB1,YDPTRSLB2=>MDLDYN%YRPTRSLB2)

IF (NOPT_MEMORY == 1) THEN
  CALL GP_MODELSTACK(YDGEO,YDFIELDS,MDL,CDCONF,LD_DFISTEP,PTRAJEC=PTRAJEC,&
   & PTRAJEC_OOPS=PTRAJEC_OOPS)
ELSE IF (NOPT_MEMORY == 0) THEN
  ALLOCATE(ZB1(YDSL%NASLB1,YDPTRSLB1%NFLDSLB1))
  ALLOCATE(ZB2(DIMG%NPROMA,YDPTRSLB2%NFLDSLB2,DIMG%NGPBLKS))
  ALLOCATE(ZGRADPHY(DIMG%NPROMA,MDLMF%YRARPHY%NGRADIENTS,DIMV%NFLEVG,DIMG%NGPBLKS))

  CALL GP_MODEL(YDGEO,YDFIELDS,MDL,CDCONF,LD_DFISTEP,ZB1,ZB2,ZGRADPHY,PTRAJEC=PTRAJEC,&
   & PTRAJEC_OOPS=PTRAJEC_OOPS)

  DEALLOCATE(ZGRADPHY)
  DEALLOCATE(ZB2)
  DEALLOCATE(ZB1)
ELSE
  ! deallocate if needed
  IF (ALLOCATED(ZZB1).AND.(NPROMA /= DIMG%NPROMA.OR.NFLEVG /= DIMV%NFLEVG.OR.&
    NGPBLKS /= DIMG%NGPBLKS.OR.NASLB1 /= YDSL%NASLB1.OR.NFB1 /= YDPTRSLB1%NFLDSLB1.OR.&
    NFB2 /= YDPTRSLB2%NFLDSLB2.OR.NGR /= MDLMF%YRARPHY%NGRADIENTS)) THEN
    WRITE(NULERR,*) "WARNING: DEALLOCATION/REALLOCATION OF PERMANENT ARRAYS"
    WRITE(NULERR,*) "OLD DIMS:",NPROMA,NFLEVG,NGPBLKS,NASLB1,NFB1,NFB2,NGR
    WRITE(NULERR,*) "NEW DIMS:",DIMG%NPROMA,DIMV%NFLEVG,DIMG%NGPBLKS,YDSL%NASLB1,&
       YDPTRSLB1%NFLDSLB1,YDPTRSLB2%NFLDSLB2,MDLMF%YRARPHY%NGRADIENTS

    DEALLOCATE(ZZGRADPHY)
    DEALLOCATE(ZZB2)
    DEALLOCATE(ZZB1)
  ENDIF

  ! allocate if needed
  IF (.NOT.ALLOCATED(ZZB1)) THEN
    NPROMA = DIMG%NPROMA
    NFLEVG = DIMV%NFLEVG
    NGPBLKS = DIMG%NGPBLKS
    NASLB1 = YDSL%NASLB1
    NFB1 = YDPTRSLB1%NFLDSLB1
    NFB2 = YDPTRSLB2%NFLDSLB2
    NGR = MDLMF%YRARPHY%NGRADIENTS

    ALLOCATE(ZZB1(NASLB1,NFB1))
    ALLOCATE(ZZB2(NPROMA,NFB2,NGPBLKS))
    ALLOCATE(ZZGRADPHY(NPROMA,NGR,NFLEVG,NGPBLKS))
  ENDIF

  CALL GP_MODEL(YDGEO,YDFIELDS,MDL,CDCONF,LD_DFISTEP,ZZB1,ZZB2,ZZGRADPHY,PTRAJEC=PTRAJEC,&
   & PTRAJEC_OOPS=PTRAJEC_OOPS)

  IF (L_OOPS .AND. (NOPT_MEMORY==2) .AND. (NSTEP==(MDL%YRML_GCONF%YRRIP%NSTOP-1))) THEN
    DEALLOCATE(ZZGRADPHY)
    DEALLOCATE(ZZB2)
    DEALLOCATE(ZZB1)
  ENDIF
ENDIF
END ASSOCIATE
END ASSOCIATE

IF (LHOOK) CALL DR_HOOK("GP_MODEL_DRV",1,ZHOOK_HANDLE)
CONTAINS
  SUBROUTINE GP_MODELSTACK(YDGEO,YDFIELDS,MDL,CDCONF,LD_DFISTEP,PTRAJEC,PTRAJEC_OOPS)
    TYPE(GEOMETRY),INTENT(IN) :: YDGEO
    TYPE(FIELDS),INTENT(INOUT) :: YDFIELDS
    TYPE(MODEL),INTENT(INOUT) :: MDL
    CHARACTER(LEN=9),INTENT(IN) :: CDCONF
    TYPE(TRAJ_TYPE),OPTIONAL,INTENT(INOUT) :: PTRAJEC
    TYPE(TRAJ_TYPE_OOPS),OPTIONAL,INTENT(INOUT) :: PTRAJEC_OOPS
    LOGICAL,INTENT(IN) :: LD_DFISTEP

    REAL(KIND=JPRB) :: ZB1(MDL%YRML_DYN%YRSL%NASLB1,MDL%YRML_DYN%YRPTRSLB1%NFLDSLB1),&
     & ZB2(YDGEO%YRDIM%NPROMA,MDL%YRML_DYN%YRPTRSLB2%NFLDSLB2,YDGEO%YRDIM%NGPBLKS),&
     & ZGRADPHY(YDGEO%YRDIM%NPROMA,MDL%YRML_PHY_MF%YRARPHY%NGRADIENTS,YDGEO%YRDIMV%NFLEVG,&
     & YDGEO%YRDIM%NGPBLKS)

    CALL GP_MODEL(YDGEO,YDFIELDS,MDL,CDCONF,LD_DFISTEP,ZB1,ZB2,ZGRADPHY,PTRAJEC=PTRAJEC,&
     &  PTRAJEC_OOPS=PTRAJEC_OOPS)
  END SUBROUTINE
END SUBROUTINE

