! (C) Copyright 1989- Meteo-France.

SUBROUTINE SUFPXFU(YDFPOS,YDXFU)

!**** *SUFPXFU*  - INITIALIZE INSTANTANEOUS FLUXES SWITCHES FOR POST-PROCESSING

!     PURPOSE.
!     --------
!        Modify default values to allow post-processing

!**   INTERFACE.
!     ----------
!       *CALL* *SUFPXFU*

!        EXPLICIT ARGUMENTS
!        --------------------
!        NONE

!        IMPLICIT ARGUMENTS
!        --------------------
!        YOMXFU

!     METHOD.
!     -------
!        SEE DOCUMENTATION

!     EXTERNALS.
!     ----------

!     REFERENCE.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     AUTHOR.
!     -------
!      RYAD EL KHATIB *METEO-FRANCE*
!      ORIGINAL : 94-04-08

!     MODIFICATIONS.
!     --------------
!      R. El Khatib : 01-04-23 LXQCLS, LXTTCLS,LXHHCLS
!      R. El Khatib : 01-08-07 Pruning options
!      R. El Khatib : 03-04-17 Fullpos improvments
!      M.Hamrud      01-Oct-2003 CY28 Cleaning
!      Y. Seity     : 07-01-23 Add graupel and hail 
!      F. Bouyssel  : 09-07-15 LFPCAPEX
!      K. Yessad (July 2014): Move some variables.
!      R. Brozkova (Sep 2018): Added mean radiant temperature.
!      R. El Khatib : 18-02-19 Bugfix for LFPCAPEX
!      V. Guidard :   13-05-19 Add new satellites-sensors for ISP
!     ------------------------------------------------------------------

USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK

USE YOMLUN   , ONLY : NULERR
USE YOMXFU   , ONLY : TXFU_KEYS
USE YOMFA    , ONLY : &
 & YFA_XTCC ,YFA_X10U ,YFA_X10V ,YFA_X10NU,YFA_X10NV, &
 & YFA_X2T  ,YFA_X2SH ,YFA_XCSH , YFA_XSIC, &
 & YFA_X2RH ,YFA_XCCC ,YFA_XHCC ,YFA_XMCC ,YFA_XUGST,YFA_XUGST2 ,YFA_XGUST, &
 & YFA_XLCC ,YFA_XX2T ,YFA_XN2T ,YFA_XCVU ,YFA_XVGST,YFA_XVGST2 ,YFA_XCLPH, &
 & YFA_XCVV ,YFA_XCVQ ,YFA_XCVS ,YFA_XTUU ,YFA_XTUV ,YFA_XMOCO, &
 & YFA_XTUQ ,YFA_XTUS ,YFA_XGDU ,YFA_XGDV ,YFA_XLSP ,YFA_XCAPE, YFA_XCTOP, &
 & YFA_XCP  ,YFA_XLSS ,YFA_XCSF ,YFA_XSSR ,YFA_XSTR ,YFA_X10FF, &
 & YFA_XTSR ,YFA_XTTR ,YFA_XX2HU,YFA_XN2HU,YFA_XLSG ,YFA_XCSG , YFA_X2TPW, &
 & YFA_XXDIAGH,YFA_XVEIN,YFA_XLSH, YFA_ASMC ,YFA_XMRT,&
 & YFA_VISICLD, YFA_VISIHYD, YFA_MXCLWC, YFA_VISICLD2, YFA_VISIHYD2, YFA_MXCLWC2, YFA_XPTYPE, &
 & YFA_XPTYPESEV, YFA_XPTYPE2, YFA_XPTYPESEV2
USE FULLPOS  , ONLY : TFPOS

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(TFPOS), INTENT(IN) :: YDFPOS
TYPE(TXFU_KEYS),INTENT(INOUT) :: YDXFU

CHARACTER :: CLMARK*39
INTEGER(KIND=JPIM) :: IU10, INU10, IUBL, IUCV, IUGW, IUTU, IV10, INV10, IVBL, IVCV, IVGW, IVTU, JFLD
INTEGER(KIND=JPIM) :: IUBL2, IVBL2

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

#include "abor1.intfb.h"

!     ------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('SUFPXFU',0,ZHOOK_HANDLE)
ASSOCIATE(CFPXFU=>YDFPOS%YNAMFPL%CFPXFU, CFP2DF=>YDFPOS%YNAMFPL%CFP2DF, LFPCAPEX=>YDFPOS%YNAMFPSCI%LFPCAPEX, &
 & LXCLP=>YDXFU%LXCLP, LXVEIN=>YDXFU%LXVEIN,LXCLS=>YDXFU%LXCLS, &
 & LXFU=>YDXFU%LXFU, LXHHCLS=>YDXFU%LXHHCLS, LXICV=>YDXFU%LXICV, LXCTOP=>YDXFU%LXCTOP,&
 & LXNEBPA=>YDXFU%LXNEBPA, LXNEBTT=>YDXFU%LXNEBTT, LXPLC=>YDXFU%LXPLC, &
 & LXPLCG=>YDXFU%LXPLCG, LXPLCH=>YDXFU%LXPLCH, LXPLS=>YDXFU%LXPLS, &
 & LXPLSG=>YDXFU%LXPLSG, LXPLSH=>YDXFU%LXPLSH, LXQCLS=>YDXFU%LXQCLS, &
 & LXR=>YDXFU%LXR, LXTGST=>YDXFU%LXTGST, LXTRC=>YDXFU%LXTRC, LXTRD=>YDXFU%LXTRD, &
 & LXTRT=>YDXFU%LXTRT, LXTTCLS=>YDXFU%LXTTCLS, LXXDIAGH=>YDXFU%LXXDIAGH,LXMRT=>YDXFU%LXMRT,&
 & LXVISI=>YDXFU%LXVISI,LXVISI2=>YDXFU%LXVISI2, LXTPWCLS=>YDXFU%LXTPWCLS,&
 & LXPRECIPS1=>YDXFU%LXPRECIPS1,LXPRECIPS2=>YDXFU%LXPRECIPS2)
!     ------------------------------------------------------------------

!*       1. MODIFY DEFAULT VALUES
!           ---------------------

  IU10=0
  IV10=0
  INU10=0
  INV10=0
  IUCV=0
  IVCV=0
  IUTU=0
  IVTU=0
  IUGW=0
  IVGW=0
  IUBL=0
  IVBL=0
  IUBL2=0
  IVBL2=0

DO JFLD=1,SIZE(CFPXFU)
  IF(CFPXFU(JFLD) == ' ') THEN
    LXFU=LXFU.OR.(JFLD > 1)
    EXIT
  ELSEIF     (CFPXFU(JFLD) == YFA_XTCC%CLNAME) THEN
    LXNEBTT=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_X10U%CLNAME) THEN
    LXCLS=.TRUE.
    IU10=1
  ELSEIF (CFPXFU(JFLD) == YFA_X10V%CLNAME) THEN
    LXCLS=.TRUE.
    IV10=1
  ELSEIF (CFPXFU(JFLD) == YFA_X10NU%CLNAME) THEN
    LXCLS=.TRUE.
    INU10=1
  ELSEIF (CFPXFU(JFLD) == YFA_X10NV%CLNAME) THEN
    LXCLS=.TRUE.
    INV10=1
  ELSEIF (CFPXFU(JFLD) == YFA_X2T%CLNAME ) THEN
    LXCLS=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_X2SH%CLNAME) THEN
    LXQCLS=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_X2RH%CLNAME) THEN
    LXCLS=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XSIC%CLNAME) THEN
    LXCLS=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XCCC%CLNAME) THEN
    LXNEBPA=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XHCC%CLNAME) THEN
    LXNEBPA=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XMCC%CLNAME) THEN
    LXNEBPA=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XLCC%CLNAME) THEN
    LXNEBPA=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XXDIAGH%CLNAME) THEN
    LXXDIAGH=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XX2T%CLNAME) THEN
    LXTTCLS=.TRUE.
    LXCLS=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XN2T%CLNAME) THEN
    LXTTCLS=.TRUE.
    LXCLS=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XX2HU%CLNAME) THEN
    LXHHCLS=.TRUE.
    LXCLS=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XN2HU%CLNAME) THEN
    LXHHCLS=.TRUE.
    LXCLS=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_X2TPW%CLNAME) THEN
    LXTPWCLS=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XCVU%CLNAME) THEN
    LXTRC=.TRUE.
    IUCV=1
  ELSEIF (CFPXFU(JFLD) == YFA_XCVV%CLNAME) THEN
    LXTRC=.TRUE.
    IVCV=1
  ELSEIF (CFPXFU(JFLD) == YFA_XCVQ%CLNAME) THEN
    LXTRC=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XCVS%CLNAME) THEN
    LXTRC=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XTUU%CLNAME) THEN
    LXTRT=.TRUE.
    IUTU=1
  ELSEIF (CFPXFU(JFLD) == YFA_XTUV%CLNAME) THEN
    LXTRT=.TRUE.
    IVTU=1
  ELSEIF (CFPXFU(JFLD) == YFA_XTUQ%CLNAME) THEN
    LXTRT=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XTUS%CLNAME) THEN
    LXTRT=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XGDU%CLNAME) THEN
    LXTRD=.TRUE.
    IUGW=1
  ELSEIF (CFPXFU(JFLD) == YFA_XGDV%CLNAME) THEN
    LXTRD=.TRUE.
    IVGW=1
  ELSEIF (CFPXFU(JFLD) == YFA_XLSP%CLNAME) THEN
    LXPLS=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XCP%CLNAME ) THEN
    LXPLC=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XLSS%CLNAME) THEN
    LXPLS=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XCSF%CLNAME) THEN
    LXPLC=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XLSG%CLNAME) THEN
    LXPLSG=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XCSG%CLNAME ) THEN
    LXPLCG=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XLSH%CLNAME) THEN
    LXPLSH=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XCSH%CLNAME ) THEN
    LXPLCH=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XSSR%CLNAME) THEN
    LXR=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XSTR%CLNAME) THEN
    LXR=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XTSR%CLNAME) THEN
    LXR=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XTTR%CLNAME) THEN
    LXR=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_X10FF%CLNAME) THEN
    LXCLS=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XCAPE%CLNAME) THEN
    LXICV=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XCTOP%CLNAME) THEN
    LXCTOP=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XMOCO%CLNAME) THEN
    LXICV=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XCLPH%CLNAME) THEN
    LXCLP=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XVEIN%CLNAME) THEN
    LXVEIN=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XMRT%CLNAME) THEN
    LXMRT=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XGUST%CLNAME) THEN
    LXTGST=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XUGST%CLNAME) THEN
    LXTGST=.TRUE.
    IUBL=1
  ELSEIF (CFPXFU(JFLD) == YFA_XVGST%CLNAME) THEN
    LXTGST=.TRUE.
    IVBL=1
  ELSEIF (CFPXFU(JFLD) == YFA_XUGST2%CLNAME) THEN
    LXTGST=.TRUE.
    IUBL2=1
  ELSEIF (CFPXFU(JFLD) == YFA_XVGST2%CLNAME) THEN
    LXTGST=.TRUE.
    IVBL2=1
  ELSEIF (CFPXFU(JFLD) == YFA_VISICLD%CLNAME) THEN
     LXVISI=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_VISIHYD%CLNAME) THEN
     LXVISI=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_MXCLWC%CLNAME) THEN
     LXVISI=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_VISICLD2%CLNAME) THEN
     LXVISI2=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_VISIHYD2%CLNAME) THEN
     LXVISI2=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_MXCLWC2%CLNAME) THEN
     LXVISI2=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XPTYPESEV%CLNAME) THEN
    LXPRECIPS1=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XPTYPE%CLNAME) THEN
    LXPRECIPS1=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XPTYPESEV2%CLNAME) THEN
    LXPRECIPS2=.TRUE.
  ELSEIF (CFPXFU(JFLD) == YFA_XPTYPE2%CLNAME) THEN
    LXPRECIPS2=.TRUE.
  ELSE
    CLMARK=CFPXFU(JFLD)//' NOT FOUND '
    WRITE(NULERR,*) CLMARK
  ENDIF
ENDDO
IF (IU10 /= IV10) THEN
  CALL ABOR1('U AND V 10 COMPONENTS ARE BOTH NECESSARY !')
ENDIF
IF (INU10 /= INV10) THEN
  CALL ABOR1('NU AND NV 10 COMPONENTS ARE BOTH NECESSARY !')
ENDIF
IF (IUTU /= IVTU) THEN
  CALL ABOR1('U AND V TU COMPONENTS ARE BOTH NECESSARY !')
ENDIF
IF (IUBL /= IVBL) THEN
  CALL ABOR1('U AND V BL COMPONENTS ARE BOTH NECESSARY !')
ENDIF
IF (IUBL2 /= IVBL2) THEN
  CALL ABOR1('U AND V BL2 COMPONENTS ARE BOTH NECESSARY !')
ENDIF
IF (IUGW /= IVGW) THEN
  CALL ABOR1('U AND V GW COMPONENTS ARE BOTH NECESSARY !')
ENDIF
IF (IUCV /= IVCV) THEN  
  CALL ABOR1('U AND V CV COMPONENTS ARE BOTH NECESSARY !')
ENDIF

! When to activate CLS :
DO JFLD=1,SIZE(CFP2DF)
  IF (CFP2DF(JFLD)==YFA_XX2T%CLNAME .OR. CFP2DF(JFLD)==YFA_XN2T%CLNAME) THEN  
    ! Tn, Tx, Tcls must be read (to compute increments) if Tn,Tx are recomputed : 
    LXTTCLS=.TRUE.
    LXCLS=.TRUE.
  ELSEIF (CFP2DF(JFLD)==YFA_XX2HU%CLNAME .OR. CFP2DF(JFLD)==YFA_XN2HU%CLNAME) THEN  
    ! HUn,HUx, HUcls must be read (to compute increments) if HUn,HUx are recomputed :
    LXHHCLS=.TRUE.
    LXCLS=.TRUE.
  ELSEIF (CFP2DF(JFLD)==YFA_ASMC%CLNAME) THEN
    ! analysed surface Moisture convergence needs CLS wind & moisture, not for varpack :
    LXCLS=.TRUE.
  ENDIF
ENDDO
! Tcls,RHcls must be read if Cape is computed from PBL fields : 
LXCLS=LXCLS.OR.LFPCAPEX
LXFU=LXFU.OR.LXCLS


!     ------------------------------------------------------------------
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUFPXFU',1,ZHOOK_HANDLE)
END SUBROUTINE SUFPXFU
