! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE AER_EQSAM4CLIM_IFS &
  &( YDEAERSNK,YDEAERATM,YDCOMPO, KIDIA, KFDIA, KLON, KLEV, KLEVTROP,  PRSF1,&
  &  PSO4 , PNO3_1, PNO3_2, PNH4OK, PNH3,PHNO3, PDUST1, PDUST2, PDUST3, &
  &  POM1, POM2, PBC1, PBC2, PSOA1, PSOA2, &
  &  PSS1, PSS2, PSS3, PRHO, PDZ, PRHCL, PT, PDP, PTSPHY, PFRAC_CA1, PFRAC_CA2, &
  &  PLP, PIP, PFLXR, PFLXS,PFLXRC, PFLXSC, PAP, PPRCOV, PTNO3_1, PTNO3_2, PTNH4, &
  &  PTHNO3, PTNH3, PFNO3_1, PFNO3_2, PFNH4, PAERPH, PCLOUDPH, PRAINPH, PAERWAT, PAD)

!*** * AER_EQSAM4CLIM_IFS* - EQSAM4CLIM - IFS INTERFACE

!**   INTERFACE.
!     ----------
!          *AER_EQSAM4CLIM_IFS* IS CALLED FROM *AER_PHY3*.

!     AUTHOR.
!     -------
!        SAMUEL REMY (LMD)  
!        SWEN METZGER (RC)
!
!     SOURCE.
!     -------
!     AER_NO3NH4
!
!     MODIFICATIONS.
!     --------------
!        ORIGINAL : 20160914 (AER_NO3NH4)
!        20170425 SRemy simplified gas partitioning, add RH size dependence for
!                       het uptake, reactions up to tropopause +10
!        20170613 SRemy added the RH80 switch
!        20220316 SMetzger duplicated and adopted to AER_EQSAM4CLIM
!-----------------------------------------------------------------------

USE PARKIND1  , ONLY : JPIM     ,JPRB
USE YOMHOOK   , ONLY : LHOOK,   DR_HOOK, JPHOOK

USE YOMCST    , ONLY : RG, RPI, RMD
USE YOEAERSNK , ONLY : TEAERSNK
USE YOEAERATM , ONLY : TEAERATM
USE YOMCOMPO  , ONLY : TCOMPO

IMPLICIT NONE

!-----------------------------------------------------------------------

!*       0.1   ARGUMENTS
!              ---------

TYPE(TEAERSNK)    ,INTENT(INOUT) :: YDEAERSNK
TYPE(TEAERATM)    ,INTENT(INOUT) :: YDEAERATM
TYPE(TCOMPO)      ,INTENT(INOUT) :: YDCOMPO
INTEGER(KIND=JPIM),INTENT(IN)    :: KLON 
INTEGER(KIND=JPIM),INTENT(IN)    :: KIDIA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KFDIA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEV
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEVTROP(KLON)

REAL(KIND=JPRB)   ,INTENT(IN)    :: PRSF1(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSO4(KLON,KLEV), PDP(KLON, KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDUST1(KLON,KLEV), PDUST2(KLON,KLEV), PDUST3(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSS1(KLON,KLEV), PSS2(KLON,KLEV), PSS3(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: POM1(KLON,KLEV), POM2(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PBC1(KLON,KLEV), PBC2(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSOA1(KLON,KLEV), PSOA2(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PNO3_1(KLON,KLEV),PNO3_2(KLON,KLEV),PNH4OK(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PNH3(KLON,KLEV), PHNO3 (KLON, KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PT(KLON,KLEV),PRHO(KLON,KLEV),PDZ(KLON,KLEV),PRHCL(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTSPHY 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFRAC_CA1(KLON),PFRAC_CA2(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PLP(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PIP(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFLXR(KLON,KLEV+1),PFLXS(KLON,KLEV+1)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFLXRC(KLON,KLEV+1),PFLXSC(KLON,KLEV+1)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PAP(KLON,KLEV),PPRCOV(KLON,KLEV)

REAL(KIND=JPRB)   ,INTENT(OUT)   :: PTNO3_1(KLON,KLEV), PTNO3_2(KLON,KLEV), PTNH4(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PTNH3(KLON,KLEV),PTHNO3(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PFNO3_1(KLON), PFNO3_2(KLON), PFNH4(KLON)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PAERPH(KLON,KLEV),PCLOUDPH(KLON,KLEV), PRAINPH(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PAERWAT(KLON,KLEV), PAD(KLON)


!*       0.5   LOCAL VARIABLES
!              ---------------
REAL(KIND=JPRB)            :: ZTA(KLON,KLEV),ZTN(KLON,KLEV),ZTADISP(KLON,KLEV)
REAL(KIND=JPRB)            :: ZTNTA(KLON,KLEV),ZTS(KLON,KLEV)
REAL(KIND=JPRB)            :: ZAIRDM(KLON,KLEV),ZTDU(KLON,KLEV),ZTSS(KLON,KLEV)
REAL(KIND=JPRB)            :: ZAIRD(KLON,KLEV)
REAL(KIND=JPRB)            :: ZTAM(KLON,KLEV),ZTSM(KLON,KLEV),ZKHNO30(KLON,KLEV)
REAL(KIND=JPRB)            :: ZKHNO3(KLON,KLEV)
REAL(KIND=JPRB)            :: ZNH4PINI(KLON,KLEV),ZDGHNO3(KLON,KLEV)
REAL(KIND=JPRB)            :: ZCAMMR(KLON,KLEV),ZCAVMR(KLON,KLEV),ZCINO3(KLON,KLEV)
REAL(KIND=JPRB)            :: ZNAMMR(KLON,KLEV),ZNAVMR(KLON,KLEV)
REAL(KIND=JPRB)            :: ZNH3UP(KLON,KLEV)
REAL(KIND=JPRB)            :: ZHNO3UP(KLON,KLEV)
REAL(KIND=JPRB)            :: ZTOTSS(KLON,KLEV),ZTOTDUST(KLON,KLEV)
REAL(KIND=JPRB)            :: ZTOTWATSS(KLON,KLEV), ZTOTWATOM(KLON,KLEV), ZTOTWATSOA(KLON,KLEV)
REAL(KIND=JPRB)            :: ZTOTWATDD(KLON,KLEV)
REAL(KIND=JPRB)            :: ZLP,ZRP, ZX1, ZX2, ZNO3_2NA, ZNO3_2CA, ZNO3_2OTH
INTEGER(KIND=JPIM)         :: JL, JK, IRH(KLON,KLEV), IIRH, JTAB
REAL(KIND=JPRB), PARAMETER :: ZMWNH3  = 17.E-3_JPRB !Kg/mol
REAL(KIND=JPRB), PARAMETER :: ZMWHNO3 = 63.E-3_JPRB
REAL(KIND=JPRB), PARAMETER :: ZMWNH4  = 18.E-3_JPRB
REAL(KIND=JPRB), PARAMETER :: ZMWNO3  = 62.E-3_JPRB
REAL(KIND=JPRB), PARAMETER :: ZMWDUST  = 100.E-3_JPRB
REAL(KIND=JPRB), PARAMETER :: ZMWCANO3  = 164.E-3_JPRB
REAL(KIND=JPRB), PARAMETER :: ZMWNANO3  = 85.E-3_JPRB
REAL(KIND=JPRB), PARAMETER :: ZMWMNO3  = 148.E-3_JPRB
REAL(KIND=JPRB), PARAMETER :: ZMWCACO3  = 164.E-3_JPRB
REAL(KIND=JPRB), PARAMETER :: ZMWCA  = 40.E-3_JPRB
REAL(KIND=JPRB), PARAMETER :: ZMWNACL  = 58.44E-3_JPRB
REAL(KIND=JPRB), PARAMETER :: ZMWNA  = 22.9E-3_JPRB
REAL(KIND=JPRB), PARAMETER :: ZMWK  = 39.1E-3_JPRB
REAL(KIND=JPRB), PARAMETER :: ZMWOM  = 16.8E-3_JPRB
REAL(KIND=JPRB), PARAMETER :: ZMWBC  = 12.E-3_JPRB
REAL(KIND=JPRB), PARAMETER :: ZMWMG  = 24.3E-3_JPRB
REAL(KIND=JPRB), PARAMETER :: ZMWCL  = 35.45E-3_JPRB
REAL(KIND=JPRB), PARAMETER :: ZMWSO4  = 96.E-3_JPRB
REAL(KIND=JPRB), PARAMETER :: ZRHO_OM=1800._JPRB  ! kg/m^3
REAL(KIND=JPRB), PARAMETER :: ZRHO_DD=2600._JPRB  ! kg/m^3
REAL(KIND=JPRB), PARAMETER :: ZRHO_SOA=1800._JPRB  ! kg/m^3
REAL(KIND=JPRB), PARAMETER :: ZRHO_H2O=1000._JPRB  ! kg/m^3 (water)
REAL(KIND=JPRB), DIMENSION(12), PARAMETER    :: ZRH_GROWTH_OM= &
         & (/1.00_JPRB,1.00_JPRB,1.00_JPRB,1.00_JPRB,1._JPRB,1.050_JPRB,&
         & 1.100_JPRB,1.150_JPRB,1.200_JPRB,1.250_JPRB,1.300_JPRB,1.400_JPRB/)
REAL(KIND=JPRB), DIMENSION(12), PARAMETER    :: ZRH_GROWTH_SOA= &
         & (/1.00_JPRB,1.00_JPRB,1.00_JPRB,1.00_JPRB,1.00_JPRB,1.2_JPRB,&
         & 1.3_JPRB,1.4_JPRB,1.5_JPRB,1.6_JPRB,1.7_JPRB,1.8_JPRB/)
REAL(KIND=JPRB), DIMENSION(12), PARAMETER    :: ZRH_GROWTH_DD= &
         & (/1.00_JPRB,1.008_JPRB,1.016_JPRB,1.024_JPRB,1.032_JPRB,1.038_JPRB,&
         & 1.046_JPRB,1.054_JPRB,1.062_JPRB,1.066_JPRB,1.07_JPRB,1.074_JPRB/)




!
! EQSAM4Clim
REAL(KIND=JPRB)            :: ZXYPA(5),ZXYPS(5),ZXYMA(4),ZXYMS(4),ZXYG(4),ZXYG2(4)
REAL(KIND=JPRB)            :: ZXSPM,ZXAPM,ZXPMS,ZXPMT,ZXRHO,ZXVOL,ZXPH,ZXHp,ZXGF
REAL(KIND=JPRB)            :: ZXTT,ZXAW,ZXWH2O,ZXAD,ZXDD
REAL(KIND=JPRB)            :: ZRHOD, ZDRYD, ZWETD, ZRHOW, ZRHOS, ZSTANDD, ZVFRAC
REAL(KIND=JPRB)            :: ZRHODOM, ZDRYDOM, ZWETDOM, ZRHOWOM,ZFACTSSWAT,ZFACTOMWAT
REAL(KIND=JPRB)            :: ZRHODDD, ZDRYDDD, ZWETDDD, ZRHOWDD,ZFACTDDWAT
REAL(KIND=JPRB)            :: ZRHODSOA, ZDRYDSOA, ZWETDSOA, ZRHOWSOA,ZFACTSOAWAT
LOGICAL                    :: LEQSKIP


REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "aer_eqsam4clim.intfb.h"

!-----------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('AER_EQSAM4CLIM_IFS',0,ZHOOK_HANDLE)
ASSOCIATE( RMMD_DD=>YDEAERSNK%RMMD_DD, RRHO_DD=>YDEAERSNK%RRHO_DD, &
         & RMMD_SS=>YDEAERSNK%RMMD_SS, RRHO_SS=>YDEAERSNK%RRHO_SS, &
         & RRHTAB=>YDEAERSNK%RRHTAB, &
         & LSEASALT_RH80=> YDEAERATM%LSEASALT_RH80, &
         & RSS_DRY_MASSFAC=>YDEAERATM%RSS_DRY_MASSFAC,&
         & RSS_DRY_DIAFAC=>YDEAERATM%RSS_DRY_DIAFAC,&
         & RSSGROWTH_RHTAB=>YDEAERSNK%RSSGROWTH_RHTAB, &
         & RSSDENS_RHTAB=>YDEAERSNK%RSSDENS_RHTAB)

IRH(:,:)=1
  
ZRHOD=RSSDENS_RHTAB(1)
ZDRYD=RSSGROWTH_RHTAB(1)
ZRHOS=RSSDENS_RHTAB(9)
ZSTANDD=RSSGROWTH_RHTAB(9)

ZDRYDOM=ZRH_GROWTH_OM(1)
ZDRYDSOA=ZRH_GROWTH_SOA(1)
ZDRYDDD=ZRH_GROWTH_DD(1)
DO JL=KIDIA,KFDIA
  DO JK=1,KLEV
   PTNO3_1(JL,JK)=0.0_JPRB
   PTNO3_2(JL,JK)=0.0_JPRB
   PTNH4(JL,JK)=0.0_JPRB
   ZTOTSS(JL,JK)=PSS1(JL,JK)+PSS2(JL,JK)+PSS3(JL,JK)
   ZTOTDUST(JL,JK)=PDUST1(JL,JK) + PDUST2(JL,JK)
! Compute sea-salt aerosol water content 
   DO JTAB=1,12
     IF (PRHCL(JL,JK)*100._JPRB > RRHTAB(JTAB)) THEN
       IRH(JL,JK)=JTAB
     ENDIF
   ENDDO
   ZRHOW=RSSDENS_RHTAB(IRH(JL,JK))
   ZWETD=RSSGROWTH_RHTAB(IRH(JL,JK))
   ZFACTSSWAT=((ZWETD**3._JPRB * ZRHOW) - (ZDRYD**3._JPRB * ZRHOD))/(ZSTANDD*3._JPRB * ZRHOS)

   ZVFRAC = 1.0_JPRB / ZRH_GROWTH_OM(IRH(JL,JK))**3
   ZRHOWOM = ZRHO_H2O*(1.0_JPRB-ZVFRAC) + ZVFRAC*ZRHO_OM
   ZWETDOM=ZRH_GROWTH_OM(IRH(JL,JK))
   ZFACTOMWAT=((ZWETDOM**3._JPRB * ZRHOWOM) - (ZDRYDOM**3._JPRB * ZRHO_OM))/(ZDRYDOM**3._JPRB * ZRHO_OM)
 
   ZVFRAC = 1.0_JPRB / ZRH_GROWTH_DD(IRH(JL,JK))**3
   ZRHOWDD = ZRHO_H2O*(1.0_JPRB-ZVFRAC) + ZVFRAC*ZRHO_DD
   ZWETDDD=ZRH_GROWTH_DD(IRH(JL,JK))
   ZFACTSOAWAT=((ZWETDDD**3._JPRB * ZRHOWDD) - (ZDRYDDD**3._JPRB * ZRHO_DD))/(ZDRYDDD**3._JPRB * ZRHO_DD)

   ZVFRAC = 1.0_JPRB / ZRH_GROWTH_SOA(IRH(JL,JK))**3
   ZRHOWSOA = ZRHO_H2O*(1.0_JPRB-ZVFRAC) + ZVFRAC*ZRHO_SOA
   ZWETDSOA=ZRH_GROWTH_SOA(IRH(JL,JK))
   ZFACTDDWAT=((ZWETDSOA**3._JPRB * ZRHOWSOA) - (ZDRYDSOA**3._JPRB * ZRHO_SOA))/(ZDRYDSOA**3._JPRB * ZRHO_SOA)

   ZTOTWATSS(JL,JK)=0._JPRB
   ZTOTWATDD(JL,JK)=(PDUST1(JL,JK) + PDUST2(JL,JK) + PDUST3(JL,JK))*ZFACTDDWAT*PRHO(JL,JK)
   ZTOTWATOM(JL,JK)=POM1(JL,JK)*ZFACTOMWAT*PRHO(JL,JK)
   ZTOTWATSOA(JL,JK)=MAX(0._JPRB,(PSOA1(JL,JK)+PSOA2(JL,JK))*ZFACTSOAWAT*PRHO(JL,JK))
   ENDDO
ENDDO

PTHNO3(:,:)=0._JPRB
PTNH3(:,:)=0._JPRB

DO JL=KIDIA,KFDIA
  DO JK=KLEVTROP(JL)+10,KLEV
    !ZAIRDM(JL,JK) = (7.24291E16_JPRB*PRSF1(JL,JK)/PT(JL,JK)) * RMD /6.02E23_JPRB * 1E6_JPRB
    LEQSKIP=.FALSE.
    ZXWH2O=ZTOTWATSS(JL,JK)+ZTOTWATOM(JL,JK)+ZTOTWATSOA(JL,JK)+ZTOTWATDD(JL,JK)
    ZXPMT=0.0_JPRB
    ZXPMS=0.0_JPRB
    ZXSPM=0.0_JPRB
    ZXAPM=0.0_JPRB
    ZXHP=0.0_JPRB
    ZXRHO=0.0_JPRB
    ZXVOL=0.0_JPRB
   ! gases (mol/m^3 air)
    ZXYG(1)= 0._JPRB
    ZXYG(2)= 0._JPRB                    ! HCL
    ZXYG(3)= 0._JPRB
    ZXYG(4)= 0._JPRB                    ! H2SO4
   ! Anions (mol/m^3 air)
    ZXYMA(1)=  PSO4(JL,JK)*PRHO(JL,JK)/ZMWSO4
    ZXYMA(2)=  0._JPRB                    ! HSO4-
    ZXYMA(3)=  (PNO3_1(JL,JK)+PNO3_2(JL,JK))*PRHO(JL,JK)/ZMWNO3 + PHNO3(JL,JK)*PRHO(JL,JK)/ZMWHNO3
    ZXYMA(4)=  0.128_JPRB*ZTOTSS(JL,JK)*PRHO(JL,JK)/ZMWCL
!      ZXYMA(4)=0._JPRB
      ! cations (mol/m^3 air)
    ZXYPA(1)= PNH4OK(JL,JK)*PRHO(JL,JK)/ZMWNH4+PNH3(JL,JK)*PRHO(JL,JK)/ZMWNH3
    ZXYPA(2)= 0.07_JPRB*ZTOTSS(JL,JK)*PRHO(JL,JK)/ZMWNA + &
           & 0.012_JPRB*ZTOTDUST(JL,JK)*PRHO(JL,JK)/ZMWDUST                     ! Na+
    ZXYPA(3)= 0.015_JPRB*ZTOTDUST(JL,JK)*PRHO(JL,JK)/ZMWDUST + &
           & 0.03_JPRB*(POM1(JL,JK) + POM2(JL,JK))*PRHO(JL,JK)/ZMWOM + & ! K
           & 0.03_JPRB*(PBC1(JL,JK) + PBC2(JL,JK))*PRHO(JL,JK)/ZMWBC ! K
    ZXYPA(4)=  ((PDUST1(JL,JK)+PDUST2(JL,JK))*PFRAC_CA1(JL) + &
            & PDUST3(JL,JK)*PFRAC_CA2(JL))*PRHO(JL,JK)/ZMWDUST + &
            & PNO3_2(JL,JK)*PRHO(JL,JK)/ZMWCACO3+ &
            & 0.012*ZTOTSS(JL,JK)*PRHO(JL,JK)/ZMWCA
    ZXYPA(5)=0.01_JPRB*ZTOTDUST(JL,JK)*PRHO(JL,JK)/ZMWDUST  + &         ! Ng++
          & 0.01_JPRB * ZTOTSS(JL,JK)*PRHO(JL,JK)/ZMWNACL

    ZNO3_2CA=0._JPRB
    ZNO3_2OTH=0._JPRB
    ZNO3_2NA=0._JPRB
    ZXAD=0._JPRB    ! aerosol domain
    ZXDD=1.e-6_JPRB ! aerosol diameter

!     ZLP= cloud water content   [kg/m3(air)]
    ZLP=0._JPRB
    IF (PAP(JL,JK) > 0.05_JPRB) THEN
      ZLP=PLP(JL,JK)*PRHO(JL,JK)/PAP(JL,JK)
    ENDIF
!    ZRP = rain water content   [kg/m3(air)]
    ZRP=0._JPRB
    IF (PPRCOV(JL,JK) > 0.01_JPRB) THEN
!  PLFXR = kg/m2s , *PTSPHY = kg/m2
!  , /DZ (in m) = kg/m3
      ZRP=(PFLXR(JL,JK)+PFLXS(JL,JK)+PFLXRC(JL,JK)+PFLXSC(JL,JK))/(PPRCOV(JL,JK)*PDZ(JL,JK))
    ENDIF
! Convective precip
!    ZRP=PRP(JL,JK)*PRHO(JL,JK)

!SUBROUTINE AER_EQSAM4CLIM(xPP,         xTT,      xRH,          xAD, PLP, PRP,
    CALL  AER_EQSAM4CLIM(PRSF1(JL,JK),PT(JL,JK),PRHCL(JL,JK),ZXAD,ZLP, ZRP, &
    &                   ZXSPM,ZXAPM,ZXPMS,ZXPMT,ZXRHO,ZXVOL,ZXPH,ZXHP,&
!                          xsPM, xaPM, xPMs,xPMT,  xRHO, xVOL, xPH, xHp,&
    &                   ZXGF,ZXWH2O,ZXYPA,ZXYPS,ZXYMA,ZXYMS,ZXYG,ZXDD, &
!                        xGF, xWH2O, xYPa, xYPs, xYMa, xYMs, xYG,  Dd,&
    &                   LEQSKIP,ZNO3_2NA,ZNO3_2CA,ZNO3_2OTH,&
!                       lEQskip,xNO3_2NA,xNO3_2CA,xNO3_2OTH,& 
    &                   PAERPH(JL,JK),PCLOUDPH(JL,JK), PRAINPH(JL,JK), PAERWAT(JL,JK))
!                       xAERPH,       xCLOUDPH,        xRAINPH)

! ToDo: assign lumped ions and gases from EQSAM4clim output 
    IF (.NOT. LEQSKIP) THEN
      PTNO3_2(JL,JK)=((ZNO3_2NA+ZNO3_2CA+ZNO3_2OTH)*ZMWNO3/PRHO(JL,JK) - PNO3_2 (JL,JK))/PTSPHY
      PTHNO3(JL,JK)=(ZXYG(1)*ZMWHNO3/PRHO(JL,JK)-PHNO3(JL,JK))/PTSPHY
      PTNO3_1(JL,JK)=-1._JPRB*PTHNO3(JL,JK)*ZMWNO3/ZMWHNO3 - PTNO3_2(JL,JK)
      PTNH3(JL,JK)=(ZXYG(3)*ZMWNH3/PRHO(JL,JK) - PNH3(JL,JK))/PTSPHY
      PTNH4(JL,JK)=-1._JPRB*PTNH3(JL,JK)*ZMWNH3/ZMWNH4
      IF (JK==KLEV) THEN
        PAD(JL)=ZXAD
      ENDIF
    ENDIF
  ENDDO
ENDDO

DO JL=KIDIA,KFDIA
  PFNO3_1(JL)=0.0_JPRB
  PFNO3_2(JL)=0.0_JPRB
  PFNH4(JL)=0.0_JPRB
ENDDO

DO JK=1,KLEV
   DO JL=KIDIA,KFDIA
      PFNO3_1(JL) = PFNO3_1(JL) + PTNO3_1(JL,JK)*(PDP(JL,JK))/RG
      PFNO3_2(JL) = PFNO3_2(JL) + PTNO3_2(JL,JK)*(PDP(JL,JK))/RG
      PFNH4(JL) = PFNH4(JL) + PTNH4(JL,JK)*(PDP(JL,JK))/RG
   ENDDO
ENDDO

!-----------------------------------------------------------------------
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('AER_EQSAM4CLIM_IFS',1,ZHOOK_HANDLE)
END SUBROUTINE AER_EQSAM4CLIM_IFS
