! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE CALL_SL_DRV(YDGEO,YDGMV,YDMODEL,PGFL,YDSL,KVSEPC,KVSEPL,PB1,PB2,PWRL9, PGMVT1,PGMVT1S,&
  & PGFLT1,PGFLPC,PUP9,PVP9,PTP9,PGFLP9,PSPPTCLEARP9,PEXTRADYN)

!****-------------------------------------------------------------------
!**** *CALL_SL_DRV* - Semi-lagrangian driver
!****-------------------------------------------------------------------
!     Purpose.   call_sl driver using memory on heap for large arrays
!     --------   allocates memory (if possible) only once

!**   Interface.
!     ----------
!        *CALL* *CALL_SL_DRV (..)

!     Method.
!     -------

!     Externals.   See includes below.
!     ----------

!     Reference.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     Author.
!     -------
!        H Petithomme (Dec 2020): merge stack, heap and heap2 versions

! Modifications
! -------------
!        R. El Khatib 27-Oct-2021 optimize memory allocations for NH.
! End Modifications
!-------------------------------------------------------------------------------

USE PARKIND1,    ONLY: JPIM,JPRB
USE YOMHOOK,     ONLY: LHOOK,DR_HOOK, JPHOOK
USE YOMCT0,      ONLY: NOPT_MEMORY, L_OOPS
USE TYPE_MODEL,  ONLY: MODEL
USE GEOMETRY_MOD,ONLY: GEOMETRY
USE YOMGMV,      ONLY: TGMV
USE EINT_MOD,    ONLY: SL_STRUCT
USE YOMCT3,      ONLY: NSTEP

IMPLICIT NONE

TYPE(GEOMETRY),    INTENT(IN)    :: YDGEO
TYPE(TGMV),        INTENT(INOUT) :: YDGMV
TYPE(MODEL),       INTENT(INOUT) :: YDMODEL
REAL(KIND=JPRB),   INTENT(INOUT) :: PGFL(YDGEO%YRDIM%NPROMA,YDGEO%YRDIMV%NFLEVG,YDMODEL%YRML_GCONF%YGFL%NDIM,YDGEO%YRDIM%NGPBLKS)
TYPE(SL_STRUCT),   INTENT(INOUT) :: YDSL
INTEGER(KIND=JPIM),INTENT(INOUT) :: KVSEPC(YDGEO%YRDIM%NGPBLKS)
INTEGER(KIND=JPIM),INTENT(INOUT) :: KVSEPL(YDGEO%YRDIM%NGPBLKS)
REAL(KIND=JPRB),   INTENT(INOUT) :: PB1(YDSL%NASLB1,YDMODEL%YRML_DYN%YRPTRSLB1%NFLDSLB1)
REAL(KIND=JPRB),   INTENT(INOUT) :: PB2(YDGEO%YRDIM%NPROMA,YDMODEL%YRML_DYN%YRPTRSLB2%NFLDSLB2,YDGEO%YRDIM%NGPBLKS)
REAL(KIND=JPRB),   INTENT(IN)    :: PWRL9(YDGEO%YRDIM%NPROMA,YDGEO%YRDIMV%NFLEVG,YDGEO%YRDIM%NGPBLKS)
REAL(KIND=JPRB),   INTENT(INOUT) :: PGMVT1(YDGEO%YRDIM%NPROMA,YDGEO%YRDIMV%NFLEVG,YDGMV%YT1%NDIM,YDGEO%YRDIM%NGPBLKS)
REAL(KIND=JPRB),   INTENT(INOUT) :: PGMVT1S(YDGEO%YRDIM%NPROMA,YDGMV%YT1%NDIMS,YDGEO%YRDIM%NGPBLKS)
REAL(KIND=JPRB),   INTENT(INOUT) :: PGFLT1(YDGEO%YRDIM%NPROMA,YDGEO%YRDIMV%NFLEVG,YDMODEL%YRML_GCONF%YGFL%NDIM1,YDGEO%YRDIM%NGPBLKS)
REAL(KIND=JPRB),   INTENT(INOUT) :: PGFLPC(YDGEO%YRDIM%NPROMA,YDGEO%YRDIMV%NFLEVG,YDMODEL%YRML_GCONF%YGFL%NDIMPC,YDGEO%YRDIM%NGPBLKS)
REAL(KIND=JPRB),   INTENT(OUT)   :: PUP9(YDGEO%YRDIM%NPROMA,YDGEO%YRDIMV%NFLEVG,YDGEO%YRDIM%NGPBLKS)
REAL(KIND=JPRB),   INTENT(OUT)   :: PVP9(YDGEO%YRDIM%NPROMA,YDGEO%YRDIMV%NFLEVG,YDGEO%YRDIM%NGPBLKS)
REAL(KIND=JPRB),   INTENT(OUT)   :: PTP9(YDGEO%YRDIM%NPROMA,YDGEO%YRDIMV%NFLEVG,YDGEO%YRDIM%NGPBLKS)
REAL(KIND=JPRB),   INTENT(OUT)   :: PGFLP9(YDGEO%YRDIM%NPROMA,YDGEO%YRDIMV%NFLEVG,YDMODEL%YRML_GCONF%YGFL%NUMFLDS,YDGEO%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PSPPTCLEARP9(YDGEO%YRDIM%NPROMA,YDGEO%YRDIMV%NFLEVG,YDGEO%YRDIM%NGPBLKS)
REAL(KIND=JPRB),   INTENT(INOUT) :: PEXTRADYN(YDGEO%YRDIM%NPROMA,YDGEO%YRDIMV%NFLEVG,YDMODEL%YRML_PHY_G%YRDPHY%NVEXTRDYN,YDGEO%YRDIM%NGPBLKS) ! or just intent(out) ?

INTEGER(KIND=JPIM) :: IL0(YDGEO%YRDIM%NPROMA,YDGEO%YRDIMV%NFLEVG,0:3,YDGEO%YRDIM%NGPBLKS)
REAL(KIND=JPRB) :: ZLSCAW(YDGEO%YRDIM%NPROMA,YDGEO%YRDIMV%NFLEVG,YDMODEL%YRML_DYN%YYTLSCAW%NDIM,YDGEO%YRDIM%NGPBLKS)

! note: pointers are needed here because of arguments IL0 and ZSCAW, commonly passed to
! CALL_SL and TRMFIXERS
INTEGER(KIND=JPIM),SAVE :: NPROMA=0,NFLEVG=0,NGPBLKS=0,NRSCAW=0,NSCO=0,NCCO=0
INTEGER(KIND=JPIM),ALLOCATABLE,TARGET,SAVE :: IILH0(:,:,:,:)
INTEGER(KIND=JPIM),CONTIGUOUS,POINTER :: ILH0(:,:,:,:)
REAL(KIND=JPRB),ALLOCATABLE,TARGET,SAVE :: ZZRSCAW(:,:,:,:)
REAL(KIND=JPRB),ALLOCATABLE,TARGET,SAVE :: ZZSCO(:,:,:,:),ZZCCO(:,:,:,:)
REAL(KIND=JPRB),CONTIGUOUS,POINTER :: ZRSCAW(:,:,:,:),ZSCO(:,:,:,:),ZCCO(:,:,:,:)

INTEGER(KIND=JPIM),SAVE :: NPROMNH=0, NLSCAWH=0, NRSCAWH=0
REAL(KIND=JPRB),ALLOCATABLE,TARGET,SAVE :: ZZRSCAWH(:,:,:,:), ZZLSCAWH(:,:,:,:)
REAL(KIND=JPRB),CONTIGUOUS,POINTER :: ZRSCAWH(:,:,:,:), ZLSCAWH(:,:,:,:)

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "call_sl.intfb.h"
#include "trmfixers.intfb.h"
#include "gmassdiag.intfb.h"

IF (LHOOK) CALL DR_HOOK('CALL_SL_DRV',0,ZHOOK_HANDLE)

ASSOCIATE(YGFL=>YDMODEL%YRML_GCONF%YGFL)

ASSOCIATE(YDDIM=>YDGEO%YRDIM,YDDIMV=>YDGEO%YRDIMV,YDDYN=>YDMODEL%YRML_DYN,&
 & LTRCMFIX=>YGFL%LTRCMFIX,LADVNEGFIX=>YGFL%LADVNEGFIX,NMFDIAGLEV=>YGFL%NMFDIAGLEV)

IF (NOPT_MEMORY == 1) THEN
  CALL CALL_SLSTACK(YDGEO,YDGMV,YDMODEL,PGFL,YDSL,KVSEPC,KVSEPL,IL0,ZLSCAW,PB1,PB2,&
    & PWRL9, PGMVT1,PGMVT1S,PGFLT1,PGFLPC,PUP9,PVP9,PTP9,PGFLP9)
ELSE
  IF (NOPT_MEMORY == 0) THEN
    ALLOCATE(ILH0(YDDIM%NPROMA,YDDIMV%NFLEVG,0:3,YDDIM%NGPBLKS))
    ALLOCATE(ZRSCAW(YDDIM%NPROMA,YDDIMV%NFLEVG,YDDYN%YYTRSCAW%NDIM,YDDIM%NGPBLKS))
    ALLOCATE(ZSCO(YDDIM%NPROMA,YDDIMV%NFLEVG,YDDYN%YYTSCO%NDIM,YDDIM%NGPBLKS))
    ALLOCATE(ZCCO(YDDIM%NPROMA,YDDIMV%NFLEVG,YDDYN%YYTCCO%NDIM,YDDIM%NGPBLKS))
    ALLOCATE(ZLSCAWH(YDDIM%NPROMNH,YDDIMV%NFLEVG,YDDYN%YYTLSCAWH%NDIM,YDDIM%NGPBLKS))
    ALLOCATE(ZRSCAWH(YDDIM%NPROMNH,YDDIMV%NFLEVG,YDDYN%YYTRSCAWH%NDIM,YDDIM%NGPBLKS))

  ELSEIF (NOPT_MEMORY == 2) THEN
    ! deallocate if needed
    IF (ALLOCATED(IILH0).AND.(NPROMA /= YDDIM%NPROMA.OR.NFLEVG /= YDDIMV%NFLEVG.OR.&
     & NGPBLKS /= YDDIM%NGPBLKS.OR.NRSCAW /= YDDYN%YYTRSCAW%NDIM.OR.&
     & NSCO /= YDDYN%YYTSCO%NDIM.OR.NCCO /= YDDYN%YYTCCO%NDIM)) THEN
      DEALLOCATE(ZZCCO)
      DEALLOCATE(ZZSCO)
      DEALLOCATE(ZZRSCAW)
      DEALLOCATE(IILH0)
    ENDIF
    IF (ALLOCATED(ZZLSCAWH).AND.(NPROMNH /= YDDIM%NPROMNH.OR.NFLEVG /= YDDIMV%NFLEVG.OR.&
     & NGPBLKS /= YDDIM%NGPBLKS.OR.NLSCAWH /= YDDYN%YYTLSCAWH%NDIM.OR.NRSCAWH /= YDDYN%YYTRSCAWH%NDIM)) THEN
      DEALLOCATE(ZZLSCAWH)
      DEALLOCATE(ZZRSCAWH)
    ENDIF

    ! allocate if needed
    IF (.NOT.ALLOCATED(IILH0)) THEN
      NPROMA = YDDIM%NPROMA
      NFLEVG = YDDIMV%NFLEVG
      NGPBLKS = YDDIM%NGPBLKS
      NRSCAW = YDDYN%YYTRSCAW%NDIM
      NSCO = YDDYN%YYTSCO%NDIM
      NCCO = YDDYN%YYTCCO%NDIM
      ALLOCATE(IILH0(YDDIM%NPROMA,YDDIMV%NFLEVG,0:3,YDDIM%NGPBLKS))
      ALLOCATE(ZZRSCAW(YDDIM%NPROMA,YDDIMV%NFLEVG,YDDYN%YYTRSCAW%NDIM,YDDIM%NGPBLKS))
      ALLOCATE(ZZSCO(YDDIM%NPROMA,YDDIMV%NFLEVG,YDDYN%YYTSCO%NDIM,YDDIM%NGPBLKS))
      ALLOCATE(ZZCCO(YDDIM%NPROMA,YDDIMV%NFLEVG,YDDYN%YYTCCO%NDIM,YDDIM%NGPBLKS))
    ENDIF
    ILH0 => IILH0(:,:,:,:)
    ZRSCAW => ZZRSCAW(:,:,:,:)
    ZSCO => ZZSCO(:,:,:,:)
    ZCCO => ZZCCO(:,:,:,:)

    IF (.NOT.ALLOCATED(ZZLSCAWH)) THEN
      NPROMNH = YDDIM%NPROMNH
      NLSCAWH = YDDYN%YYTLSCAWH%NDIM
      NRSCAWH = YDDYN%YYTRSCAWH%NDIM
      ALLOCATE(ZZLSCAWH(YDDIM%NPROMNH,YDDIMV%NFLEVG,YDDYN%YYTLSCAWH%NDIM,YDDIM%NGPBLKS))
      ALLOCATE(ZZRSCAWH(YDDIM%NPROMNH,YDDIMV%NFLEVG,YDDYN%YYTRSCAWH%NDIM,YDDIM%NGPBLKS))
    ENDIF
    ZLSCAWH => ZZLSCAWH(:,:,:,:)
    ZRSCAWH => ZZRSCAWH(:,:,:,:)
  ENDIF

  CALL CALL_SL(YDGEO,YDGMV,YDMODEL,PGFL,YDSL,KVSEPC,KVSEPL,PB1,PB2,PWRL9,PGMVT1,PGMVT1S,PGFLT1,&
    & PGFLPC,IL0,ZLSCAW,PUP9,PVP9,PTP9,PGFLP9,PSPPTCLEARP9,ILH0,ZRSCAW,ZSCO,ZCCO,ZLSCAWH,ZRSCAWH)

  IF (NOPT_MEMORY == 0) THEN
    DEALLOCATE(ZCCO)
    DEALLOCATE(ZSCO)
    DEALLOCATE(ZRSCAW)
    DEALLOCATE(ILH0)
    DEALLOCATE(ZLSCAWH)
    DEALLOCATE(ZRSCAWH)
  ENDIF
  IF (L_OOPS .AND. (NOPT_MEMORY==2) .AND. (NSTEP==(YDMODEL%YRML_GCONF%YRRIP%NSTOP-1))) THEN
    DEALLOCATE(ZZCCO)
    DEALLOCATE(ZZSCO)
    DEALLOCATE(ZZRSCAW)
    DEALLOCATE(IILH0)
    DEALLOCATE(ZZLSCAWH)
    DEALLOCATE(ZZRSCAWH)
  ENDIF
ENDIF

!*  TRACER MASS FIXER - MADE OPTIONAL THROUGH LTRCMFIX
!   A FIX FOR A LOSS OR GAIN OF MASS DUE TO THE ADVECTION SCHEME ONLY

IF ( (LTRCMFIX.OR.LADVNEGFIX).AND. &
  &  ((YDDYN%YRDYNA%LPC_FULL.AND.YDDYN%YRDYN%NCURRENT_ITER==YDDYN%YRDYN%NSITER).OR. &
  &   (.NOT.YDDYN%YRDYNA%LPC_FULL)) ) THEN
  IF (NMFDIAGLEV>1) THEN
    CALL GMASSDIAG(YDGEO,YDGMV,YDMODEL%YRML_CHEM,YGFL,YDDYN%YRDYN,YDGMV%GMV,YDGMV%GMVS,PGMVT1S,&
      & PGFL,PGFLT1,KOPT=1)
    CALL GMASSDIAG(YDGEO,YDGMV,YDMODEL%YRML_CHEM,YGFL,YDDYN%YRDYN,YDGMV%GMV,YDGMV%GMVS,PGMVT1S,&
      & PGFL,PGFLT1,KOPT=1,LDTROP=.TRUE.)
  ENDIF
  CALL GSTATS(7,0)
  CALL TRMFIXERS(YDGEO,YDGMV,YDMODEL%YRML_PHY_G%YRDPHY,YDMODEL%YRML_GCONF,YDDYN,&
   & YDMODEL%YRML_DYN%YRDYNA%LSLAG,IL0,ZLSCAW,PB1,YDSL,YDGMV%GMVS,PGMVT1S,PGFL,&
   & PGFLT1,PEXTRADYN)
  CALL GSTATS(7,1)
  IF (NMFDIAGLEV>2) THEN ! Full range of mass diags including troposhere after fixers applied
    CALL GMASSDIAG(YDGEO,YDGMV,YDMODEL%YRML_CHEM,YGFL,YDDYN%YRDYN,&
      & YDGMV%GMV,YDGMV%GMVS,PGMVT1S,PGFL,PGFLT1)
    CALL GMASSDIAG(YDGEO,YDGMV,YDMODEL%YRML_CHEM,YGFL,YDDYN%YRDYN,&
      & YDGMV%GMV,YDGMV%GMVS,PGMVT1S,PGFL,PGFLT1,LDTROP=.TRUE.)
  ENDIF
ENDIF
! The following call allow basic diags to be printed regardless if mass fixer is active or not.
IF (NMFDIAGLEV==1 .OR. NMFDIAGLEV==2) THEN
  CALL GMASSDIAG(YDGEO,YDGMV,YDMODEL%YRML_CHEM,YGFL,YDDYN%YRDYN,YDGMV%GMV,YDGMV%GMVS,PGMVT1S,&
    & PGFL,PGFLT1,KOPT=0)
ENDIF
END ASSOCIATE
END ASSOCIATE

IF (LHOOK) CALL DR_HOOK('CALL_SL_DRV',1,ZHOOK_HANDLE)

CONTAINS

SUBROUTINE CALL_SLSTACK(YDGEO,YDGMV,YDMODEL,PGFL,YDSL,KVSEPC,KVSEPL,KL0,PLSCAW,PB1,PB2,&
  & PWRL9, PGMVT1,PGMVT1S,PGFLT1,PGFLPC,PUP9,PVP9,PTP9,PGFLP9)
  TYPE(GEOMETRY),INTENT(IN)  :: YDGEO
  TYPE(TGMV),INTENT(INOUT) :: YDGMV
  TYPE(MODEL),INTENT(INOUT) :: YDMODEL
  REAL(KIND=JPRB),INTENT(INOUT) :: PGFL(YDGEO%YRDIM%NPROMA,YDGEO%YRDIMV%NFLEVG,&
    & YDMODEL%YRML_GCONF%YGFL%NDIM,YDGEO%YRDIM%NGPBLKS)
  TYPE(SL_STRUCT),INTENT(INOUT) :: YDSL
  INTEGER(KIND=JPIM),INTENT(INOUT) :: KVSEPC(YDGEO%YRDIM%NGPBLKS)
  INTEGER(KIND=JPIM),INTENT(INOUT) :: KVSEPL(YDGEO%YRDIM%NGPBLKS)
  INTEGER(KIND=JPIM),INTENT(OUT) :: KL0(YDGEO%YRDIM%NPROMA,YDGEO%YRDIMV%NFLEVG,0:3,YDGEO%YRDIM%NGPBLKS)
  REAL(KIND=JPRB),INTENT(OUT) :: PLSCAW(YDGEO%YRDIM%NPROMA,YDGEO%YRDIMV%NFLEVG,&
    & YDMODEL%YRML_DYN%YYTLSCAW%NDIM,YDGEO%YRDIM%NGPBLKS)
  REAL(KIND=JPRB),INTENT(INOUT) :: PB1(YDSL%NASLB1,YDMODEL%YRML_DYN%YRPTRSLB1%NFLDSLB1)
  REAL(KIND=JPRB),INTENT(INOUT) :: PB2(YDGEO%YRDIM%NPROMA,YDMODEL%YRML_DYN%YRPTRSLB2%NFLDSLB2,&
    & YDGEO%YRDIM%NGPBLKS)
  REAL(KIND=JPRB),INTENT(IN)    :: PWRL9(YDGEO%YRDIM%NPROMA,YDGEO%YRDIMV%NFLEVG, &
    & YDGEO%YRDIM%NGPBLKS)
  REAL(KIND=JPRB),INTENT(INOUT) :: PGMVT1(YDGEO%YRDIM%NPROMA,YDGEO%YRDIMV%NFLEVG,&
    & YDGMV%YT1%NDIM,YDGEO%YRDIM%NGPBLKS)
  REAL(KIND=JPRB),INTENT(INOUT) :: PGMVT1S(YDGEO%YRDIM%NPROMA,YDGMV%YT1%NDIMS,YDGEO%YRDIM%NGPBLKS)
  REAL(KIND=JPRB),INTENT(INOUT) :: PGFLT1(YDGEO%YRDIM%NPROMA,YDGEO%YRDIMV%NFLEVG,&
    & YDMODEL%YRML_GCONF%YGFL%NDIM1,YDGEO%YRDIM%NGPBLKS)
  REAL(KIND=JPRB),INTENT(INOUT) :: PGFLPC(YDGEO%YRDIM%NPROMA,YDGEO%YRDIMV%NFLEVG,&
    & YDMODEL%YRML_GCONF%YGFL%NDIMPC,YDGEO%YRDIM%NGPBLKS)
  REAL(KIND=JPRB),INTENT(OUT) :: PUP9(YDGEO%YRDIM%NPROMA,YDGEO%YRDIMV%NFLEVG,YDGEO%YRDIM%NGPBLKS)
  REAL(KIND=JPRB),INTENT(OUT) :: PVP9(YDGEO%YRDIM%NPROMA,YDGEO%YRDIMV%NFLEVG,YDGEO%YRDIM%NGPBLKS)
  REAL(KIND=JPRB),INTENT(OUT) :: PTP9(YDGEO%YRDIM%NPROMA,YDGEO%YRDIMV%NFLEVG,YDGEO%YRDIM%NGPBLKS)
  REAL(KIND=JPRB),INTENT(OUT) :: PGFLP9(YDGEO%YRDIM%NPROMA,YDGEO%YRDIMV%NFLEVG,&
    & YDMODEL%YRML_GCONF%YGFL%NUMFLDS,YDGEO%YRDIM%NGPBLKS)

  INTEGER(KIND=JPIM) :: ILH0(YDGEO%YRDIM%NPROMA,YDGEO%YRDIMV%NFLEVG,0:3,YDGEO%YRDIM%NGPBLKS)
  REAL(KIND=JPRB) :: ZRSCAW(YDGEO%YRDIM%NPROMA,YDGEO%YRDIMV%NFLEVG,YDMODEL%YRML_DYN%YYTRSCAW%NDIM,&
    & YDGEO%YRDIM%NGPBLKS)
  REAL(KIND=JPRB) :: ZSCO(YDGEO%YRDIM%NPROMA,YDGEO%YRDIMV%NFLEVG,YDMODEL%YRML_DYN%YYTSCO%NDIM,&
    & YDGEO%YRDIM%NGPBLKS)
  REAL(KIND=JPRB) :: ZCCO(YDGEO%YRDIM%NPROMA,YDGEO%YRDIMV%NFLEVG,YDMODEL%YRML_DYN%YYTCCO%NDIM,&
    & YDGEO%YRDIM%NGPBLKS)
  REAL(KIND=JPRB) :: ZLSCAWH(YDGEO%YRDIM%NPROMNH,YDGEO%YRDIMV%NFLEVG,YDMODEL%YRML_DYN%YYTLSCAWH%NDIM,&
    & YDGEO%YRDIM%NGPBLKS)
  REAL(KIND=JPRB) :: ZRSCAWH(YDGEO%YRDIM%NPROMNH,YDGEO%YRDIMV%NFLEVG,YDMODEL%YRML_DYN%YYTRSCAWH%NDIM,&
    & YDGEO%YRDIM%NGPBLKS)

  CALL CALL_SL(YDGEO,YDGMV,YDMODEL,PGFL,YDSL,KVSEPC,KVSEPL,PB1,PB2,PWRL9,PGMVT1,PGMVT1S,PGFLT1,&
    & PGFLPC,KL0,PLSCAW,PUP9,PVP9,PTP9,PGFLP9,PSPPTCLEARP9,ILH0,ZRSCAW,ZSCO,ZCCO,ZLSCAWH,ZRSCAWH)

END SUBROUTINE CALL_SLSTACK

END SUBROUTINE CALL_SL_DRV
