! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE GPADDSLPHY(YDGEOMETRY,YDMODEL,YGFL,LDLFSTEP,KST,KEND,PTMST, &
 & PSAVTEND,PGFLSLP,&
 & PSLB1U0,PSLB1V0,PSLB1T0,PSLB1GFL0,PSLB1SPPTCLEAR0)  

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE TYPE_MODEL   , ONLY : MODEL
USE PARKIND1     , ONLY : JPIM, JPRB
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOM_YGFL     , ONLY : TYPE_GFLD

!**** *GPADDSLPHY - add physics tendencies to RHS of semi-lagrangian buffers

!     Purpose. add physics tendencies to RHS 
!     -------- 

!**   Interface.
!     ----------
!        *CALL* *GPADDSLPHY(...)*

!        Explicit arguments : see CPG
!        -------------------- 

!        Implicit arguments :
!        --------------------

!     Method.
!     -------
!        See documentation

!     Externals.
!     ----------

!     Reference.
!     ----------
!        None

!     Author.
!     -------
!        Nils Wedi  *ECMWF*

!     Modifications.
!     --------------
!   M.Hamrud      01-Oct-2003 CY28 Cleaning
!   N. Wedi and K. Yessad (Jan 2008): different dev for NH model and PC scheme
!   F.Vana        11-Sep-2020 Cleaning
!   F. Vana and S. Lang January 2023: SPPT updated to new seq. physics order
!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
TYPE(MODEL)       ,INTENT(IN)    :: YDMODEL
TYPE(TYPE_GFLD)   ,INTENT(IN)    :: YGFL
LOGICAL           ,INTENT(IN)    :: LDLFSTEP 
INTEGER(KIND=JPIM),INTENT(IN)    :: KST 
INTEGER(KIND=JPIM),INTENT(IN)    :: KEND 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTMST 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSAVTEND(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_PHY_G%YRSLPHY%NVTEND) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGFLSLP(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YGFL%NDIMSLP) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PSLB1U0(YDGEOMETRY%YRDIM%NPROMA, &
 & YDGEOMETRY%YRDIMV%NFLSA:YDGEOMETRY%YRDIMV%NFLEN)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PSLB1V0(YDGEOMETRY%YRDIM%NPROMA, &
 & YDGEOMETRY%YRDIMV%NFLSA:YDGEOMETRY%YRDIMV%NFLEN)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PSLB1T0(YDGEOMETRY%YRDIM%NPROMA, &
 & YDGEOMETRY%YRDIMV%NFLSA:YDGEOMETRY%YRDIMV%NFLEN)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PSLB1GFL0(YDGEOMETRY%YRDIM%NPROMA, &
 & YDGEOMETRY%YRDIMV%NFLSA:YDGEOMETRY%YRDIMV%NFLEN, YGFL%NDIMSLP) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PSLB1SPPTCLEAR0(YDGEOMETRY%YRDIM%NPROMA, &
 & YDGEOMETRY%YRDIMV%NFLSA:YDGEOMETRY%YRDIMV%NFLEN)

!     ------------------------------------------------------------------

INTEGER(KIND=JPIM) :: JLEV, JROF, JGFL
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('GPADDSLPHY',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM,YDDIMV=>YDGEOMETRY%YRDIMV,YDGEM=>YDGEOMETRY%YRGEM, &
 & YDMP=>YDGEOMETRY%YRMP,YDSLPHY=>YDMODEL%YRML_PHY_G%YRSLPHY,YDDYN=>YDMODEL%YRML_DYN%YRDYN, &
 & YDEPHY=>YDMODEL%YRML_PHY_EC%YREPHY, &
 & YDDYNA=>YDMODEL%YRML_DYN%YRDYNA,YDSPPT_CONFIG=>YDMODEL%YRML_GCONF%YRSPPT_CONFIG)
ASSOCIATE(NUMFLDS=>YGFL%NUMFLDS, YCOMP=>YGFL%YCOMP, NFLEVG=>YDDIMV%NFLEVG, &
 & NSITER=>YDDYN%NSITER,NCURRENT_ITER=>YDDYN%NCURRENT_ITER, &
 & MSPPTCLEAR_SAVTEND=>YDSLPHY%MSPPTCLEAR_SAVTEND, LPC_SPHY=>YDDYNA%LPC_SPHY, &
 & MT_SAVTEND=>YDSLPHY%MT_SAVTEND, MU_SAVTEND=>YDSLPHY%MU_SAVTEND, &
 & MV_SAVTEND=>YDSLPHY%MV_SAVTEND, MTS_SAVTEND=>YDSLPHY%MTS_SAVTEND, &
 & MUS_SAVTEND=>YDSLPHY%MUS_SAVTEND, MVS_SAVTEND=>YDSLPHY%MVS_SAVTEND, &
 & MQS_SAVTEND=>YDSLPHY%MQS_SAVTEND, NVTEND=>YDSLPHY%NVTEND)
!     ------------------------------------------------------------------

IF(.NOT.LDLFSTEP) THEN
  IF (LPC_SPHY .AND. (NCURRENT_ITER /= NSITER)) THEN
    DO JLEV=1,NFLEVG
      DO JROF=KST,KEND
        PSLB1U0(JROF,JLEV)=PSLB1U0(JROF,JLEV)+PSAVTEND(JROF,JLEV,MUS_SAVTEND)*PTMST
        PSLB1V0(JROF,JLEV)=PSLB1V0(JROF,JLEV)+PSAVTEND(JROF,JLEV,MVS_SAVTEND)*PTMST
        PSLB1T0(JROF,JLEV)=PSLB1T0(JROF,JLEV)+PSAVTEND(JROF,JLEV,MTS_SAVTEND)*PTMST
      ENDDO
    ENDDO
  ELSE
    DO JLEV=1,NFLEVG
      DO JROF=KST,KEND
        PSLB1U0(JROF,JLEV)=PSLB1U0(JROF,JLEV)+PSAVTEND(JROF,JLEV,MU_SAVTEND)*PTMST
        PSLB1V0(JROF,JLEV)=PSLB1V0(JROF,JLEV)+PSAVTEND(JROF,JLEV,MV_SAVTEND)*PTMST
        PSLB1T0(JROF,JLEV)=PSLB1T0(JROF,JLEV)+PSAVTEND(JROF,JLEV,MT_SAVTEND)*PTMST
      ENDDO
    ENDDO
  ENDIF

  DO JGFL=1,NUMFLDS
    IF(YCOMP(JGFL)%LPHY) THEN
      IF (LPC_SPHY .AND. (NCURRENT_ITER /= NSITER) .AND. YCOMP(JGFL)%CNAME == ' HUMIDITY') THEN
        DO JLEV=1,NFLEVG
          DO JROF=KST,KEND
            PSLB1GFL0(JROF,JLEV,YCOMP(JGFL)%MPSLP)=PSLB1GFL0(JROF,JLEV,YCOMP(JGFL)%MPSLP)+&
             & PSAVTEND(JROF,JLEV,MQS_SAVTEND)*PTMST  
          ENDDO
        ENDDO
      ELSE
        DO JLEV=1,NFLEVG
          DO JROF=KST,KEND
            PSLB1GFL0(JROF,JLEV,YCOMP(JGFL)%MPSLP)=PSLB1GFL0(JROF,JLEV,YCOMP(JGFL)%MPSLP)+&
             & PGFLSLP(JROF,JLEV,YCOMP(JGFL)%MPSLP)*PTMST  
          ENDDO
        ENDDO
      ENDIF
    ENDIF
  ENDDO
ENDIF

!     ------------------------------------------------------------------

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('GPADDSLPHY',1,ZHOOK_HANDLE)
END SUBROUTINE GPADDSLPHY
