! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE GPRCP(KPROMA,KST,KPROF,KFLEV,PQ,PQI,PQL,PQR,PQS,PQG,PCP,PR,PKAP,PGFL,KGFLTYP,&
  LDTHERMACT)

!**** *GPRCP* - Computes Cp, R and R/Cp from Q

!     Purpose.
!     --------
!        Computes Cp, R and R/Cp from Q

!**   Interface.
!     ----------
!        *CALL* *GPRCP(...)

!        Explicit arguments :
!        --------------------

!        INPUT:
!          KPROMA               - dimensioning.
!          KSTART               - start of work.
!          KPROF                - depth of work.
!          KFLEV                - number of layers.
!          PQ(KPROMA,KFLEV)     - specific humidity.
!          PQI(KPROMA,KFLEV)    - ice.
!          PQL(KPROMA,KFLEV)    - liquid water.
!          PQR(KPROMA,KFLEV)    - rain.
!          PQS(KPROMA,KFLEV)    - snow.
!          PQG(KPROMA,KFLEV)    - graupel.

!        OUTPUT:
!          PCP(KPROMA,KFLEV)    - CP
!          PR(KPROMA,KFLEV)     - R
!          PKAP(KPROMA,KFLEV)   - KAPPA

!        Implicit arguments :  Physical constants from YOMCST
!        --------------------

!     Method.
!     -------
!        See documentation

!     Externals.  None.
!     ----------

!     Reference.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     Author.
!     -------
!      Mats Hamrud and Philippe Courtier  *ECMWF*
!      Original : 88-02-04

!     Modifications.
!      M.Hamrud      01-Oct-2003 CY28 Cleaning
!      Y.Seity  04-02-13 (Rain, Snow and Graupel)
!      M.Hamrud  15-Jan-2006  Revised GPRCP
!      K. Yessad (Jan 2011): more compact rewriting.
!      R. El Khatib 28-Aug-2014 Optimizations :
!       - compute R or CP only if required
!       - loop collapsing whenever possible, through pure array syntax
!      A. Geer      01-Oct-2015    For independence of observation operator in OOPS, 
!                                  allow calls without YGFL initialised. Removal
!                                  of all YGFL references will have to wait.
!      H Petithomme (Dec 2020): general rewrite for optimization
!      R. El Khatib 23-Feb-2023 Portability fix for NEC Sx-Aurora : remove contiguous pointers and other dummies
!     ------------------------------------------------------------------

USE PARKIND1,ONLY: JPIM,JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMCST,ONLY: RD,RV,RCPD,RCPV,RCW,RCS
USE YOM_YGFL,ONLY: TYPE_GFLD,TYPE_GFL_COMP,YGFL
USE CODETOOLS,ONLY: SETDEFAULTL,SETDEFAULTI

IMPLICIT NONE

#include "abor1.intfb.h"

INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA,KFLEV,KST,KPROF
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KGFLTYP
LOGICAL,OPTIONAL,INTENT(IN) :: LDTHERMACT
REAL(KIND=JPRB),OPTIONAL,INTENT(IN) :: PQ(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL,INTENT(IN) :: PQL(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL,INTENT(IN) :: PQI(KPROMA,KFLEV),PQR(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL,INTENT(IN) :: PQS(KPROMA,KFLEV),PQG(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL,INTENT(IN) :: PGFL(KPROMA,KFLEV,YGFL%NDIM)
REAL(KIND=JPRB),OPTIONAL,TARGET,INTENT(OUT) :: PCP(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL,TARGET,INTENT(OUT) :: PR(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL,INTENT(OUT) :: PKAP(KPROMA,KFLEV)

REAL(KIND=JPRB),TARGET :: ZCP0(KPROMA,KFLEV),ZR0(KPROMA,KFLEV)
REAL(KIND=JPRB),CONTIGUOUS,POINTER :: ZCP(:,:),ZR(:,:)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK("GPRCP",0,ZHOOK_HANDLE)

IF (PRESENT(PR)) THEN
  ZR => PR(:,:)
ELSEIF (PRESENT(PKAP)) THEN
  ZR => ZR0(:,:)
ELSE
  ZR => NULL()
ENDIF

IF (PRESENT(PCP)) THEN
  ZCP => PCP(:,:)
ELSEIF (PRESENT(PKAP)) THEN
  ZCP => ZCP0(:,:)
ELSE
  ZCP => NULL()
ENDIF

IF (PRESENT(PGFL)) THEN
  !DIR$ FORCEINLINE
  CALL GPRCPGFL(YGFL,KPROMA,KST,KPROF,KFLEV,PGFL,KGFLTYP)
ELSE
  !DIR$ FORCEINLINE
  CALL GPRCPQ(YGFL,KPROMA,KST,KPROF,KFLEV,PQ=PQ,PQL=PQL,PQI=PQI,PQR=PQR,PQS=PQS,&
    PQG=PQG,LDTHERMACT=LDTHERMACT)
ENDIF

IF (PRESENT(PKAP)) PKAP(KST:KPROF,1:KFLEV)=ZR(KST:KPROF,1:KFLEV)/ZCP(KST:KPROF,1:KFLEV)

IF (LHOOK) CALL DR_HOOK("GPRCP",1,ZHOOK_HANDLE)
CONTAINS
SUBROUTINE GPRCPGFL(YGFL,KPROMA,KST,KPROF,KFLEV,PGFL,KGFLTYP)
  TYPE(TYPE_GFLD),INTENT(IN) :: YGFL
  INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA,KFLEV,KST,KPROF
  REAL(KIND=JPRB),INTENT(IN) :: PGFL(KPROMA,KFLEV,YGFL%NDIM)
  INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KGFLTYP

  INTEGER(KIND=JPIM) :: IGFLTYP,JL,JP,JGFL,I,NACT,IPT(YGFL%NUMFLDS)
  REAL(KIND=JPRB) :: YR(YGFL%NUMFLDS),YCP(YGFL%NUMFLDS)

  ASSOCIATE(YCOMP=>YGFL%YCOMP)

  IGFLTYP = SETDEFAULTI(0,KGFLTYP)

  NACT = 0
  IF (IGFLTYP == 0) THEN
    DO JGFL=1,YGFL%NUMFLDS
      IF (.NOT.YCOMP(JGFL)%LTHERMACT) CYCLE

      NACT = NACT+1
      IPT(NACT) = YCOMP(JGFL)%MP
      YR(NACT) = YCOMP(JGFL)%R
      YCP(NACT) = YCOMP(JGFL)%RCP
    ENDDO
  ELSEIF (IGFLTYP == 1) THEN
    DO JGFL=1,YGFL%NUMFLDS
      IF (.NOT.YCOMP(JGFL)%LTHERMACT) CYCLE

      NACT = NACT+1
      IPT(NACT) = YCOMP(JGFL)%MP1
      YR(NACT) = YCOMP(JGFL)%R
      YCP(NACT) = YCOMP(JGFL)%RCP
    ENDDO
  ELSEIF (IGFLTYP == 5) THEN
    DO JGFL=1,YGFL%NUMFLDS
      IF (.NOT.YCOMP(JGFL)%LTHERMACT) CYCLE

      NACT = NACT+1
      IPT(NACT) = YCOMP(JGFL)%MP5
      YR(NACT) = YCOMP(JGFL)%R
      YCP(NACT) = YCOMP(JGFL)%RCP
    ENDDO
  ELSEIF (IGFLTYP == 9) THEN
    DO JGFL=1,YGFL%NUMFLDS
      IF (.NOT.YCOMP(JGFL)%LTHERMACT) CYCLE

      NACT = NACT+1
      IPT(NACT) = YCOMP(JGFL)%MP9_PH
      YR(NACT) = YCOMP(JGFL)%R
      YCP(NACT) = YCOMP(JGFL)%RCP
    ENDDO
  ELSEIF (IGFLTYP == 101) THEN
    DO JGFL=1,YGFL%NUMFLDS
      IF (.NOT.YCOMP(JGFL)%LTHERMACT) CYCLE

      NACT = NACT+1
      IPT(NACT) = YCOMP(JGFL)%MP_SL1
      YR(NACT) = YCOMP(JGFL)%R
      YCP(NACT) = YCOMP(JGFL)%RCP
    ENDDO
  ELSE
    CALL ABOR1("UNKNOWN GFL TYPE")
  ENDIF

  IF (ASSOCIATED(ZR)) THEN
    ! note: mind the brackets on PGFL, in order to add RD at last (precise computes)
    ! optim: explicit treatment of cases 0, 1, 2 and 3 (fewer loops)
    IF (NACT == 0) THEN
      ZR(KST:KPROF,1:KFLEV) = RD
    ELSE IF (NACT == 1) THEN
      ZR(KST:KPROF,1:KFLEV) = RD+(YR(1)-RD)*PGFL(KST:KPROF,1:KFLEV,IPT(1))
    ELSE IF (NACT == 2) THEN
      ZR(KST:KPROF,1:KFLEV) = RD+((YR(1)-RD)*PGFL(KST:KPROF,1:KFLEV,IPT(1))+&
       & (YR(2)-RD)*PGFL(KST:KPROF,1:KFLEV,IPT(2)))
    ELSE IF (NACT == 3) THEN
      ZR(KST:KPROF,1:KFLEV) = RD+((YR(1)-RD)*PGFL(KST:KPROF,1:KFLEV,IPT(1))+&
       & (YR(2)-RD)*PGFL(KST:KPROF,1:KFLEV,IPT(2))+&
       & (YR(3)-RD)*PGFL(KST:KPROF,1:KFLEV,IPT(3)))
    ELSE
      ZR(KST:KPROF,1:KFLEV) = (YR(1)-RD)*PGFL(KST:KPROF,1:KFLEV,IPT(1))+&
       & (YR(2)-RD)*PGFL(KST:KPROF,1:KFLEV,IPT(2))+&
       & (YR(3)-RD)*PGFL(KST:KPROF,1:KFLEV,IPT(3))

      DO I=4,NACT-1
        ZR(KST:KPROF,1:KFLEV) = ZR(KST:KPROF,1:KFLEV)+&
          (YR(I)-RD)*PGFL(KST:KPROF,1:KFLEV,IPT(I))
      ENDDO

      I=NACT
      ZR(KST:KPROF,1:KFLEV) = RD+(ZR(KST:KPROF,1:KFLEV)+&
          (YR(I)-RD)*PGFL(KST:KPROF,1:KFLEV,IPT(I)))
    ENDIF
  ENDIF

  IF (ASSOCIATED(ZCP)) THEN
    ! note: mind the brackets on PGFL, in order to add RCPD at last (precise computes)
    ! optim: explicit treatment of cases 0, 1, 2 and 3 (fewer loops)
    IF (NACT == 0) THEN
      ZCP(KST:KPROF,1:KFLEV) = RCPD
    ELSE IF (NACT == 1) THEN
      ZCP(KST:KPROF,1:KFLEV) = RCPD+(YCP(1)-RCPD)*PGFL(KST:KPROF,1:KFLEV,IPT(1))
    ELSE IF (NACT == 2) THEN
      ZCP(KST:KPROF,1:KFLEV) = RCPD+((YCP(1)-RCPD)*PGFL(KST:KPROF,1:KFLEV,IPT(1))+&
       & (YCP(2)-RCPD)*PGFL(KST:KPROF,1:KFLEV,IPT(2)))
    ELSE IF (NACT == 3) THEN
      ZCP(KST:KPROF,1:KFLEV) = RCPD+((YCP(1)-RCPD)*PGFL(KST:KPROF,1:KFLEV,IPT(1))+&
       & (YCP(2)-RCPD)*PGFL(KST:KPROF,1:KFLEV,IPT(2))+&
       & (YCP(3)-RCPD)*PGFL(KST:KPROF,1:KFLEV,IPT(3)))
    ELSE
      ZCP(KST:KPROF,1:KFLEV) = (YCP(1)-RCPD)*PGFL(KST:KPROF,1:KFLEV,IPT(1))+&
       & (YCP(2)-RCPD)*PGFL(KST:KPROF,1:KFLEV,IPT(2))+&
       & (YCP(3)-RCPD)*PGFL(KST:KPROF,1:KFLEV,IPT(3))

      DO I=4,NACT-1
        ZCP(KST:KPROF,1:KFLEV) = ZCP(KST:KPROF,1:KFLEV)+(YCP(I)-RCPD)*&
         & PGFL(KST:KPROF,1:KFLEV,IPT(I))
      ENDDO

      I=NACT
      ZCP(KST:KPROF,1:KFLEV) = RCPD+(ZCP(KST:KPROF,1:KFLEV)+(YCP(I)-RCPD)*&
       & PGFL(KST:KPROF,1:KFLEV,IPT(I)))
    ENDIF
  ENDIF
  END ASSOCIATE
END SUBROUTINE

SUBROUTINE GPRCPQ(YGFL,KPROMA,KST,KPROF,KFLEV,PQ,PQL,PQI,PQR,PQS,PQG,LDTHERMACT)
  TYPE(TYPE_GFLD),INTENT(IN) :: YGFL
  INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA,KFLEV,KST,KPROF
  REAL(KIND=JPRB),OPTIONAL,INTENT(IN) :: PQ(KPROMA,KFLEV)
  REAL(KIND=JPRB),OPTIONAL,INTENT(IN) :: PQL(KPROMA,KFLEV)
  REAL(KIND=JPRB),OPTIONAL,INTENT(IN) :: PQI(KPROMA,KFLEV)
  REAL(KIND=JPRB),OPTIONAL,INTENT(IN) :: PQR(KPROMA,KFLEV)
  REAL(KIND=JPRB),OPTIONAL,INTENT(IN) :: PQS(KPROMA,KFLEV)
  REAL(KIND=JPRB),OPTIONAL,INTENT(IN) :: PQG(KPROMA,KFLEV)
  LOGICAL,OPTIONAL,INTENT(IN) :: LDTHERMACT

  LOGICAL :: LTHERMACT,LQ,LL,LI

  ASSOCIATE(YQ=>YGFL%YQ,YL=>YGFL%YL,YI=>YGFL%YI,YR=>YGFL%YR,YS=>YGFL%YS,YG=>YGFL%YG)

  LTHERMACT = SETDEFAULTL(.TRUE.,LDTHERMACT)

  LQ = PRESENT(PQ).AND.(LTHERMACT.OR.YQ%LTHERMACT)
  LL = PRESENT(PQL).AND.(LTHERMACT.OR.YL%LTHERMACT)
  LI = PRESENT(PQI).AND.(LTHERMACT.OR.YI%LTHERMACT)

  IF (ASSOCIATED(ZR)) THEN
    ! note: mind that no brackets are used on multiple adds for reproducibility reasons
    ! optim: explicit treatment of cases LQ, LL and LI (fewer loops)
    IF (LQ.AND.LL.AND.LI) THEN
      ZR(KST:KPROF,1:KFLEV) = RD+(RV-RD)*PQ(KST:KPROF,1:KFLEV)-&
       & RD*PQL(KST:KPROF,1:KFLEV)-RD*PQI(KST:KPROF,1:KFLEV)
    ELSE
      IF (LQ) THEN
        ZR(KST:KPROF,1:KFLEV) = RD+(RV-RD)*PQ(KST:KPROF,1:KFLEV)
      ELSE
        ZR(KST:KPROF,1:KFLEV) = RD
     ENDIF

      IF (LL.AND.LI) THEN
        ZR(KST:KPROF,1:KFLEV) = ZR(KST:KPROF,1:KFLEV)-RD*PQL(KST:KPROF,1:KFLEV)-&
         & RD*PQI(KST:KPROF,1:KFLEV)
      ELSE IF (LL) THEN
        ZR(KST:KPROF,1:KFLEV) = ZR(KST:KPROF,1:KFLEV)-RD*PQL(KST:KPROF,1:KFLEV)
      ELSE IF (LI) THEN
        ZR(KST:KPROF,1:KFLEV) = ZR(KST:KPROF,1:KFLEV)-RD*PQI(KST:KPROF,1:KFLEV)
      ENDIF
    ENDIF

    IF (PRESENT(PQR).AND.(LTHERMACT.OR.YR%LTHERMACT))&
      ZR(KST:KPROF,1:KFLEV) = ZR(KST:KPROF,1:KFLEV)-RD*PQR(KST:KPROF,1:KFLEV)
    IF (PRESENT(PQS).AND.(LTHERMACT.OR.YS%LTHERMACT))&
      ZR(KST:KPROF,1:KFLEV) = ZR(KST:KPROF,1:KFLEV)-RD*PQS(KST:KPROF,1:KFLEV)
    IF (PRESENT(PQG).AND.(LTHERMACT.OR.YG%LTHERMACT))&
      ZR(KST:KPROF,1:KFLEV) = ZR(KST:KPROF,1:KFLEV)-RD*PQG(KST:KPROF,1:KFLEV)
  ENDIF

  IF (ASSOCIATED(ZCP)) THEN
    ! note: mind that no brackets are used on multiple adds for reproducibility reasons
    ! optim: explicit treatment of cases LQ, LL and LI (fewer loops)
    IF (LQ.AND.LL.AND.LI) THEN
      ZCP(KST:KPROF,1:KFLEV) = RCPD+(RCPV-RCPD)*PQ(KST:KPROF,1:KFLEV)+&
       & (RCW-RCPD)*PQL(KST:KPROF,1:KFLEV)+(RCS-RCPD)*PQI(KST:KPROF,1:KFLEV)
    ELSE
      IF (LQ) THEN
        ZCP(KST:KPROF,1:KFLEV) = RCPD+(RCPV-RCPD)*PQ(KST:KPROF,1:KFLEV)
      ELSE
        ZCP(KST:KPROF,1:KFLEV) = RCPD
      ENDIF

      IF (LL.AND.LI) THEN
        ZCP(KST:KPROF,1:KFLEV) = ZCP(KST:KPROF,1:KFLEV)+(RCW-RCPD)*PQL(KST:KPROF,1:KFLEV)+&
         & (RCS-RCPD)*PQI(KST:KPROF,1:KFLEV)
       ELSE  IF (LL) THEN
        ZCP(KST:KPROF,1:KFLEV) = ZCP(KST:KPROF,1:KFLEV)+(RCW-RCPD)*PQL(KST:KPROF,1:KFLEV)
      ELSE IF (LI) THEN
        ZCP(KST:KPROF,1:KFLEV) = ZCP(KST:KPROF,1:KFLEV)+(RCS-RCPD)*PQI(KST:KPROF,1:KFLEV)
      ENDIF
    ENDIF

    IF (PRESENT(PQR).AND.(LTHERMACT.OR.YR%LTHERMACT))&
      ZCP(KST:KPROF,1:KFLEV) = ZCP(KST:KPROF,1:KFLEV)+(RCW-RCPD)*PQR(KST:KPROF,1:KFLEV)
    IF (PRESENT(PQS).AND.(LTHERMACT.OR.YS%LTHERMACT))&
      ZCP(KST:KPROF,1:KFLEV) = ZCP(KST:KPROF,1:KFLEV)+(RCS-RCPD)*PQS(KST:KPROF,1:KFLEV)
    IF (PRESENT(PQG).AND.(LTHERMACT.OR.YG%LTHERMACT))&
      ZCP(KST:KPROF,1:KFLEV) = ZCP(KST:KPROF,1:KFLEV)+(RCS-RCPD)*PQG(KST:KPROF,1:KFLEV)
  ENDIF
  END ASSOCIATE
END SUBROUTINE
END SUBROUTINE

