! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE FJBCHVAR_MOD
!-----------------------------------------------------------
!     Module containing functions needed for the background 
!     dependent change of humidity control variable
!
!     Patrick Gillies   09-12-19:  Original
!
!-----------------------------------------------------------
  USE PARKIND1 , ONLY : JPIM, JPRB
  USE YOMJG    , ONLY : TYPE_JBCHVAR, TYPE_JB_STRUCT


  IMPLICIT NONE

  CONTAINS

  FUNCTION FQS_FUNC(KSLEV,STRUCT_JBCHVAR)
    REAL(KIND=JPRB) :: FQS_FUNC
    INTEGER(KIND=JPIM) :: KSLEV
    TYPE(TYPE_JBCHVAR) :: STRUCT_JBCHVAR
    FQS_FUNC=STRUCT_JBCHVAR%RQS(MAX(MIN(KSLEV,6),0))
    RETURN
  END FUNCTION

  FUNCTION FQT_FUNC(KSLEV,STRUCT_JBCHVAR)
!     2. Normalization for q/q_s(T^b)-based cv
!        Combines: L = Subsaturated (rh^b < 1)
!                  H = Supersaturated (rh^b > 1)
!        Inputs:   kilev = model level
!                  prhb  = relative humidity background
!                  prh   = relative humidity 
    REAL(JPRB)         :: FQT_FUNC
    INTEGER(KIND=JPIM) :: KSLEV
    TYPE(TYPE_JBCHVAR) :: STRUCT_JBCHVAR
    FQT_FUNC = STRUCT_JBCHVAR%RQT(MAX(MIN(KSLEV,6),0))
    RETURN
  END FUNCTION

  FUNCTION FSUB_FUNC(PRHB)
    REAL(KIND=JPRB) :: FSUB_FUNC
    REAL(KIND=JPRB) :: PRHB
    
    FSUB_FUNC = 0.5_JPRB+SIGN(0.5_JPRB,1.0_JPRB-PRHB)

    RETURN
  END FUNCTION

  FUNCTION FQH_FUNC(KILEV,PRH,STRUCT_JBCHVAR,STRUCT_JB_STRUCT)
    REAL(KIND=JPRB) :: FQH_FUNC
    INTEGER(KIND=JPIM) :: KILEV
    REAL(KIND=JPRB) :: PRH
    TYPE(TYPE_JBCHVAR) :: STRUCT_JBCHVAR
    TYPE(TYPE_JB_STRUCT) :: STRUCT_JB_STRUCT

    FQH_FUNC = MIN(MAX(PRH,STRUCT_JBCHVAR%RQHMIN(KILEV)), &
                           &    STRUCT_JB_STRUCT%JBCHVAR%RQHMAX(KILEV))
    RETURN
  END FUNCTION
 
  FUNCTION FQL_FUNC(KILEV, PRH, STRUCT_JBCHVAR)
    REAL(JPRB)         :: FQL_FUNC
    INTEGER(KIND=JPIM) :: KILEV
    REAL(KIND=JPRB) :: PRH
    TYPE(TYPE_JBCHVAR) :: STRUCT_JBCHVAR

    FQL_FUNC = MIN(MAX(PRH,STRUCT_JBCHVAR%RQLMIN(KILEV)), &
                               &    STRUCT_JBCHVAR%RQLMAX(KILEV))
    RETURN

  END FUNCTION


  FUNCTION FQSIGMA_FUNC(KILEV,KSLEV,PRHB,PRH,STRUCT_JBCHVAR,STRUCT_JB_STRUCT)
    REAL(JPRB) :: FQSIGMA_FUNC
    INTEGER(KIND=JPIM) :: KILEV,KSLEV
    REAL(KIND=JPRB) :: PRHB
    REAL(KIND=JPRB) :: PRH
    TYPE(TYPE_JBCHVAR) :: STRUCT_JBCHVAR
    TYPE(TYPE_JB_STRUCT) :: STRUCT_JB_STRUCT

    FQSIGMA_FUNC = &
 & 0.7_JPRB*FQS_FUNC(KILEV-KSLEV,STRUCT_JBCHVAR)&
 &  *(           FSUB_FUNC(PRHB) *(                  STRUCT_JBCHVAR%RQLSTD(KILEV,0)&
 &             +FQL_FUNC(KILEV,PRH,STRUCT_JBCHVAR)*( STRUCT_JBCHVAR%RQLSTD(KILEV,1)&
 &             +FQL_FUNC(KILEV,PRH,STRUCT_JBCHVAR)*( STRUCT_JBCHVAR%RQLSTD(KILEV,2)&
 &             +FQL_FUNC(KILEV,PRH,STRUCT_JBCHVAR)*( STRUCT_JBCHVAR%RQLSTD(KILEV,3)&
 &             +FQL_FUNC(KILEV,PRH,STRUCT_JBCHVAR)*( STRUCT_JBCHVAR%RQLSTD(KILEV,4)&
 &             +FQL_FUNC(KILEV,PRH,STRUCT_JBCHVAR)*( STRUCT_JBCHVAR%RQLSTD(KILEV,5)))))))&
 &    +(1.0_JPRB-FSUB_FUNC(PRHB))*(                                   STRUCT_JBCHVAR%RQHSTD(KILEV,0)&
 &             +FQH_FUNC(KILEV,PRH,STRUCT_JBCHVAR,STRUCT_JB_STRUCT)*( STRUCT_JBCHVAR%RQHSTD(KILEV,1)&
 &             +FQH_FUNC(KILEV,PRH,STRUCT_JBCHVAR,STRUCT_JB_STRUCT)*( STRUCT_JBCHVAR%RQHSTD(KILEV,2)&
 &             +FQH_FUNC(KILEV,PRH,STRUCT_JBCHVAR,STRUCT_JB_STRUCT)*( STRUCT_JBCHVAR%RQHSTD(KILEV,3)&
 &             +FQH_FUNC(KILEV,PRH,STRUCT_JBCHVAR,STRUCT_JB_STRUCT)*( STRUCT_JBCHVAR%RQHSTD(KILEV,4)&
 &             +FQH_FUNC(KILEV,PRH,STRUCT_JBCHVAR,STRUCT_JB_STRUCT)*( STRUCT_JBCHVAR%RQHSTD(KILEV,5))))))))

  END FUNCTION



  FUNCTION FQTBAL_FUNC(KILEV,KSLEV,PRHB,STRUCT_JBCHVAR)
    REAL(KIND=JPRB) :: FQTBAL_FUNC
    INTEGER(KIND=JPIM) :: KILEV,KSLEV
    REAL(KIND=JPRB) :: PRHB
    TYPE(TYPE_JBCHVAR) :: STRUCT_JBCHVAR
    FQTBAL_FUNC = MAX(0.0_JPRB,&
   &                      FQT_FUNC(KILEV-KSLEV,STRUCT_JBCHVAR)*FSUB_FUNC(PRHB) &
   &  *(                                       STRUCT_JBCHVAR%RQTBAL(KILEV,0)&
   &    +FQL_FUNC(KILEV,PRHB,STRUCT_JBCHVAR)*( STRUCT_JBCHVAR%RQTBAL(KILEV,1)&
   &    +FQL_FUNC(KILEV,PRHB,STRUCT_JBCHVAR)*( STRUCT_JBCHVAR%RQTBAL(KILEV,2)&
   &    +FQL_FUNC(KILEV,PRHB,STRUCT_JBCHVAR)*( STRUCT_JBCHVAR%RQTBAL(KILEV,3)&
   &    +FQL_FUNC(KILEV,PRHB,STRUCT_JBCHVAR)*( STRUCT_JBCHVAR%RQTBAL(KILEV,4)&
   &    +FQL_FUNC(KILEV,PRHB,STRUCT_JBCHVAR)*( STRUCT_JBCHVAR%RQTBAL(KILEV,5))))))))

    RETURN
  END FUNCTION

  FUNCTION FQTBALSAT_FUNC(KILEV,KSLEV,PRHB,STRUCT_JBCHVAR)
    REAL(KIND=JPRB) :: FQTBALSAT_FUNC
    INTEGER(KIND=JPIM) :: KILEV,KSLEV
    REAL(KIND=JPRB) :: PRHB
    TYPE(TYPE_JBCHVAR) :: STRUCT_JBCHVAR
    FQTBALSAT_FUNC = MIN(1.0_JPRB, MAX(0.0_JPRB,&
   &                                   FQT_FUNC(KILEV-KSLEV,STRUCT_JBCHVAR) &
   &  *(                                  STRUCT_JBCHVAR%RQTBAL(KILEV,0)&
   &    +FQL_FUNC(KILEV,PRHB,STRUCT_JBCHVAR)*( STRUCT_JBCHVAR%RQTBAL(KILEV,1)&
   &    +FQL_FUNC(KILEV,PRHB,STRUCT_JBCHVAR)*( STRUCT_JBCHVAR%RQTBAL(KILEV,2)&
   &    +FQL_FUNC(KILEV,PRHB,STRUCT_JBCHVAR)*( STRUCT_JBCHVAR%RQTBAL(KILEV,3)&
   &    +FQL_FUNC(KILEV,PRHB,STRUCT_JBCHVAR)*( STRUCT_JBCHVAR%RQTBAL(KILEV,4)&
   &    +FQL_FUNC(KILEV,PRHB,STRUCT_JBCHVAR)*( STRUCT_JBCHVAR%RQTBAL(KILEV,5)))))))))
    RETURN
  END FUNCTION

  FUNCTION FQMIN_FUNC(KILEV,PRHB,STRUCT_JBCHVAR)
    REAL(KIND=JPRB) :: FQMIN_FUNC
    INTEGER(KIND=JPIM) :: KILEV
    REAL(KIND=JPRB) :: PRHB
    TYPE(TYPE_JBCHVAR) :: STRUCT_JBCHVAR
    FQMIN_FUNC = STRUCT_JBCHVAR%RQLMIN(KILEV)
    RETURN
  END FUNCTION

  FUNCTION FQMAX_FUNC(KILEV,PRHB,STRUCT_JBCHVAR)
    REAL(KIND=JPRB) :: FQMAX_FUNC
    INTEGER(KIND=JPIM) :: KILEV
    REAL(KIND=JPRB) :: PRHB
    TYPE(TYPE_JBCHVAR) :: STRUCT_JBCHVAR
    FQMAX_FUNC = STRUCT_JBCHVAR%RQHMAX(KILEV)
    RETURN
  END FUNCTION


END MODULE

