! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE UPDATE_SFX(YDGEOMETRY,YDMODEL,PTIMEC,PTSTEP)

!**** *UPDATE_SFX*

!     PURPOSE.
!     --------

!     Receive OASIS fields and update surfex buffer filed for ARPEGE/AROME use


!     METHOD.
!     -------

!     EXTERNALS.
!     ----------

!     AUTHORS.
!     --------

!        A. Voldoire  06-2014

!     MODIFICATIONS.
!     --------------
!        C. Lebeaupin 01/2018: adapt to cy41  
!        S. Bielli et S.Malardel : adapt CY43t2 (12/2019) et CY48t1 (12/2020)
!     ------------------------------------------------------------------
USE TYPE_MODEL         , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK
USE YOMGPPB  , ONLY : GPARBUF
!-----------------------------------------------------------------------

IMPLICIT NONE

TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(MODEL)   ,INTENT(INOUT) :: YDMODEL
REAL(KIND=JPRB), INTENT(IN) :: PTIMEC
REAL(KIND=JPRB), INTENT(IN) :: PTSTEP

REAL(KIND=JPRB), DIMENSION(YDGEOMETRY%YRGEM%NGPTOT) :: ZZENITH
REAL(KIND=JPRB), DIMENSION(YDGEOMETRY%YRGEM%NGPTOT) :: ZEMIS
REAL(KIND=JPRB), DIMENSION(YDGEOMETRY%YRGEM%NGPTOT) :: ZTSURF
REAL(KIND=JPRB), DIMENSION(YDGEOMETRY%YRGEM%NGPTOT,YDMODEL%YRML_PHY_MF%YRPARAR%NSWB_MNH) :: ZALBDIR
REAL(KIND=JPRB), DIMENSION(YDGEOMETRY%YRGEM%NGPTOT,YDMODEL%YRML_PHY_MF%YRPARAR%NSWB_MNH) :: ZALBSCA
REAL(KIND=JPRB), DIMENSION(YDGEOMETRY%YRGEM%NGPTOT) :: ZTSRAD
REAL(KIND=JPRB), DIMENSION(YDGEOMETRY%YRDIM%NPROMA, YDMODEL%YRML_PHY_MF%YRPARAR%NGPAR) :: ZGPAR
!
REAL(KIND=JPRB) :: ZMU0
!
INTEGER(KIND=JPIM) :: JBLOCK,INDX1,INDX2,INPROMA,JROF
LOGICAL :: LLOASIS_PUT
!
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
!
#include "recv_oasis3_sfx.h"
!
!-----------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('UPDATE_SFX',0,ZHOOK_HANDLE)

ASSOCIATE(NGPTOT=>YDGEOMETRY%YRGEM%NGPTOT, &
 &NPROMA=>YDGEOMETRY%YRDIM%NPROMA,NGPBLKS=>YDGEOMETRY%YRDIM%NGPBLKS,&
 &YRGSGEOM_NB=>YDGEOMETRY%YRGSGEOM_NB,&
 &NGPAR=>YDMODEL%YRML_PHY_MF%YRPARAR%NGPAR,MVEMIS=>YDMODEL%YRML_PHY_MF%YRPARAR%MVEMIS, &
 &MVTS=>YDMODEL%YRML_PHY_MF%YRPARAR%MVTS,MALBDIR=>YDMODEL%YRML_PHY_MF%YRPARAR%MALBDIR,&
 &MALBSCA=>YDMODEL%YRML_PHY_MF%YRPARAR%MALBSCA,XSW_BANDS=>YDMODEL%YRML_PHY_MF%YRPARAR%XSW_BANDS,&
 &NSWB_MNH=>YDMODEL%YRML_PHY_MF%YRPARAR%NSWB_MNH)

DO JROF=1,NGPTOT
   ZMU0=MAX( YDMODEL%YRML_GCONF%YRRIP%RSIDEC*YRGSGEOM_NB%GEMU(JROF)&
   & -YDMODEL%YRML_GCONF%YRRIP%RCODEC*YDMODEL%YRML_GCONF%YRRIP%RCOVSR &
   & *SQRT(1.0_JPRB-YRGSGEOM_NB%GEMU(JROF)**2)*COS(YRGSGEOM_NB%GELAM(JROF))&
   & +YDMODEL%YRML_GCONF%YRRIP%RCODEC*YDMODEL%YRML_GCONF%YRRIP%RSIVSR&
   & *SQRT(1.0_JPRB-YRGSGEOM_NB%GEMU(JROF)**2)*SIN(YRGSGEOM_NB%GELAM(JROF))&
   & ,0.0_JPRB)
   ZZENITH(JROF)=ACOS(ZMU0)
ENDDO

CALL RECV_OASIS3_SFX(YDGEOMETRY,PTIMEC,PTSTEP,NSWB_MNH,XSW_BANDS,ZZENITH,LLOASIS_PUT,ZEMIS,ZTSURF,&
                       &        ZALBDIR,ZALBSCA,ZTSRAD) 
IF (LLOASIS_PUT) THEN
 DO JBLOCK=1,NGPBLKS
  INDX1=1+(JBLOCK-1)*NPROMA
  INDX2=MIN(JBLOCK*NPROMA,NGPTOT)
  INPROMA=INDX2-INDX1+1
  GPARBUF(1:INPROMA,MVEMIS,JBLOCK)=ZEMIS (INDX1:INDX2)
  GPARBUF(1:INPROMA,MVTS,JBLOCK)=ZTSURF(INDX1:INDX2)
  GPARBUF(1:INPROMA,MALBDIR:MALBDIR+NSWB_MNH-1,JBLOCK)=ZALBDIR(INDX1:INDX2,:)
  GPARBUF(1:INPROMA,MALBSCA:MALBSCA+NSWB_MNH-1,JBLOCK)=ZALBSCA(INDX1:INDX2,:)
 ENDDO
ENDIF
!
END ASSOCIATE

IF (LHOOK) CALL DR_HOOK('UPDATE_SFX',1,ZHOOK_HANDLE)
!-------------------------------------------------------------------------------
!
END SUBROUTINE UPDATE_SFX

