! (C) Copyright 2011- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE DIGFIL(YDGEOMETRY,YDGFL,YDML_GCONF,KSTEP,KDIGLST,KSUB,PSPA3,PSPD2D,PSPA1,LDIAB,PGFLGP)
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGFL , ONLY : TGFL
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TGFL) ,INTENT(INOUT) :: YDGFL
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT):: YDML_GCONF
INTEGER(KIND=JPIM),INTENT(IN) :: KSTEP
INTEGER(KIND=JPIM),INTENT(IN) :: KDIGLST
INTEGER(KIND=JPIM),INTENT(IN) :: KSUB
REAL(KIND=JPRB) ,INTENT(IN) :: PSPA3(YDGEOMETRY%YRDIMV%NFLSUR,YDGEOMETRY%YRDIM%NSPEC2,YDML_GCONF%YRDIMF%NS3D)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPD2D(YDGEOMETRY%YRDIM%NSPEC2,YDML_GCONF%YRDIMF%NFD2D)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPA1(YDGEOMETRY%YRDIMV%NFLEVL,2)
LOGICAL ,INTENT(IN) :: LDIAB
REAL(KIND=JPRB),OPTIONAL,INTENT(INOUT) :: PGFLGP(YDGEOMETRY%YRGEM%NGPTOT,YDGEOMETRY%YRDIMV%NFLEVG)
call abor1("DIGFIL should never be called with this build configuration - EXITING")
END SUBROUTINE DIGFIL
