! (C) Copyright 2011- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE FPEDRD(YDQTYPE,YDTFP,YDALLCAT,KPROMA,KST,KND,KFLEVG,POROG,POROGL,POROGM, &
 & PQIRAD, PQLRAD, &
 & PCP, PKAP, PR, PRT, PGEOPF,PTKE,PUT0,PVT0,PUT0L,PVT0L,&
 & PDIVT0,PVORT0,PT,PTL,PTM,PSTDF,PSHDF,PTETA,PTETAL,PTETAM, &
 & PTETAV,PGPFL,PGPFM,PRCORI,PRACTHE,PRATATH,PGM,PPV,&
 & PPFL, POMG, PEDR, &
 & PTI1,PTI1H, PTI1M,PEDRDC, PEDRDCH,PEDRDCM,PEDRDCL)
USE PARKIND1 , ONLY : JPIM, JPRB
use types_fpcat , only:&
 & all_fpcat_types
USE YOMAFN , ONLY : ALL_FULLPOS_TYPES
USE TYPE_FPRQDYNS, ONLY : TYPE_FPRQDYN
TYPE (TYPE_FPRQDYN), INTENT(IN) :: YDQTYPE
TYPE(ALL_FULLPOS_TYPES), INTENT(IN) :: YDTFP
TYPE(ALL_FPCAT_TYPES),INTENT(IN) :: YDALLCAT
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KST
INTEGER(KIND=JPIM),INTENT(IN) :: KND
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEVG
REAL(KIND=JPRB) ,INTENT(IN) :: POROG(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: POROGL(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: POROGM(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PQIRAD(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PQLRAD(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PCP(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PKAP(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PR(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PRT(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOPF(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTKE(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PUT0(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PVT0(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PUT0L(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PVT0L(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIVT0(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PVORT0(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTL(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTM(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PSTDF(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PSHDF(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTETA(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTETAL(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTETAM(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTETAV(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PGPFL(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PGPFM(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PRCORI(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PRACTHE(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PRATATH(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PGM(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PPV(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PPFL(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: POMG(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PEDR(KPROMA,KFLEVG)
REAL(KIND=JPRB) , INTENT(OUT) :: PTI1(KPROMA,KFLEVG)
REAL(KIND=JPRB) , INTENT(OUT) :: PTI1H(KPROMA)
REAL(KIND=JPRB) , INTENT(OUT) :: PTI1M(KPROMA)
REAL(KIND=JPRB) , INTENT(OUT) :: PEDRDC(KPROMA,KFLEVG)
REAL(KIND=JPRB) , INTENT(OUT) :: PEDRDCH(KPROMA)
REAL(KIND=JPRB) , INTENT(OUT) :: PEDRDCM(KPROMA)
REAL(KIND=JPRB) , INTENT(OUT) :: PEDRDCL(KPROMA)
call abor1("FPEDRD should never be called with this build configuration - EXITING")
END SUBROUTINE FPEDRD
