! (C) Copyright 2011- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE SATSIM(YGFL,KPROMA,KIDIA,KFDIA,KSATSIM,KFLEVG, &
 & PGELAT,PGELAM,POROG,PLSM,PCI,PTRENU,PQLINU,PCAPE,PTCLS,PQCLS,PUCLS,PVCLS,PDSP, &
 & PRESF,PT,PQ,PO3,PA,PL,PI,PR,PS, &
 & PDCLBT,PDCSBT,PDCDRFL,PDCRRFL,PSNFRAC,PHVFRAC,KDATE_NOW)
USE PARKIND1, ONLY : JPIM, JPRB
USE YOM_YGFL, ONLY : TYPE_GFLD
TYPE(TYPE_GFLD) ,INTENT(IN) :: YGFL
INTEGER(KIND=JPIM), INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KSATSIM
INTEGER(KIND=JPIM), INTENT(IN) :: KFLEVG
REAL(KIND=JPRB), INTENT(IN) :: PGELAM(KPROMA)
REAL(KIND=JPRB), INTENT(IN) :: PGELAT(KPROMA)
REAL(KIND=JPRB), INTENT(IN) :: POROG(KPROMA)
REAL(KIND=JPRB), INTENT(IN) :: PLSM(KPROMA)
REAL(KIND=JPRB), INTENT(IN) :: PCI(KPROMA)
REAL(KIND=JPRB), INTENT(IN) :: PTRENU(KPROMA)
REAL(KIND=JPRB), INTENT(IN) :: PQLINU(KPROMA)
REAL(KIND=JPRB), INTENT(IN) :: PCAPE(KPROMA)
REAL(KIND=JPRB), INTENT(IN) :: PTCLS(KPROMA)
REAL(KIND=JPRB), INTENT(IN) :: PQCLS(KPROMA)
REAL(KIND=JPRB), INTENT(IN) :: PUCLS(KPROMA)
REAL(KIND=JPRB), INTENT(IN) :: PVCLS(KPROMA)
REAL(KIND=JPRB), INTENT(IN) :: PDSP(KPROMA)
REAL(KIND=JPRB), INTENT(IN) :: PRESF(KPROMA,KFLEVG)
REAL(KIND=JPRB), INTENT(IN) :: PT(KPROMA,KFLEVG)
REAL(KIND=JPRB), INTENT(IN) :: PQ(KPROMA,KFLEVG)
REAL(KIND=JPRB), INTENT(IN) :: PO3(KPROMA,KFLEVG)
REAL(KIND=JPRB), INTENT(IN) :: PA(KPROMA,KFLEVG)
REAL(KIND=JPRB), INTENT(IN) :: PL(KPROMA,KFLEVG)
REAL(KIND=JPRB), INTENT(IN) :: PI(KPROMA,KFLEVG)
REAL(KIND=JPRB), INTENT(IN) :: PR(KPROMA,KFLEVG)
REAL(KIND=JPRB), INTENT(IN) :: PS(KPROMA,KFLEVG)
REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PSNFRAC(KPROMA)
REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PHVFRAC(KPROMA)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: KDATE_NOW
REAL(KIND=JPRB), INTENT(OUT) :: PDCLBT(KPROMA,KSATSIM)
REAL(KIND=JPRB), INTENT(OUT) :: PDCSBT(KPROMA,KSATSIM)
REAL(KIND=JPRB), INTENT(OUT) :: PDCDRFL(KPROMA,KSATSIM)
REAL(KIND=JPRB), INTENT(OUT) :: PDCRRFL(KPROMA,KSATSIM)
call abor1("SATSIM should never be called with this build configuration - EXITING")
END SUBROUTINE SATSIM
