! (C) Copyright 2011- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE VDIFLCZ(YDVDF,YDVAB,YDPHLC,KIDIA, KFDIA, KLON, KLEV,&
 & PTSTEP,&
 & PLSM,&
 & PAPHI,&
 & PAPHIF, PCP, PR, PRDELP,&
 & PU0, PV0, PT0, PAPH0,&
 & PU9, PV9, PT9,&
 & PUT1,PVT1,PTT1)
use yomvert , only:&
 & tvab
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOEVDF , ONLY : TVDF
USE YOPHLC , ONLY : TPHLC
TYPE(TVDF) , INTENT(IN) :: YDVDF
TYPE(TVAB) , INTENT(IN) :: YDVAB
TYPE(TPHLC) ,INTENT(INOUT) :: YDPHLC
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PTSTEP
REAL(KIND=JPRB) ,INTENT(IN) :: PLSM(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHI(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHIF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PR(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRDELP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PU0(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PV0(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT0(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPH0(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PU9(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PV9(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT9(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUT1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVT1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTT1(KLON,KLEV)
call abor1("VDIFLCZ should never be called with this build configuration - EXITING")
END SUBROUTINE VDIFLCZ
