! (C) Copyright 2011- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE WRPHTRAJM(YDGEOMETRY,YDSIMPHL,KSTA,KEND,PTRAJ_PHYS,&
 & PUT95,PVT95,PTT95,PQT95,PQLT95,PQIT95,PSP95)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMSIMPHL, ONLY : TSIMPHL
USE YOMTRAJ , ONLY : TRAJ_PHYS_TYPE
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TSIMPHL) ,INTENT(IN) :: YDSIMPHL
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSTA
INTEGER(KIND=JPIM) ,INTENT(IN) :: KEND
TYPE (TRAJ_PHYS_TYPE),INTENT(INOUT) :: PTRAJ_PHYS
REAL(KIND=JPRB) ,INTENT(IN) :: PUT95(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PVT95(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTT95(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PQT95(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PQLT95(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PQIT95(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PSP95(YDGEOMETRY%YRDIM%NPROMA)
call abor1("WRPHTRAJM should never be called with this build configuration - EXITING")
END SUBROUTINE WRPHTRAJM
