! (C) Copyright 2011- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE WRSLTRAJ2(YDDIM,KSTA,KEND,PTRAJ_SLAG,&
 & PUT95,PVT95,PSPNLT95,PUL95,PVL95,&
 & PSPL95,PUL05,PVL05,PSPL05,&
 & PURL05,PVRL05,PURL5,PVRL5,PUSI5,PVSI5,&
 & PUT15,PVT15)
USE YOMDIM , ONLY : TDIM
USE PARKIND1 , ONLY : JPIM, JPRB
use yomtraj , only:&
 & traj_slag_type
TYPE(TDIM) , INTENT(IN) :: YDDIM
INTEGER(KIND=JPIM) , INTENT(IN) :: KSTA
INTEGER(KIND=JPIM) , INTENT(IN) :: KEND
TYPE(TRAJ_SLAG_TYPE), INTENT(INOUT) :: PTRAJ_SLAG
REAL(KIND=JPRB) , INTENT(IN) :: PUT95(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: PVT95(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: PSPNLT95(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: PUL95(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: PVL95(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: PSPL95(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: PUL05(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: PVL05(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: PSPL05(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: PURL05(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: PVRL05(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: PURL5(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: PVRL5(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: PUSI5(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: PVSI5(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: PUT15(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: PVT15(YDDIM%NPROMA)
call abor1("WRSLTRAJ2 should never be called with this build configuration - EXITING")
END SUBROUTINE WRSLTRAJ2
