! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE CONTROL_VECTORS_BASE_MIX

!   Purpose.
!   --------
!     This module contains the definition of the CONTROL_VECTOR type
!     and basic routines (allocate, deallocate).
!
!   Author.
!   -------
!     Y. Tremolet
!
!   Modifications.
!   --------------
!     Original   25-Jul-2004 Split from CONTROL_VECTORS
!     A. Deckmyn 01-Oct-2008 LAM-wavelet Jb
!     M. Fisher  15-Feb-2013 Put globals into structures. Introduce JB_CONTROL_VECTORS
!     Y. Michel, MF, June 2018 Extension of the control variable for sqrt EnVar
!     S. Massart 19-Feb-2019 Parameter optimisation
!     Y. Michel, MF, May 2019 Move LWAVELETJB TO INITCV
! ------------------------------------------------------------------

USE PARKIND1,                    ONLY : JPIM, JPRB
USE YOMHOOK,                     ONLY : LHOOK, DR_HOOK, JPHOOK
USE MPL_MODULE,                  ONLY : MPL_RANK
USE SPECTRAL_FIELDS_MOD,         ONLY : SPECTRAL_FIELD, INQ_SPEC, ALLOCATE_SPEC, DEALLOCATE_SPEC, ASSIGNMENT(=)
USE CONTROL_VECTORS_DATA_MIX,    ONLY : CONTROL_VECTOR_DATA_STRUCT
USE JB_CONTROL_VECTORS_BASE_MOD, ONLY : JB_CONTROL_VECTOR,&
 &                                      ALLOCATE_JB_CTLVEC_NODATA,&
 &                                      DEALLOCATE_JB_CTLVEC_NODATA

IMPLICIT NONE
PRIVATE
PUBLIC CONTROL_VECTOR, ALLOCATE_CTLVEC, DEALLOCATE_CTLVEC, INVERSE, CHECK

! ------------------------------------------------------------------

TYPE CONTROL_VECTOR
  LOGICAL :: LINITCV, LTOVSCV, LAM1D, LELAM, LENSCV
  REAL(KIND=JPRB), POINTER :: DATA(:) => NULL()
  INTEGER(KIND=JPIM) :: NSMAX, NMSMAX, NMODERR, NSERR, NPARA, NPECV
  INTEGER(KIND=JPIM) :: NSMAX_ENS, NMSMAX_ENS
  INTEGER(KIND=JPIM) :: NS3D, NS2D, NS1D, NVE3D, NVE2D
  INTEGER(KIND=JPIM) :: NENS
  INTEGER(KIND=JPIM) :: NSIZEL, NSIZEG, NSCALES
  INTEGER(KIND=JPIM) :: NSIZES(7)
  TYPE(JB_CONTROL_VECTOR), POINTER  :: INITCV => NULL()
  TYPE(JB_CONTROL_VECTOR), POINTER  :: ENSCV => NULL()
  REAL(KIND=JPRB), POINTER :: MODERR(:) => NULL()
  REAL(KIND=JPRB), POINTER :: TOVSCV(:) => NULL()
  REAL(KIND=JPRB), POINTER :: LAMCV (:) => NULL()
  REAL(KIND=JPRB), POINTER :: PARAMS(:) => NULL()
  REAL(KIND=JPRB), POINTER :: PECV(:) => NULL()
  LOGICAL :: LALLOC = .FALSE.
  TYPE(CONTROL_VECTOR_DATA_STRUCT), POINTER :: STRUCT => NULL()
  TYPE(CONTROL_VECTOR_DATA_STRUCT), POINTER :: STRUCT_ENS => NULL()

CONTAINS

PROCEDURE, PASS(YDCV) :: ALLOCATE_CV
PROCEDURE, PASS(YDCV) :: ALLOCATE_CV_CV
PROCEDURE, PASS(YDCV) :: CHECK_CV
PROCEDURE, PASS(YDCV1):: CHECK_CV_CV
PROCEDURE, PASS(YDCV1):: EQUIV_CV
PROCEDURE, PASS(YDCV1):: NEQUIV_CV
PROCEDURE, PASS(YDCV) :: INVERSE_CV
PROCEDURE, PASS(YDOUT):: INVERSE_CV_CV
PROCEDURE, PASS(YDCV1):: ASSIGN_CV_CV
PROCEDURE, PASS(YDCV) :: ASSIGN_CV_AR
PROCEDURE, PASS(YDCV) :: ASSIGN_AR_CV
PROCEDURE, PASS(YDCV) :: ASSIGN_SCALAR_CV
PROCEDURE, PASS(YDCV) :: DEALLOCATE_CV

GENERIC, PUBLIC :: ALLOCATE_CTLVEC   => ALLOCATE_CV, ALLOCATE_CV_CV
GENERIC, PUBLIC :: CHECK             => CHECK_CV, CHECK_CV_CV
GENERIC, PUBLIC :: OPERATOR(.EQV.)   => EQUIV_CV
GENERIC, PUBLIC :: OPERATOR(.NEQV.)  => NEQUIV_CV
GENERIC, PUBLIC :: ASSIGNMENT(=)     => ASSIGN_CV_CV, ASSIGN_SCALAR_CV, ASSIGN_AR_CV, ASSIGN_CV_AR
GENERIC, PUBLIC :: INVERSE           => INVERSE_CV, INVERSE_CV_CV
GENERIC, PUBLIC :: DEALLOCATE_CTLVEC => DEALLOCATE_CV

END TYPE CONTROL_VECTOR

! ------------------------------------------------------------------

INTERFACE ALLOCATE_CTLVEC
MODULE PROCEDURE ALLOCATE_CV, ALLOCATE_CV_CV
END INTERFACE

INTERFACE DEALLOCATE_CTLVEC
MODULE PROCEDURE DEALLOCATE_CV
END INTERFACE

INTERFACE CHECK
MODULE PROCEDURE CHECK_CV, CHECK_CV_CV
END INTERFACE

INTERFACE INVERSE
MODULE PROCEDURE INVERSE_CV, INVERSE_CV_CV
END INTERFACE

! ------------------------------------------------------------------
CONTAINS
! ------------------------------------------------------------------

SUBROUTINE ALLOCATE_CV(YDCV,KSMAX,KMSMAX,KSMAX_ENS,KMSMAX_ENS,KMERR,KSERR,KPARAM,LDINIT,LDTOVS,&
                     & LDLAM,LDLENS,KS3D,KS2D,KS1D,KENS,KE3D,KE2D,KNSCALES)

USE YOMCT0, ONLY : LALLOPR
USE CONTROL_VECTORS_DATA_MIX, ONLY : CTLVEC_STRUCT, CTLVEC_STRUCT_ENS
CLASS(CONTROL_VECTOR), INTENT(OUT) :: YDCV
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: KSMAX,KMSMAX,KMERR,KSERR,KPARAM
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: KSMAX_ENS,KMSMAX_ENS
LOGICAL, OPTIONAL, INTENT(IN) :: LDINIT,LDTOVS,LDLAM,LDLENS
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: KS3D,KS2D,KS1D,KE3D,KE2D,KNSCALES,KENS

INTEGER(KIND=JPIM) :: IBGN_IC,IEND_IC,IBGN_ME,IEND_ME,IBGN_TV,IEND_TV,&
                    & IBGN_LA,IEND_LA,IBGN_PA,IEND_PA,IBGN_PP,IEND_PP,ILEN,&
                    & IBGN_EN,IEND_EN
TYPE(SPECTRAL_FIELD) :: YLSP

! Default values
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('CONTROL_VECTORS_BASE_MIX:ALLOCATE_CV',0,ZHOOK_HANDLE)

! Default values
IF (.NOT.ASSOCIATED(CTLVEC_STRUCT)) THEN
  CALL ABOR1('Trying to allocate a control_vector, but CTLVEC_STRUCT is not initialised')
ENDIF

YDCV%STRUCT => CTLVEC_STRUCT
YDCV%STRUCT_ENS => CTLVEC_STRUCT_ENS

YDCV%LINITCV   = YDCV%STRUCT%LINITCV
YDCV%LELAM     = YDCV%STRUCT%LELAM
YDCV%NSMAX     = YDCV%STRUCT%NSMAX
YDCV%NMSMAX    = YDCV%STRUCT%NMSMAX
YDCV%LENSCV = YDCV%STRUCT%LENSCV
IF (YDCV%LENSCV) THEN
   YDCV%NSMAX_ENS     = YDCV%STRUCT_ENS%NSMAX
   YDCV%NMSMAX_ENS    = YDCV%STRUCT_ENS%NMSMAX
   YDCV%NENS=YDCV%STRUCT_ENS%NENS
ENDIF
YDCV%NMODERR   = YDCV%STRUCT%NMODERR
YDCV%NSERR     = YDCV%STRUCT%NSERR
YDCV%LTOVSCV   = YDCV%STRUCT%LTOVSCV
YDCV%LAM1D     = YDCV%STRUCT%LELAM
YDCV%NS3D      = YDCV%STRUCT%NCTL3
YDCV%NS2D      = YDCV%STRUCT%NCTL2
YDCV%NS1D      = YDCV%STRUCT%NCTL1
YDCV%NVE3D     = YDCV%STRUCT%NVE3D
YDCV%NVE2D     = YDCV%STRUCT%NVE2D
YDCV%NS1D      = YDCV%STRUCT%NCTL1
YDCV%NPARA     = YDCV%STRUCT%NPARAM
YDCV%NPECV     = YDCV%STRUCT%NPECV
IF (YDCV%STRUCT%LWAVELETJB) THEN
  YDCV%NSCALES = YDCV%STRUCT%NSCALES
ENDIF
YDCV%NSIZES(:)=0

! Check for optional arguments
IF (PRESENT(LDINIT))   YDCV%LINITCV = LDINIT
IF (PRESENT(KSMAX))    YDCV%NSMAX   = KSMAX
IF (PRESENT(KMSMAX))   YDCV%NMSMAX  = KMSMAX
IF (PRESENT(KSMAX_ENS))    YDCV%NSMAX_ENS   = KSMAX_ENS
IF (PRESENT(KMSMAX_ENS))   YDCV%NMSMAX_ENS  = KMSMAX_ENS
IF (PRESENT(KMERR))    YDCV%NMODERR = KMERR
IF (PRESENT(KSERR))    YDCV%NSERR   = KSERR
IF (PRESENT(LDTOVS))   YDCV%LTOVSCV = LDTOVS
IF (PRESENT(LDLAM ))   YDCV%LAM1D   = LDLAM
IF (PRESENT(KS3D))     YDCV%NS3D    = KS3D
IF (PRESENT(KS2D))     YDCV%NS2D    = KS2D
IF (PRESENT(KS1D))     YDCV%NS1D    = KS1D
IF (PRESENT(KE3D))     YDCV%NVE3D   = KE3D
IF (PRESENT(KE2D))     YDCV%NVE2D   = KE2D
IF (PRESENT(KPARAM))   YDCV%NPARA   = KPARAM
IF (PRESENT(KNSCALES)) YDCV%NSCALES = KNSCALES
IF (PRESENT(LDLENS)) YDCV%LENSCV  = LDLENS
IF (PRESENT(KENS))  YDCV%NENS    = KENS

!cf To avoid stupid array bound violation
IF (YDCV%NS1D==0) YDCV%LAM1D=.FALSE.

IF (YDCV%LINITCV) THEN
  ALLOCATE(YDCV%INITCV)
  ! Setup Jb control vector, but don't allocate ydcv%initcv%data
  CALL ALLOCATE_JB_CTLVEC_NODATA(YDCV%INITCV,YDCV%NSMAX,YDCV%NMSMAX,&
                              &  YDCV%NS3D,YDCV%NS2D,YDCV%NS1D,YDCV%NSCALES,LLENS=.FALSE.)

  ! Reserve space in yd%data for the Jb control vector
  YDCV%NSIZEL=YDCV%INITCV%NSIZEL
  YDCV%NSIZEG=YDCV%INITCV%NSIZEG
  IBGN_IC = 1
  IEND_IC = YDCV%INITCV%NSIZEL
  YDCV%NSIZES(1)=YDCV%INITCV%NSIZEG
ELSE
  YDCV%NSIZEL=0
  YDCV%NSIZEG=0
ENDIF

IF (YDCV%LENSCV) THEN
   ALLOCATE(YDCV%ENSCV)
   ! Setup Ens-Jb control vector, but don't allocate ydcv%enscv%data
   CALL ALLOCATE_JB_CTLVEC_NODATA(YDCV%ENSCV,YDCV%NSMAX_ENS,YDCV%NMSMAX_ENS, &
        &  YDCV%NENS,YDCV%NENS,YDCV%NS1D,YDCV%NSCALES,LLENS=.TRUE.)
   ! Reserve space in yd%data for the Ens-Jb control vector
   ILEN = YDCV%ENSCV%NSIZEL
   IBGN_EN = YDCV%NSIZEL + 1
   IEND_EN = YDCV%NSIZEL + ILEN
   YDCV%NSIZEL=YDCV%NSIZEL + ILEN
   ILEN = YDCV%ENSCV%NSIZEG
   YDCV%NSIZEG=YDCV%NSIZEG + ILEN
   YDCV%NSIZES(2)=YDCV%ENSCV%NSIZEG
ENDIF

IF (YDCV%NMODERR>0) THEN

  CALL INQ_SPEC(YLSP,YDCV%STRUCT%NFLEVL,YDCV%STRUCT%NFLEVG,&
        & YDCV%STRUCT%NUMP,YDCV%STRUCT%MYMS,YDCV%NSERR,YDCV%NSERR,&
        & YDCV%STRUCT%NALLMS,YDCV%STRUCT%NPTRMS,YDCV%STRUCT%NUMLL,&
        & YDCV%STRUCT%NPTRLL,YDCV%STRUCT%NPSURF,YDCV%NVE3D,YDCV%NVE2D)

  ILEN = YDCV%NMODERR * YLSP%NSPSIZEL
  IBGN_ME = YDCV%NSIZEL + 1
  IEND_ME = YDCV%NSIZEL + ILEN
  YDCV%NSIZEL = YDCV%NSIZEL + ILEN
  ILEN = YDCV%NMODERR * YLSP%NSPSIZEG
  YDCV%NSIZEG = YDCV%NSIZEG + ILEN
  YDCV%NSIZES(3) = ILEN
  CALL DEALLOCATE_SPEC(YLSP)
ENDIF

IF (YDCV%LTOVSCV) THEN
  ILEN = YDCV%STRUCT%NLENTOVSCV*YDCV%STRUCT%NVATOVV
  IBGN_TV = YDCV%NSIZEL + 1
  IEND_TV = YDCV%NSIZEL + ILEN
  YDCV%NSIZEL = YDCV%NSIZEL + ILEN
  YDCV%NSIZEG = YDCV%NSIZEG + YDCV%STRUCT%NLENTOVSCVG*YDCV%STRUCT%NVATOVV
  YDCV%NSIZES(4)=YDCV%STRUCT%NLENTOVSCVG*YDCV%STRUCT%NVATOVV
ENDIF

IF (YDCV%LAM1D) THEN
  ILEN=YDCV%STRUCT%NFLEVL*YDCV%NS1D
  IBGN_LA = YDCV%NSIZEL + 1
  IEND_LA = YDCV%NSIZEL + ILEN
  YDCV%NSIZEL = YDCV%NSIZEL + ILEN
  YDCV%NSIZEG = YDCV%NSIZEG + YDCV%STRUCT%NFLEVG*YDCV%NS1D
  YDCV%NSIZES(5)=YDCV%STRUCT%NFLEVG*YDCV%NS1D
ENDIF

IF (YDCV%NPARA>0) THEN
  IBGN_PA = YDCV%NSIZEL + 1
  IEND_PA = YDCV%NSIZEL + YDCV%NPARA
  YDCV%NSIZEL = YDCV%NSIZEL + YDCV%NPARA
  YDCV%NSIZEG = YDCV%NSIZEG + YDCV%NPARA
  YDCV%NSIZES(6)=YDCV%NPARA
ENDIF

IF (YDCV%NPECV>0) THEN
  IBGN_PP = YDCV%NSIZEL + 1
  IEND_PP = YDCV%NSIZEL + YDCV%NPECV
  YDCV%NSIZEL = YDCV%NSIZEL + YDCV%NPECV
  YDCV%NSIZEG = YDCV%NSIZEG + YDCV%NPECV
  YDCV%NSIZES(7)=YDCV%NPECV
ENDIF

ALLOCATE(YDCV%DATA(1:YDCV%NSIZEL))
YDCV%LALLOC = .TRUE.

IF (YDCV%LINITCV  ) THEN
  YDCV%INITCV%DATA => YDCV%DATA(IBGN_IC:IEND_IC)
  YDCV%INITCV%LALLOC = .TRUE.
ENDIF

IF (YDCV%LENSCV  ) THEN
   YDCV%ENSCV%DATA => YDCV%DATA(IBGN_EN:IEND_EN)
   YDCV%ENSCV%LALLOC = .TRUE.
ENDIF

IF (YDCV%NMODERR>0) YDCV%MODERR => YDCV%DATA(IBGN_ME:IEND_ME)
IF (YDCV%LTOVSCV  ) YDCV%TOVSCV => YDCV%DATA(IBGN_TV:IEND_TV)
IF (YDCV%LAM1D    ) YDCV%LAMCV  => YDCV%DATA(IBGN_LA:IEND_LA)
IF (YDCV%NPARA>0  ) YDCV%PARAMS => YDCV%DATA(IBGN_PA:IEND_PA)
IF (YDCV%NPECV>0  ) YDCV%PECV   => YDCV%DATA(IBGN_PP:IEND_PP)

IF (LALLOPR .AND. MPL_RANK <= 1) THEN
  WRITE(*,*)'CONTROL_VECTORS:ALLOCATE_CV size local, global = ', YDCV%NSIZEL, YDCV%NSIZEG
ENDIF

IF (LHOOK) CALL DR_HOOK('CONTROL_VECTORS_BASE_MIX:ALLOCATE_CV',1,ZHOOK_HANDLE)
END SUBROUTINE ALLOCATE_CV

! ------------------------------------------------------------------

SUBROUTINE ALLOCATE_CV_CV(YDCV,YDIN)
CLASS(CONTROL_VECTOR), INTENT(OUT) :: YDCV
TYPE(CONTROL_VECTOR), INTENT(IN)  :: YDIN
LOGICAL :: LLENS

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('CONTROL_VECTORS_BASE_MIX:ALLOCATE_CV_CV',0,ZHOOK_HANDLE)
LLENS=YDIN%LENSCV

CALL ALLOCATE_CV(YDCV, KSMAX=YDIN%NSMAX, KSERR=YDIN%NSERR,LDLENS=LLENS)

IF (LHOOK) CALL DR_HOOK('CONTROL_VECTORS_BASE_MIX:ALLOCATE_CV_CV',1,ZHOOK_HANDLE)
END SUBROUTINE ALLOCATE_CV_CV

! ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_CV(YDCV)
CLASS(CONTROL_VECTOR), INTENT(INOUT) :: YDCV

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('CONTROL_VECTORS_BASE_MIX:DEALLOCATE_CV',0,ZHOOK_HANDLE)
IF (YDCV%LINITCV) THEN
  CALL DEALLOCATE_JB_CTLVEC_NODATA (YDCV%INITCV)
  DEALLOCATE(YDCV%INITCV)
  NULLIFY(YDCV%INITCV)
ENDIF

IF (YDCV%LENSCV) THEN
   CALL DEALLOCATE_JB_CTLVEC_NODATA (YDCV%ENSCV)
   DEALLOCATE(YDCV%ENSCV)
   NULLIFY(YDCV%ENSCV)
ENDIF

IF (ASSOCIATED(YDCV%MODERR)) NULLIFY(YDCV%MODERR)
IF (ASSOCIATED(YDCV%TOVSCV)) NULLIFY(YDCV%TOVSCV)
IF (ASSOCIATED(YDCV%LAMCV )) NULLIFY(YDCV%LAMCV )
IF (ASSOCIATED(YDCV%PARAMS)) NULLIFY(YDCV%PARAMS)
IF (ASSOCIATED(YDCV%PECV))   NULLIFY(YDCV%PECV)
IF (ASSOCIATED(YDCV%DATA)) DEALLOCATE(YDCV%DATA)
YDCV%LALLOC = .FALSE.

NULLIFY(YDCV%STRUCT)

IF (LHOOK) CALL DR_HOOK('CONTROL_VECTORS_BASE_MIX:DEALLOCATE_CV',1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_CV

! ------------------------------------------------------------------

SUBROUTINE CHECK_CV(YDCV)
CLASS(CONTROL_VECTOR), INTENT(IN) :: YDCV

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('CONTROL_VECTORS_BASE_MIX:CHECK_CV',0,ZHOOK_HANDLE)
IF (.NOT.(YDCV%LALLOC)) THEN
  CALL ABOR1('Control vector not allocated')
ENDIF
!yt the following is temporary, lalloc can be removed after
!yt this has been tested.
IF (ASSOCIATED(YDCV%DATA) .AND. .NOT.(YDCV%LALLOC)) THEN
  CALL ABOR1('Control vector associated but not lalloc')
ENDIF
IF (.NOT.ASSOCIATED(YDCV%DATA) .AND. YDCV%LALLOC) THEN
  CALL ABOR1('Control vector lalloc but not associated')
ENDIF

IF (LHOOK) CALL DR_HOOK('CONTROL_VECTORS_BASE_MIX:CHECK_CV',1,ZHOOK_HANDLE)
END SUBROUTINE CHECK_CV

! ------------------------------------------------------------------

SUBROUTINE CHECK_CV_CV(YDCV1,YDCV2)
CLASS(CONTROL_VECTOR), INTENT(IN) :: YDCV1
CLASS(CONTROL_VECTOR), INTENT(IN) :: YDCV2

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('CONTROL_VECTORS_BASE_MIX:CHECK_CV_CV',0,ZHOOK_HANDLE)
IF (.NOT.(YDCV1%LALLOC .AND. YDCV2%LALLOC)) THEN
  CALL ABOR1('Control vectors not allocated')
ENDIF
IF (NEQUIV_CV(YDCV1,YDCV2)) THEN
  CALL ABOR1('Control vectors are incompatible')
ENDIF

IF ((YDCV1%NSMAX/=YDCV2%NSMAX) .OR. (YDCV1%NSERR/=YDCV2%NSERR) .OR.&
 &((YDCV1%NMSMAX/=YDCV2%NMSMAX).AND.(YDCV1%LELAM))) THEN
  CALL ABOR1('Control vectors have different resolution')
ENDIF

IF (YDCV1%LENSCV .AND. YDCV2%LENSCV) THEN
  IF (YDCV1%NENS/=YDCV2%NENS) THEN
    CALL ABOR1('Control vectors have different ens. size')
  ENDIF
ENDIF
IF (LHOOK) CALL DR_HOOK('CONTROL_VECTORS_BASE_MIX:CHECK_CV_CV',1,ZHOOK_HANDLE)
END SUBROUTINE CHECK_CV_CV

! ------------------------------------------------------------------

LOGICAL FUNCTION EQUIV_CV(YDCV1,YDCV2)
CLASS(CONTROL_VECTOR), INTENT(IN) :: YDCV1
CLASS(CONTROL_VECTOR), INTENT(IN) :: YDCV2
LOGICAL :: LL

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('CONTROL_VECTORS_BASE_MIX:EQUIV_CV',0,ZHOOK_HANDLE)
LL = .TRUE.
LL = LL .AND. (YDCV1%LINITCV.EQV.YDCV2%LINITCV)
LL = LL .AND. (YDCV1%LENSCV.EQV.YDCV2%LENSCV)
LL = LL .AND. (YDCV1%LTOVSCV.EQV.YDCV2%LTOVSCV)
LL = LL .AND. (YDCV1%LAM1D  .EQV.YDCV2%LAM1D  )

LL = LL .AND. (YDCV1%NMODERR== YDCV2%NMODERR)
LL = LL .AND. (YDCV1%NS3D   == YDCV2%NS3D)
LL = LL .AND. (YDCV1%NS2D   == YDCV2%NS2D)
LL = LL .AND. (YDCV1%NS1D   == YDCV2%NS1D)
LL = LL .AND. (YDCV1%NVE3D  == YDCV2%NVE3D)
LL = LL .AND. (YDCV1%NVE2D  == YDCV2%NVE2D)
LL = LL .AND. (YDCV1%NPARA  == YDCV2%NPARA)
LL = LL .AND. (YDCV1%NPECV  == YDCV2%NPECV)
IF (YDCV1%LENSCV) THEN
  LL = LL .AND. (YDCV1%NENS  == YDCV2%NENS)
ENDIF

EQUIV_CV=LL
IF (LHOOK) CALL DR_HOOK('CONTROL_VECTORS_BASE_MIX:EQUIV_CV',1,ZHOOK_HANDLE)
END FUNCTION EQUIV_CV

! ------------------------------------------------------------------

LOGICAL FUNCTION NEQUIV_CV(YDCV1,YDCV2)
CLASS(CONTROL_VECTOR), INTENT(IN) :: YDCV1
CLASS(CONTROL_VECTOR), INTENT(IN) :: YDCV2

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('CONTROL_VECTORS_BASE_MIX:NEQUIV_CV',0,ZHOOK_HANDLE)
NEQUIV_CV = .NOT. EQUIV_CV(YDCV1,YDCV2)

IF (LHOOK) CALL DR_HOOK('CONTROL_VECTORS_BASE_MIX:NEQUIV_CV',1,ZHOOK_HANDLE)
END FUNCTION NEQUIV_CV

! ------------------------------------------------------------------
! ------------------------------------------------------------------

SUBROUTINE ASSIGN_CV_CV(YDCV1,YDCV2)
CLASS(CONTROL_VECTOR), INTENT(INOUT) :: YDCV1
TYPE(CONTROL_VECTOR), INTENT(IN)    :: YDCV2
TYPE(SPECTRAL_FIELD) :: YLSP1, YLSP2
LOGICAL :: LL_SAME_INIT, LL_SAME_ENS, LL_SAME_MODERR
INTEGER(KIND=JPIM) :: ILEN,I1,I2,IL1,IL2,JJ,J,II
INTEGER(KIND=JPIM), ALLOCATABLE :: IGRB(:)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('CONTROL_VECTORS_OPER_MOD:ASSIGN_CV_CV',0,ZHOOK_HANDLE)
CALL CHECK_CV(YDCV1)
CALL CHECK_CV(YDCV2)
IF (NEQUIV_CV(YDCV1,YDCV2)) THEN
  CALL ABOR1('Control vectors are incompatible')
ENDIF

LL_SAME_INIT = .TRUE.
IF (YDCV1%LINITCV) THEN
  IF (YDCV1%INITCV%LWAVELETJB) THEN
    LL_SAME_INIT = YDCV1%NSCALES==YDCV2%NSCALES.AND.(YDCV1%NSERR==YDCV2%NSERR)
  ELSE
    LL_SAME_INIT = YDCV1%NSMAX==YDCV2%NSMAX .AND. (YDCV1%NSERR==YDCV2%NSERR)
  ENDIF
ENDIF

IF (YDCV1%LENSCV) THEN
   LL_SAME_ENS = (YDCV1%NENS==YDCV2%NENS .AND. YDCV1%NSMAX_ENS==YDCV2%NSMAX_ENS) ! detects change of resolution
ENDIF

IF (YDCV1%LELAM) THEN
  LL_SAME_INIT = LL_SAME_INIT .AND. (YDCV1%NMSMAX==YDCV2%NMSMAX)
ENDIF

IF (YDCV1%NMODERR>0) THEN
  LL_SAME_MODERR = (YDCV1%NSERR==YDCV2%NSERR)
ELSE
  LL_SAME_MODERR = .TRUE.
ENDIF

IF (LL_SAME_INIT .AND. LL_SAME_MODERR .AND. LL_SAME_ENS) THEN
  CALL GSTATS(1460,0)
!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(J)
  DO J=1,SIZE(YDCV1%DATA)
    YDCV1%DATA(J) = YDCV2%DATA(J)
  ENDDO
!$OMP END PARALLEL DO
  CALL GSTATS(1460,1)
ELSE
  IF (YDCV1%LINITCV) THEN
    IF (LL_SAME_INIT) THEN
      YDCV1%INITCV%DATA(:) = YDCV2%INITCV%DATA(:)
    ELSEIF (YDCV1%INITCV%LWAVELETJB) THEN
      IF (YDCV1%LELAM) CALL  ABOR1('LELAM-wavelets not implemented here.')
!---- NB: The finest scale of the lower-resolution control vector (ydcv2 or ydcv1)
!     has a different grid than the corresponding scale of higher-resolution
!     control vector (ydcv1 or ydcv2). Ideally,
!     we should use the spherical transform to re-grid this scale. But,
!     for now we just zero it in ydcv1.

      ! Input control vector YDCV2 at lower resolution, zero finest input scale
      IF (YDCV1%NSCALES > YDCV2%NSCALES) THEN
        ILEN=YDCV1%INITCV%IBGN_SCALE(YDCV1%NSCALES-YDCV2%NSCALES+2)-1
        YDCV1%INITCV%DATA(1:ILEN) = 0.0_JPRB
        IF (  SIZE(YDCV1%INITCV%DATA(ILEN+1:)) &
          & /=SIZE(YDCV2%INITCV%DATA(YDCV2%INITCV%IBGN_SCALE(2):))) THEN
          WRITE(0,*)'size mismatch: ',SIZE(YDCV1%INITCV%DATA(ILEN+1:)), &
                   &                  SIZE(YDCV2%INITCV%DATA(YDCV2%INITCV%IBGN_SCALE(2):))
          WRITE(0,*)'ydcv1%initcv%ibgn_scale=',YDCV1%INITCV%IBGN_SCALE
          WRITE(0,*)'ydcv2%initcv%ibgn_scale=',YDCV2%INITCV%IBGN_SCALE
          CALL ABOR1 ('size mismatch')
        ENDIF
        YDCV1%INITCV%DATA(ILEN+1:) = YDCV2%INITCV%DATA(YDCV2%INITCV%IBGN_SCALE(2):)
      ! Input control vector YDCV2 at higher resolution, zero input scales up
      ! to and including the finest scale of YDC1
      ELSEIF (YDCV1%NSCALES < YDCV2%NSCALES) THEN
        ILEN=YDCV2%INITCV%IBGN_SCALE(YDCV2%NSCALES-YDCV1%NSCALES+2)-1
        YDCV1%INITCV%DATA(1:YDCV1%INITCV%IBGN_SCALE(2)-1) = 0.0_JPRB
        IF (  SIZE(YDCV2%INITCV%DATA(ILEN+1:)) &
          & /=SIZE(YDCV1%INITCV%DATA(YDCV1%INITCV%IBGN_SCALE(2):))) THEN
          WRITE(0,*)'size mismatch: ',SIZE(YDCV2%INITCV%DATA(ILEN+1:)), &
                   &                  SIZE(YDCV1%INITCV%DATA(YDCV1%INITCV%IBGN_SCALE(2):))
          WRITE(0,*)'ydcv1%initcv%ibgn_scale=',YDCV1%INITCV%IBGN_SCALE
          WRITE(0,*)'ydcv2%initcv%ibgn_scale=',YDCV2%INITCV%IBGN_SCALE
          CALL ABOR1 ('size mismatch')
        ENDIF
        YDCV1%INITCV%DATA(YDCV1%INITCV%IBGN_SCALE(2):) = YDCV2%INITCV%DATA(ILEN+1:)
      ELSE
        ! Input control vector YDCV2 of same resolution
        YDCV1%INITCV%DATA(:) = YDCV2%INITCV%DATA(:)
      ENDIF
    ELSE
      CALL ALLOCATE_SPEC(YLSP1,YDCV1%STRUCT%NFLEVL,YDCV1%STRUCT%NFLEVG, &
        & YDCV1%STRUCT%NUMP,YDCV1%STRUCT%MYMS,YDCV1%NSMAX,YDCV1%NMSMAX, &
        & YDCV1%STRUCT%NALLMS,YDCV1%STRUCT%NPTRMS,YDCV1%STRUCT%NUMLL, &
        & YDCV1%STRUCT%NPTRLL, YDCV1%STRUCT%NPSURF,YDCV1%NS3D,YDCV1%NS2D, &
        & YDCV1%STRUCT%NGRB)
      CALL ALLOCATE_SPEC(YLSP2,YDCV2%STRUCT%NFLEVL,YDCV2%STRUCT%NFLEVG, &
        & YDCV2%STRUCT%NUMP,YDCV2%STRUCT%MYMS,YDCV2%NSMAX,YDCV2%NMSMAX, &
        & YDCV2%STRUCT%NALLMS,YDCV2%STRUCT%NPTRMS,YDCV2%STRUCT%NUMLL, &
        & YDCV2%STRUCT%NPTRLL,YDCV2%STRUCT%NPSURF,YDCV2%NS3D,YDCV2%NS2D, &
        & YDCV1%STRUCT%NGRB)
      YLSP2=YDCV2%INITCV%DATA(:)
      YLSP1=YLSP2        ! Spectral_field type does change of resolution
      YDCV1%INITCV%DATA(:)=YLSP1
      CALL DEALLOCATE_SPEC(YLSP1)
      CALL DEALLOCATE_SPEC(YLSP2)
    ENDIF
  ENDIF

  IF (YDCV1%LENSCV) THEN
     IF (LL_SAME_ENS) THEN
        YDCV1%ENSCV%DATA(:) = YDCV2%ENSCV%DATA(:)
     ELSE
        IF (YDCV1%NENS /= YDCV2%NENS) CALL ABOR1("ENSEMBLE SIZE MISMATCH")
        WRITE(0,*)'CONTROL_VECTORS_OPER_MOD:ASSIGN_CV_CV::Spectral_field type does change of resolution'
        ALLOCATE(IGRB(2*YDCV1%NENS))
        DO II=1,2*YDCV1%NENS
           IGRB(II)=1000+II
        ENDDO
        CALL ALLOCATE_SPEC(YLSP1,YDCV1%STRUCT_ENS%NFLEVL,YDCV1%STRUCT_ENS%NFLEVG, &
             & YDCV1%STRUCT_ENS%NUMP,YDCV1%STRUCT_ENS%MYMS,YDCV1%NSMAX_ENS,YDCV1%NMSMAX_ENS, &
             & YDCV1%STRUCT_ENS%NALLMS,YDCV1%STRUCT_ENS%NPTRMS,YDCV1%STRUCT_ENS%NUMLL, &
             & YDCV1%STRUCT_ENS%NPTRLL, YDCV1%STRUCT_ENS%NPSURF,YDCV1%NENS,YDCV1%NENS,IGRB)
        CALL ALLOCATE_SPEC(YLSP2,YDCV2%STRUCT_ENS%NFLEVL,YDCV2%STRUCT_ENS%NFLEVG, &
             & YDCV2%STRUCT_ENS%NUMP,YDCV2%STRUCT_ENS%MYMS,YDCV2%NSMAX_ENS,YDCV2%NMSMAX_ENS, &
             & YDCV2%STRUCT_ENS%NALLMS,YDCV2%STRUCT_ENS%NPTRMS,YDCV2%STRUCT_ENS%NUMLL, &
             & YDCV2%STRUCT_ENS%NPTRLL,YDCV2%STRUCT_ENS%NPSURF,YDCV2%NENS,YDCV2%NENS,IGRB)
        YLSP2=YDCV2%ENSCV%DATA(:)
        YLSP1=YLSP2        ! Spectral_field type does change of resolution
        YDCV1%ENSCV%DATA(:)=YLSP1
        CALL DEALLOCATE_SPEC(YLSP1)
        CALL DEALLOCATE_SPEC(YLSP2)
        DEALLOCATE(IGRB)
     ENDIF
  ENDIF

  IF (YDCV1%NMODERR>0) THEN
    IF (LL_SAME_MODERR) THEN
      YDCV1%MODERR(:) = YDCV2%MODERR(:)
    ELSE
      CALL ALLOCATE_SPEC(YLSP1,YDCV1%STRUCT%NFLEVL,YDCV1%STRUCT%NFLEVG, &
       & YDCV1%STRUCT%NUMP,YDCV1%STRUCT%MYMS,YDCV1%NSERR,YDCV1%NSERR, &
       & YDCV1%STRUCT%NALLMS,YDCV1%STRUCT%NPTRMS,YDCV1%STRUCT%NUMLL, &
       & YDCV1%STRUCT%NPTRLL,YDCV1%STRUCT%NPSURF,YDCV1%NVE3D,YDCV1%NVE2D, &
       & YDCV1%STRUCT%NGRBE)
      CALL ALLOCATE_SPEC(YLSP2,YDCV2%STRUCT%NFLEVL,YDCV2%STRUCT%NFLEVG, &
       & YDCV2%STRUCT%NUMP,YDCV2%STRUCT%MYMS,YDCV2%NSERR,YDCV2%NSERR, &
       & YDCV2%STRUCT%NALLMS,YDCV2%STRUCT%NPTRMS,YDCV2%STRUCT%NUMLL, &
       & YDCV2%STRUCT%NPTRLL,YDCV2%STRUCT%NPSURF,YDCV2%NVE3D,YDCV2%NVE2D, &
       & YDCV1%STRUCT%NGRBE)
      IL1=YLSP1%NSPSIZEL
      IL2=YLSP2%NSPSIZEL
      DO JJ=1,YDCV1%NMODERR
        I1=(JJ-1)*IL1
        I2=(JJ-1)*IL2
        YLSP2=YDCV2%MODERR(I2+1:I2+IL2)
        YLSP1=YLSP2      ! Spectral_field type does change of resolution
        YDCV1%MODERR(I1+1:I1+IL1)=YLSP1
      ENDDO
      CALL DEALLOCATE_SPEC(YLSP1)
      CALL DEALLOCATE_SPEC(YLSP2)
    ENDIF
  ENDIF
  IF (YDCV1%LTOVSCV) THEN
    YDCV1%TOVSCV(:) = YDCV2%TOVSCV(:)
  ENDIF
  IF (YDCV1%LAM1D) THEN
    YDCV1%LAMCV(:) = YDCV2%LAMCV(:)
  ENDIF
  IF (YDCV1%NPARA>0) THEN
    YDCV1%PARAMS(:) = YDCV2%PARAMS(:)
  ENDIF
  IF (YDCV1%NPECV>0) THEN
    YDCV1%PECV(:) = YDCV2%PECV(:)
  ENDIF

ENDIF

IF (LHOOK) CALL DR_HOOK('CONTROL_VECTORS_OPER_MOD:ASSIGN_CV_CV',1,ZHOOK_HANDLE)
END SUBROUTINE ASSIGN_CV_CV

! ------------------------------------------------------------------

SUBROUTINE ASSIGN_SCALAR_CV(YDCV,PSCALAR)
CLASS(CONTROL_VECTOR), INTENT(INOUT) :: YDCV
REAL(KIND=JPRB), INTENT(IN) :: PSCALAR

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('CONTROL_VECTORS_OPER_MOD:ASSIGN_SCALAR_CV',0,ZHOOK_HANDLE)
CALL CHECK_CV(YDCV)
YDCV%DATA = PSCALAR

IF (LHOOK) CALL DR_HOOK('CONTROL_VECTORS_OPER_MOD:ASSIGN_SCALAR_CV',1,ZHOOK_HANDLE)
END SUBROUTINE ASSIGN_SCALAR_CV

! ------------------------------------------------------------------

SUBROUTINE ASSIGN_AR_CV(YDCV,PVEC)
CLASS(CONTROL_VECTOR), INTENT(INOUT) :: YDCV
REAL(KIND=JPRB), INTENT(IN) :: PVEC(:)
INTEGER(KIND=JPIM) :: ILEN,IOFF,JF,II,JJ,JL,IL,IBGN,IEND,IGPTOTG,JSCALE,JA,JB
INTEGER(KIND=JPIM), ALLOCATABLE :: IGRB(:)
TYPE(SPECTRAL_FIELD) :: YLSP

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('CONTROL_VECTORS_OPER_MOD:ASSIGN_AR_CV',0,ZHOOK_HANDLE)
CALL CHECK_CV(YDCV)

IF (SIZE(PVEC) == YDCV%NSIZEL) THEN
  YDCV%DATA = PVEC
ELSEIF (SIZE(PVEC) == YDCV%NSIZEG) THEN
  IF (YDCV%LINITCV) THEN
    IF (.NOT.YDCV%INITCV%LWAVELETJB) THEN
      CALL ALLOCATE_SPEC(YLSP,YDCV%STRUCT%NFLEVL,YDCV%STRUCT%NFLEVG, &
       & YDCV%STRUCT%NUMP,YDCV%STRUCT%MYMS,YDCV%NSMAX,YDCV%NMSMAX, &
       & YDCV%STRUCT%NALLMS,YDCV%STRUCT%NPTRMS,YDCV%STRUCT%NUMLL, &
       & YDCV%STRUCT%NPTRLL,YDCV%STRUCT%NPSURF,YDCV%NS3D,YDCV%NS2D,&
       & YDCV%STRUCT%NGRB)
      ILEN=YLSP%NSPSIZEG
      YLSP=PVEC(1:ILEN)
      YDCV%INITCV%DATA(:)=YLSP
      IOFF=ILEN
      CALL DEALLOCATE_SPEC(YLSP)
    ELSE
      IGPTOTG=0
      DO JSCALE=1,YDCV%NSCALES
        DO JA=1,YDCV%STRUCT%N_REGIONS_NS
          DO JB=1,YDCV%STRUCT%N_REGIONS(JA)
            IF (JA==YDCV%STRUCT%MY_REGION_NS .AND. JB==YDCV%STRUCT%MY_REGION_EW) THEN
              IBGN=YDCV%INITCV%IBGN_SCALE(JSCALE)
              ILEN=YDCV%STRUCT%NPROMA*(YDCV%STRUCT%NFLEVG*YDCV%NS3D+YDCV%NS2D) &
                       & *YDCV%STRUCT%NBLOCKSL(JSCALE+YDCV%STRUCT%NSCALES-YDCV%NSCALES)
              IEND=IBGN+ILEN-1
              YDCV%INITCV%DATA(IBGN:IEND) = PVEC(IGPTOTG+1:IGPTOTG+ILEN)
            ENDIF
            IGPTOTG=IGPTOTG+YDCV%STRUCT%NGPTOTL(JSCALE+YDCV%STRUCT%NSCALES-YDCV%NSCALES,JA,JB)
          ENDDO
        ENDDO
      ENDDO
      IF (IGPTOTG /= SUM(YDCV%STRUCT%NGPTOTG(1+YDCV%STRUCT%NSCALES-YDCV%NSCALES:))) &
        & CALL ABOR1 ('assign_ar_cv: indexing problem')
      IOFF = IGPTOTG
    ENDIF
  ENDIF

  IF (YDCV%LENSCV) THEN
     ALLOCATE(IGRB(2*YDCV%NENS))
     DO II=1,2*YDCV%NENS
        IGRB(II)=1000+II
     ENDDO
     CALL ALLOCATE_SPEC(YLSP,YDCV%STRUCT_ENS%NFLEVL,YDCV%STRUCT_ENS%NFLEVG, &
          & YDCV%STRUCT_ENS%NUMP,YDCV%STRUCT_ENS%MYMS,YDCV%NSMAX_ENS,YDCV%NMSMAX_ENS, &
          & YDCV%STRUCT_ENS%NALLMS,YDCV%STRUCT_ENS%NPTRMS,YDCV%STRUCT_ENS%NUMLL, &
          & YDCV%STRUCT_ENS%NPTRLL,YDCV%STRUCT_ENS%NPSURF,YDCV%NENS,YDCV%NENS,IGRB)
     ILEN=YLSP%NSPSIZEG
     YLSP=PVEC(1:ILEN)
     YDCV%ENSCV%DATA(:)=YLSP
     IOFF=ILEN
     CALL DEALLOCATE_SPEC(YLSP)
     DEALLOCATE(IGRB)
  ENDIF

  IF (YDCV%NMODERR>0) THEN
    CALL ALLOCATE_SPEC(YLSP,YDCV%STRUCT%NFLEVL,YDCV%STRUCT%NFLEVG, &
      & YDCV%STRUCT%NUMP,YDCV%STRUCT%MYMS,YDCV%NSERR,YDCV%NSERR, &
      & YDCV%STRUCT%NALLMS,YDCV%STRUCT%NPTRMS,YDCV%STRUCT%NUMLL, &
      & YDCV%STRUCT%NPTRLL,YDCV%STRUCT%NPSURF,YDCV%NVE3D,YDCV%NVE2D, &
      & YDCV%STRUCT%NGRBE)
    ILEN=YLSP%NSPSIZEG
    IL=YLSP%NSPSIZEL
    DO JJ=1,YDCV%NMODERR
      II=(JJ-1)*IL
      YLSP=PVEC(IOFF+1:IOFF+ILEN)
      YDCV%MODERR(II+1:II+IL)=YLSP
      IOFF=IOFF+ILEN
    ENDDO
    CALL DEALLOCATE_SPEC(YLSP)
  ENDIF
  IF (YDCV%LTOVSCV) THEN
    JL=0
    DO JF=1,YDCV%STRUCT%NVATOVV
      DO JJ=1,YDCV%STRUCT%NLENTOVSCV
        JL=JL+1
        YDCV%TOVSCV(JL)=PVEC(IOFF+YDCV%STRUCT%MYTOVOFF+JJ)
      ENDDO
      IOFF=IOFF+YDCV%STRUCT%NLENTOVSCVG
    ENDDO
  ENDIF

  IF (YDCV%LAM1D) THEN
    JJ=0
    DO JF=1,YDCV%NS1D
      DO JL=1,YDCV%STRUCT%NFLEVL
        IL=YDCV%STRUCT%MYLEVS(JL)
        JJ=JJ+1
        YDCV%LAMCV(JJ)=PVEC(IOFF+IL)
      ENDDO
      IOFF=IOFF+YDCV%STRUCT%NFLEVG
    ENDDO
  ENDIF
  IF (YDCV%NPARA>0) THEN
    DO JF=1,YDCV%NPARA
      YDCV%PARAMS(JF)=PVEC(IOFF+JF)
    ENDDO
    IOFF=IOFF+YDCV%NPARA
  ENDIF
  IF (YDCV%NPECV>0) THEN
    DO JF=1,YDCV%NPECV
      YDCV%PECV(JF)=PVEC(IOFF+JF)
    ENDDO
    IOFF=IOFF+YDCV%NPECV
  ENDIF
ELSE
  CALL ABOR1('Error: cannot assign array to control vector')
ENDIF

IF (LHOOK) CALL DR_HOOK('CONTROL_VECTORS_OPER_MOD:ASSIGN_AR_CV',1,ZHOOK_HANDLE)
END SUBROUTINE ASSIGN_AR_CV

! ------------------------------------------------------------------

SUBROUTINE ASSIGN_CV_AR(PVEC,YDCV)
REAL(KIND=JPRB), INTENT(OUT) :: PVEC(:)
CLASS(CONTROL_VECTOR), INTENT(IN) :: YDCV

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('CONTROL_VECTORS_OPER_MOD:ASSIGN_CV_AR',0,ZHOOK_HANDLE)
CALL CHECK_CV(YDCV)
IF (SIZE(PVEC) == YDCV%NSIZEL) THEN
  PVEC = YDCV%DATA
ELSEIF (SIZE(PVEC) == YDCV%NSIZEG) THEN
!  This case has to come after the preceeding one so that it isn't
!  executed if running on one processor.
  CALL ABOR1('Assign vector to global array would be very expensive')
ELSE
  CALL ABOR1('Error: cannot assign control vector to array')
ENDIF

IF (LHOOK) CALL DR_HOOK('CONTROL_VECTORS_OPER_MOD:ASSIGN_CV_AR',1,ZHOOK_HANDLE)
END SUBROUTINE ASSIGN_CV_AR

! ------------------------------------------------------------------

SUBROUTINE INVERSE_CV(YDCV)
CLASS(CONTROL_VECTOR), INTENT(INOUT) :: YDCV

! divide_cv fails on zero, inverse sets output to zero.
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('CONTROL_VECTORS_OPER_MOD:INVERSE_CV',0,ZHOOK_HANDLE)
CALL CHECK_CV(YDCV)
WHERE (YDCV%DATA /= 0.0_JPRB)
  YDCV%DATA = 1.0_JPRB/YDCV%DATA
ENDWHERE

IF (LHOOK) CALL DR_HOOK('CONTROL_VECTORS_OPER_MOD:INVERSE_CV',1,ZHOOK_HANDLE)
END SUBROUTINE INVERSE_CV

! ------------------------------------------------------------------

SUBROUTINE INVERSE_CV_CV(YDIN,YDOUT)
TYPE(CONTROL_VECTOR), INTENT(IN)    :: YDIN
CLASS(CONTROL_VECTOR), INTENT(INOUT) :: YDOUT

! divide_cv fails on zero, inverse sets output to zero.
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('CONTROL_VECTORS_OPER_MOD:INVERSE_CV_CV',0,ZHOOK_HANDLE)
CALL CHECK_CV_CV(YDIN,YDOUT)

WHERE (YDIN%DATA == 0.0_JPRB)
  YDOUT%DATA = 0.0_JPRB
ELSEWHERE
  YDOUT%DATA = 1.0_JPRB/YDIN%DATA
ENDWHERE

IF (LHOOK) CALL DR_HOOK('CONTROL_VECTORS_OPER_MOD:INVERSE_CV_CV',1,ZHOOK_HANDLE)
END SUBROUTINE INVERSE_CV_CV

! ------------------------------------------------------------------

END MODULE CONTROL_VECTORS_BASE_MIX
