! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE TM5_TRACERS

USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE TM5_CHEM_MODULE, ONLY : NTEMP

IMPLICIT NONE

SAVE

  INTEGER(KIND=JPIM), PARAMETER  :: NTRACE = 74  ! All tracers for chemistry

  !
  ! components numbers
  !
  INTEGER(KIND=JPIM), PARAMETER :: IO3=1
  INTEGER(KIND=JPIM), PARAMETER :: INOX=2
  INTEGER(KIND=JPIM), PARAMETER :: IH2O2=3 
  INTEGER(KIND=JPIM), PARAMETER :: ICH4=4 
  INTEGER(KIND=JPIM), PARAMETER :: ICO=5
  INTEGER(KIND=JPIM), PARAMETER :: IHNO3=6
  INTEGER(KIND=JPIM), PARAMETER :: ICH3O2H=7 
  INTEGER(KIND=JPIM), PARAMETER :: ICH2O=8 
  INTEGER(KIND=JPIM), PARAMETER :: IPAR=9
  INTEGER(KIND=JPIM), PARAMETER :: IETH=10 
  INTEGER(KIND=JPIM), PARAMETER :: IOLE=11
  INTEGER(KIND=JPIM), PARAMETER :: IALD2=12
  INTEGER(KIND=JPIM), PARAMETER :: IPAN=13 
  INTEGER(KIND=JPIM), PARAMETER :: IROOH=14
  INTEGER(KIND=JPIM), PARAMETER :: IORGNTR=15
  INTEGER(KIND=JPIM), PARAMETER :: IISOP=16
  INTEGER(KIND=JPIM), PARAMETER :: ISO2=17
  INTEGER(KIND=JPIM), PARAMETER :: IDMS=18 
  INTEGER(KIND=JPIM), PARAMETER :: INH3=19 
  INTEGER(KIND=JPIM), PARAMETER :: ISO4=20 
  INTEGER(KIND=JPIM), PARAMETER :: INH4=21 
  INTEGER(KIND=JPIM), PARAMETER :: IMSA=22
  INTEGER(KIND=JPIM), PARAMETER :: IMGLY=23
  ! marked tracers
  INTEGER(KIND=JPIM), PARAMETER :: IO3S=24   ! stratospheric o3 tracer   

  INTEGER(KIND=JPIM), PARAMETER :: IRN222=25
  INTEGER(KIND=JPIM), PARAMETER :: IPB210=26

  INTEGER(KIND=JPIM), PARAMETER :: INO=27  
  INTEGER(KIND=JPIM), PARAMETER :: IHO2=28 
  INTEGER(KIND=JPIM), PARAMETER :: ICH3O2=29 
  INTEGER(KIND=JPIM), PARAMETER :: IOH=30
  INTEGER(KIND=JPIM), PARAMETER :: INO2=31 
  INTEGER(KIND=JPIM), PARAMETER :: INO3=32 
  INTEGER(KIND=JPIM), PARAMETER :: IN2O5=33 
  INTEGER(KIND=JPIM), PARAMETER :: IHNO4=34 
  INTEGER(KIND=JPIM), PARAMETER :: IC2O3=35 
  INTEGER(KIND=JPIM), PARAMETER :: IROR=36
  INTEGER(KIND=JPIM), PARAMETER :: IRXPAR=37 
  INTEGER(KIND=JPIM), PARAMETER :: IXO2=38
  INTEGER(KIND=JPIM), PARAMETER :: IXO2N=39
  INTEGER(KIND=JPIM), PARAMETER :: INH2=40
  INTEGER(KIND=JPIM), PARAMETER :: IPSC=41
  INTEGER(KIND=JPIM), PARAMETER :: ICH3OH=42
  INTEGER(KIND=JPIM), PARAMETER :: IHCOOH=43
  INTEGER(KIND=JPIM), PARAMETER :: IMCOOH=44
  INTEGER(KIND=JPIM), PARAMETER :: IC2H6=45
  INTEGER(KIND=JPIM), PARAMETER :: IETHOH=46
  INTEGER(KIND=JPIM), PARAMETER :: IC3H8=47
  INTEGER(KIND=JPIM), PARAMETER :: IC3H6=48
  INTEGER(KIND=JPIM), PARAMETER :: ITERP=49
  INTEGER(KIND=JPIM), PARAMETER :: IISPD=50
  INTEGER(KIND=JPIM), PARAMETER :: INO3_A=51
  INTEGER(KIND=JPIM), PARAMETER :: IACET=52
  INTEGER(KIND=JPIM), PARAMETER :: IACO2=53
  INTEGER(KIND=JPIM), PARAMETER :: IIC3H7O2=54
  INTEGER(KIND=JPIM), PARAMETER :: IHYPROPO2=55
  !VH INTEGER(KIND=JPIM), PARAMETER :: IOCS=xxx ! Exclude OCS from tropospheric chemistry. Filled with zero
  INTEGER(KIND=JPIM), PARAMETER :: ISO3=56
  INTEGER(KIND=JPIM), PARAMETER :: ICH3O2NO2=57 
  INTEGER(KIND=JPIM), PARAMETER :: IHONO=58 
  !
  INTEGER(KIND=JPIM), PARAMETER :: IHCN=59
  INTEGER(KIND=JPIM), PARAMETER :: ICH3CN=60
  !
  INTEGER(KIND=JPIM), PARAMETER :: IXYL=61
  INTEGER(KIND=JPIM), PARAMETER :: ITOL=62 
  INTEGER(KIND=JPIM), PARAMETER :: IAROO2=63 
  ! Isoprene degredation products 
  INTEGER(KIND=JPIM), PARAMETER :: IHPALD1=64
  INTEGER(KIND=JPIM), PARAMETER :: IHPALD2=65 
  INTEGER(KIND=JPIM), PARAMETER :: IISOPOOH=66
  INTEGER(KIND=JPIM), PARAMETER :: IGLY=67         
  INTEGER(KIND=JPIM), PARAMETER :: IGLYALD=68
  INTEGER(KIND=JPIM), PARAMETER :: IHYAC=69
  ! Isoprene peroxy from LIM0    
  INTEGER(KIND=JPIM), PARAMETER :: IISOPBO2=70
  INTEGER(KIND=JPIM), PARAMETER :: IISOPDO2=71  
  !
  INTEGER(KIND=JPIM), PARAMETER :: ISOG1=72
  INTEGER(KIND=JPIM), PARAMETER :: ISOG2A=73
  INTEGER(KIND=JPIM), PARAMETER :: ISOG2B=74
  ! Volcanic SO2 tracer initialize to -999
  INTEGER(KIND=JPIM) :: IVSO2=-999

  ! Dummy index to track jo2 budget (but it doesn't work). Keep io2 < NCHEM+3
  INTEGER(KIND=JPIM), PARAMETER :: IO2 = NTRACE + 2

!
! corresponding nrr used for reaction budget calculations
! This table contains the information about which species 
! are involved in each reaction.
!
  REAL(KIND=JPRB),DIMENSION(NTRACE,NTEMP) :: HENRY   ! heterogeneous removal rates

  INTEGER(KIND=JPIM)         :: IACID, IAIR, IH2O

  INTEGER(KIND=JPIM), DIMENSION(30) :: NRJ 

  ! nrj and nrr used for reaction budget calculations
  ! INTEGER(KIND=JPIM),DIMENSION(20),PARAMETER    ::  NRJ=(/ &
  ! &         IO3,INO2,IH2O2,IHNO3,IHNO4,IN2O5,ICH2O,ICH2O, &
  ! &         ICH3O2H,INO3,INO3,IPAN,IORGNTR,IALD2,IMGLY,IROOH, & 
  ! &         IO2,IISPD, IACET,IACET, IISOPOOH/) 


  ! Flexible tracer number for additional chemistry schemes
  INTEGER(KIND=JPIM)   :: IFLRN222
  INTEGER(KIND=JPIM)   :: IFLPB210
  INTEGER(KIND=JPIM)   :: IFLO3
  INTEGER(KIND=JPIM)   :: IFLCO

END MODULE TM5_TRACERS
