! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE YOMFPHOLD

!
! Data holder for fullpos xxtddddhhmm choices
! Use to avoid reading config files over and over again
! Contains the following subroutines
!
! FIND_FP[DYN|PHY]_HOLDER : Find settings for a given CDYFILE
! FETCH_FP[DYN|PHY]_HOLDER : Fetch settings for a given CDYFILE
! SETUP_FP[DYN|PHY]_HOLDER : Setup settings for a given CDYFILE
! CLEAR_FP[DYN|PHY]_HOLDER : Destructor
! DEALLOCATE_TRQ[2|3]FP : Destructor
! COPY_TRQ[2|3]FP : Copy config type
! COPY_FPRQPHY : Copy config type

!
! Ulf Andrae, SMHI 2017-2020
!

USE PARKIND1, ONLY : JPIM,JPRB
USE YOMHOOK  , ONLY : LHOOK    ,DR_HOOK,  JPHOOK
USE YOMLUN, ONLY : NULOUT
USE YOM4FPOS , ONLY : TRQFPDYN,TRQ3FP,TRQ2FP,ALLOCATE_TRQ3FP,ALLOCATE_TRQ2FP
USE YOMFP4L, ONLY : TRQFP
USE YOMFPC, ONLY : NMAXFPHOLD,LALLOFP
USE TYPE_FPRQPHYS, ONLY : DEALLOCATE_FPRQPHY,ALLOCATE_FPRQPHY,INQUIRE_FPRQPHY

IMPLICIT NONE

TYPE FPPHY_HOLDER
 CHARACTER(LEN=120) :: CDYFILE
 TYPE(TRQFP)        :: YDRQPHY
END TYPE

TYPE FPDYN_HOLDER
 CHARACTER(LEN=120) :: CDYFILE
 TYPE(TRQFPDYN)     :: YDRQDYN
END TYPE

TYPE(FPDYN_HOLDER), ALLOCATABLE, TARGET :: FPDYN_LIST(:)
TYPE(FPPHY_HOLDER), ALLOCATABLE, TARGET :: FPPHY_LIST(:)

INTEGER, TARGET :: NFPDYN_HOLDERS=0
INTEGER, TARGET :: NFPPHY_HOLDERS=0

CONTAINS

!
!-----------------------------------------------------------------------
!

SUBROUTINE FIND_FPDYN_HOLDER(KHOLDER,CDYFILE)

 IMPLICIT NONE

 INTEGER(KIND=JPIM), INTENT(INOUT) :: KHOLDER
 CHARACTER(LEN=120), INTENT(IN)    :: CDYFILE

 INTEGER(KIND=JPIM) :: I

 REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
 IF (LHOOK) CALL DR_HOOK('YOMFPHOLD:FIND_FPDYN_HOLDER',0,ZHOOK_HANDLE)

 KHOLDER = -1
 DO I=1,NFPDYN_HOLDERS
  IF (TRIM(FPDYN_LIST(I)%CDYFILE) == TRIM(CDYFILE)) THEN
    KHOLDER = I
  ENDIF
 ENDDO

 IF (LHOOK) CALL DR_HOOK('YOMFPHOLD:FIND_FPDYN_HOLDER',1,ZHOOK_HANDLE)

 RETURN

END SUBROUTINE FIND_FPDYN_HOLDER

!
!-----------------------------------------------------------------------
!

SUBROUTINE FIND_FPPHY_HOLDER(KHOLDER,CDYFILE)

 IMPLICIT NONE

 INTEGER(KIND=JPIM), INTENT(INOUT) :: KHOLDER
 CHARACTER(LEN=120), INTENT(IN)    :: CDYFILE

 INTEGER(KIND=JPIM) :: I

 REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
 IF (LHOOK) CALL DR_HOOK('YOMFPHOLD:FIND_FPPHY_HOLDER',0,ZHOOK_HANDLE)

 KHOLDER = -1
 DO I=1,NFPPHY_HOLDERS
  IF (TRIM(FPPHY_LIST(I)%CDYFILE) == TRIM(CDYFILE)) THEN
    KHOLDER = I
  ENDIF
 ENDDO

 IF (LHOOK) CALL DR_HOOK('YOMFPHOLD:FIND_FPPHY_HOLDER',1,ZHOOK_HANDLE)

 RETURN

END SUBROUTINE FIND_FPPHY_HOLDER

!
!-----------------------------------------------------------------------
!

SUBROUTINE SETUP_FPPHY_HOLDER(CDYFILE,YDRQPHY)
 
 IMPLICIT NONE

 CHARACTER(LEN=120),INTENT(IN) :: CDYFILE
 TYPE(TRQFP),       INTENT(IN) :: YDRQPHY
  
 INTEGER, POINTER :: I 
 INTEGER(KIND=JPIM) :: IDMP_SHAPE(2)

 REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "abor1.intfb.h"

 IF (LHOOK) CALL DR_HOOK('YOMFPHOLD:SETUP_FPPHY_HOLDER',0,ZHOOK_HANDLE)

 IF ( .NOT. ALLOCATED(FPPHY_LIST) ) ALLOCATE(FPPHY_LIST(NMAXFPHOLD))

 I => NFPPHY_HOLDERS
 I = I + 1

 IF ( I > NMAXFPHOLD ) & 
 CALL ABOR1('NFPPHY_HOLDERS > NMAXFPHOLD')

 WRITE(NULOUT,*)'Add FPPHY holder for:',TRIM(CDYFILE),I

 FPPHY_LIST(I)%CDYFILE = CDYFILE

 CALL COPY_FPRQPHY(YDRQPHY,FPPHY_LIST(I)%YDRQPHY)

 NULLIFY(I)

 IF (LHOOK) CALL DR_HOOK('YOMFPHOLD:SETUP_FPPHY_HOLDER',1,ZHOOK_HANDLE)

 RETURN 

END SUBROUTINE SETUP_FPPHY_HOLDER

!
!-----------------------------------------------------------------------
!

SUBROUTINE FETCH_FPPHY_HOLDER(KHOLDER,YDRQPHY)
 
 IMPLICIT NONE

 INTEGER,     INTENT(IN ) :: KHOLDER 
 TYPE(TRQFP), INTENT(OUT) :: YDRQPHY

 REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

 IF (LHOOK) CALL DR_HOOK('YOMFPHOLD:FETCH_FPPHY_HOLDER',0,ZHOOK_HANDLE)

 CALL COPY_FPRQPHY(FPPHY_LIST(KHOLDER)%YDRQPHY,YDRQPHY)

 IF (LHOOK) CALL DR_HOOK('YOMFPHOLD:FETCH_FPPHY_HOLDER',1,ZHOOK_HANDLE)

 RETURN 

END SUBROUTINE FETCH_FPPHY_HOLDER

!
!-----------------------------------------------------------------------
!

SUBROUTINE CLEAR_FPPHY_HOLDER

 IMPLICIT NONE

 INTEGER(KIND=JPIM) :: I

 REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
 IF (LHOOK) CALL DR_HOOK('YOMFPHOLD:CLEAR_FPPHY_HOLDER',0,ZHOOK_HANDLE)

 DO I=1,NFPPHY_HOLDERS
 
  CALL DEALLOCATE_FPRQPHY(FPPHY_LIST(I)%YDRQPHY) 
  FPPHY_LIST(I)%CDYFILE = '' 

 ENDDO

 IF (ALLOCATED(FPPHY_LIST)) DEALLOCATE(FPPHY_LIST)

 NFPPHY_HOLDERS = 0

 IF (LHOOK) CALL DR_HOOK('YOMFPHOLD:CLEAR_FPPHY_HOLDER',1,ZHOOK_HANDLE)
 RETURN

END SUBROUTINE CLEAR_FPPHY_HOLDER

!
!-----------------------------------------------------------------------
!

SUBROUTINE SETUP_FPDYN_HOLDER(CDYFILE,YDRQDYN)

 IMPLICIT NONE

 CHARACTER(LEN=120),INTENT(IN) :: CDYFILE
 TYPE(TRQFPDYN),    INTENT(IN) :: YDRQDYN

 INTEGER, POINTER :: I

 REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "abor1.intfb.h"

 IF (LHOOK) CALL DR_HOOK('YOMFPDYN:SETUP_FPDYN_HOLDER',0,ZHOOK_HANDLE)

 IF ( .NOT. ALLOCATED(FPDYN_LIST) ) ALLOCATE(FPDYN_LIST(NMAXFPHOLD))

 I => NFPDYN_HOLDERS
 I = I + 1

 IF ( I > NMAXFPHOLD ) & 
 CALL ABOR1('NFPDYN_HOLDERS > NMAXFPHOLD')

 WRITE(NULOUT,*)'Add FPDYN holder for:',TRIM(CDYFILE),I

 FPDYN_LIST(I)%CDYFILE = CDYFILE

 ! Pressure levels
 CALL  COPY_TRQ3FP('YPR',       &
                   YDRQDYN%YPR, &
                   FPDYN_LIST(I)%YDRQDYN%YPR)

 ! Height (above orography) levels
 CALL  COPY_TRQ3FP('YHO',       &
                   YDRQDYN%YHO, &
                   FPDYN_LIST(I)%YDRQDYN%YHO)

 ! isentropic (Theta) levels
 CALL  COPY_TRQ3FP('YTH',       &
                   YDRQDYN%YTH, &
                   FPDYN_LIST(I)%YDRQDYN%YTH)

 ! Potential Vorticity levels
 CALL  COPY_TRQ3FP('YPV',       &
                   YDRQDYN%YPV, &
                   FPDYN_LIST(I)%YDRQDYN%YPV)

 ! Eta (s) levels
 CALL  COPY_TRQ3FP('YES',       &
                   YDRQDYN%YES, &
                   FPDYN_LIST(I)%YDRQDYN%YES)

 ! isothermic (T) levels
 CALL  COPY_TRQ3FP('YIT',       &
                   YDRQDYN%YIT, &
                   FPDYN_LIST(I)%YDRQDYN%YIT)

 ! Flight (altitude in feet) levels
 CALL  COPY_TRQ3FP('YFL',       &
                   YDRQDYN%YFL, &
                   FPDYN_LIST(I)%YDRQDYN%YFL)

 ! 2D fields

 CALL  COPY_TRQ2FP('Y2D',       &
                   YDRQDYN%Y2D, &
                   FPDYN_LIST(I)%YDRQDYN%Y2D)

 NULLIFY(I)

 IF (LHOOK) CALL DR_HOOK('YOMFPDYN:SETUP_FPDYN_HOLDER',1,ZHOOK_HANDLE)

 RETURN

END SUBROUTINE SETUP_FPDYN_HOLDER

!
!-----------------------------------------------------------------------
!

SUBROUTINE FETCH_FPDYN_HOLDER(KHOLDER,YDRQDYN)

 ! ------------------------------------------------------------------

 IMPLICIT NONE

 INTEGER(KIND=JPIM),INTENT(IN ) :: KHOLDER
 TYPE(TRQFPDYN),    INTENT(OUT) :: YDRQDYN

 REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

 IF (LHOOK) CALL DR_HOOK('YOMFPDYN:FETCH_FPDYN_HOLDER',0,ZHOOK_HANDLE)

 ! Pressure levels
 CALL  COPY_TRQ3FP('YPR',FPDYN_LIST(KHOLDER)%YDRQDYN%YPR,YDRQDYN%YPR)

 ! Height (above orography) levels
 CALL  COPY_TRQ3FP('YHO',FPDYN_LIST(KHOLDER)%YDRQDYN%YHO,YDRQDYN%YHO)

 ! isentropic (Theta) levels
 CALL  COPY_TRQ3FP('YTH',FPDYN_LIST(KHOLDER)%YDRQDYN%YTH,YDRQDYN%YTH)

 ! Potential Vorticity levels
 CALL  COPY_TRQ3FP('YPV',FPDYN_LIST(KHOLDER)%YDRQDYN%YPV,YDRQDYN%YPV)

 ! Eta (s) levels
 CALL  COPY_TRQ3FP('YES',FPDYN_LIST(KHOLDER)%YDRQDYN%YES,YDRQDYN%YES)

 ! isothermic (T) levels
 CALL  COPY_TRQ3FP('YIT',FPDYN_LIST(KHOLDER)%YDRQDYN%YIT,YDRQDYN%YIT)

 ! Flight (altitude in feet) levels
 CALL  COPY_TRQ3FP('YFL',FPDYN_LIST(KHOLDER)%YDRQDYN%YFL,YDRQDYN%YFL)

 ! 2D fields
 CALL  COPY_TRQ2FP('Y2D',FPDYN_LIST(KHOLDER)%YDRQDYN%Y2D,YDRQDYN%Y2D)

 IF (LHOOK) CALL DR_HOOK('YOMFPDYN:FETCH_FPDYN_HOLDER',1,ZHOOK_HANDLE)

END SUBROUTINE FETCH_FPDYN_HOLDER

!
!-----------------------------------------------------------------------
!

SUBROUTINE CLEAR_FPDYN_HOLDER

IMPLICIT NONE

INTEGER(KIND=JPIM) :: I

 REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

 IF (LHOOK) CALL DR_HOOK('YOMFPDYN:CLEAR_FPDYN_HOLDER',0,ZHOOK_HANDLE)

 DO I=1,NFPDYN_HOLDERS

  FPDYN_LIST(I)%CDYFILE = '' 
  ASSOCIATE(Y=> FPDYN_LIST(I)%YDRQDYN)

  CALL DEALLOCATE_TRQ3FP(Y%YPR)
  CALL DEALLOCATE_TRQ3FP(Y%YHO)
  CALL DEALLOCATE_TRQ3FP(Y%YTH)
  CALL DEALLOCATE_TRQ3FP(Y%YPV)
  CALL DEALLOCATE_TRQ3FP(Y%YES)
  CALL DEALLOCATE_TRQ3FP(Y%YIT)
  CALL DEALLOCATE_TRQ3FP(Y%YFL)
  CALL DEALLOCATE_TRQ2FP(Y%Y2D)

  END ASSOCIATE

 ENDDO

 IF (ALLOCATED(FPDYN_LIST)) DEALLOCATE(FPDYN_LIST)

 NFPDYN_HOLDERS=0

 IF (LHOOK) CALL DR_HOOK('YOMFPDYN:CLEAR_FPDYN_HOLDER',1,ZHOOK_HANDLE)

END SUBROUTINE CLEAR_FPDYN_HOLDER

!
!-----------------------------------------------------------------------
!

SUBROUTINE DEALLOCATE_TRQ2FP(YD)

 ! To deallocate and nullity 2D dynamic fields pp request

 IMPLICIT NONE

 TYPE(TRQ2FP),       INTENT(INOUT) :: YD

 REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

 IF (LHOOK) CALL DR_HOOK('YOMFPHOLD:DEALLOCATE_TRQ2FP',0,ZHOOK_HANDLE)

 DEALLOCATE(YD%ICOD)
 DEALLOCATE(YD%IDOM)
 DEALLOCATE(YD%IDMP)

 IF (LHOOK) CALL DR_HOOK('YOMFPHOLD:DEALLOCATE_TRQ2FP',1,ZHOOK_HANDLE)

END SUBROUTINE DEALLOCATE_TRQ2FP

!
!-----------------------------------------------------------------------
!

SUBROUTINE DEALLOCATE_TRQ3FP(YD)

 ! To deallocate and nullity 3D dynamic fields pp request


 IMPLICIT NONE

 TYPE(TRQ3FP),       INTENT(INOUT) :: YD

 REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

 IF (LHOOK) CALL DR_HOOK('YOMFPHOLD:DEALLOCATE_TRQ3FP',0,ZHOOK_HANDLE)

 DEALLOCATE(YD%ZPXLEV)
 DEALLOCATE(YD%ILEV)
 DEALLOCATE(YD%NPPLEVG)
 DEALLOCATE(YD%ICOD)
 DEALLOCATE(YD%IDOM)
 DEALLOCATE(YD%IDMP)

 IF (LHOOK) CALL DR_HOOK('YOMFPHOLD:DEALLOCATE_TRQ3FP',1,ZHOOK_HANDLE)

END SUBROUTINE DEALLOCATE_TRQ3FP

!
!-----------------------------------------------------------------------
!

SUBROUTINE COPY_TRQ3FP(TAG,Y_IN,Y_OUT)

 IMPLICIT NONE

 CHARACTER(LEN=*), INTENT(IN ) :: TAG
 TYPE(TRQ3FP),     INTENT(IN ) :: Y_IN
 TYPE(TRQ3FP),     INTENT(OUT) :: Y_OUT

 INTEGER(KIND=JPIM) :: KDOM

 REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

 IF (LHOOK) CALL DR_HOOK('YOMFPDYN:COPY_TRQ3FP',0,ZHOOK_HANDLE)

 IF ( Y_IN%NPPFIELDG > 0 .AND. Y_IN%NPXLEV > 0 ) THEN
    KDOM=Y_IN%IDOM(1,1)
 ELSE
    KDOM=1
 ENDIF
 CALL ALLOCATE_TRQ3FP(Y_IN%NPPFIELDG,Y_IN%NPXLEV, KDOM, &
                      LALLOFP,NULOUT,Y_OUT)

 Y_OUT%NPPFIELDG = Y_IN%NPPFIELDG
 Y_OUT%NPXLEV    = Y_IN%NPXLEV   
 Y_OUT%NFIT      = Y_IN%NFIT     
 Y_OUT%NSPFIL    = Y_IN%NSPFIL     

 IF ( Y_IN%NPPFIELDG > 0 .AND. Y_IN%NPXLEV > 0 ) THEN
   Y_OUT%ZPXLEV  = Y_IN%ZPXLEV
   Y_OUT%NPPLEVG = Y_IN%NPPLEVG
   Y_OUT%ILEV    = Y_IN%ILEV
   Y_OUT%ICOD    = Y_IN%ICOD
   Y_OUT%IDOM    = Y_IN%IDOM
   Y_OUT%IDMP    = Y_IN%IDMP
 ENDIF

 IF (LHOOK) CALL DR_HOOK('YOMFPDYN:COPY_TRQ3FP',1,ZHOOK_HANDLE)

END SUBROUTINE COPY_TRQ3FP

!
!-----------------------------------------------------------------------
!

SUBROUTINE COPY_TRQ2FP(TAG,Y_IN,Y_OUT)

 IMPLICIT NONE

 CHARACTER(LEN=*), INTENT(IN ) :: TAG
 TYPE(TRQ2FP), INTENT(IN ) :: Y_IN
 TYPE(TRQ2FP), INTENT(OUT) :: Y_OUT

 INTEGER(KIND=JPIM) :: KDOM

 REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

 IF (LHOOK) CALL DR_HOOK('YOMFPDYN:COPY_TRQ2FP',0,ZHOOK_HANDLE)

 Y_OUT%NPPFIELDG = Y_IN%NPPFIELDG
 IF ( Y_IN%NPPFIELDG > 0 ) THEN
    KDOM=Y_IN%IDOM(1)
 ELSE
    KDOM=1
 ENDIF

 CALL ALLOCATE_TRQ2FP(Y_IN%NPPFIELDG,KDOM,LALLOFP,NULOUT,Y_OUT)

 IF ( Y_IN%NPPFIELDG > 0 ) THEN
   Y_OUT%ICOD = Y_IN%ICOD
   Y_OUT%IDOM = Y_IN%IDOM
   Y_OUT%IDMP = Y_IN%IDMP
 ENDIF

 IF (LHOOK) CALL DR_HOOK('YOMFPDYN:COPY_TRQ2FP',1,ZHOOK_HANDLE)

END SUBROUTINE COPY_TRQ2FP

!
!-----------------------------------------------------------------------
!

SUBROUTINE COPY_FPRQPHY(Y_IN,Y_OUT)

 IMPLICIT NONE

 TYPE(TRQFP), INTENT(IN ) :: Y_IN
 TYPE(TRQFP), INTENT(OUT) :: Y_OUT

 INTEGER(KIND=JPIM) :: IDMP_SHAPE(2)

 REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

 IF (LHOOK) CALL DR_HOOK('YOMFPDYN:COPY_FPRQPHY',0,ZHOOK_HANDLE)

 Y_OUT%NFIELDG=Y_IN%NFIELDG
 ALLOCATE(Y_OUT%ICOD(Y_OUT%NFIELDG))
 ALLOCATE(Y_OUT%IGRIB(Y_OUT%NFIELDG))
 ALLOCATE(Y_OUT%LLSURF(Y_OUT%NFIELDG))
 ALLOCATE(Y_OUT%CLNAME(Y_OUT%NFIELDG))
 ALLOCATE(Y_OUT%CLPREF(Y_OUT%NFIELDG))
 ALLOCATE(Y_OUT%IVEC(Y_OUT%NFIELDG))
 ALLOCATE(Y_OUT%IDOM(Y_OUT%NFIELDG))
 
 IDMP_SHAPE = SHAPE(Y_IN%IDMP)
 ALLOCATE(Y_OUT%IDMP(IDMP_SHAPE(1),Y_OUT%NFIELDG))

 Y_OUT%ICOD(:)   = Y_IN%ICOD(1:Y_OUT%NFIELDG)
 Y_OUT%CLPREF(:) = Y_IN%CLPREF(1:Y_OUT%NFIELDG)
 Y_OUT%CLNAME(:) = Y_IN%CLNAME(1:Y_OUT%NFIELDG)
 Y_OUT%IGRIB(:)  = Y_IN%IGRIB(1:Y_OUT%NFIELDG)
 Y_OUT%LLSURF(:) = Y_IN%LLSURF(1:Y_OUT%NFIELDG)
 Y_OUT%IVEC(:)   = Y_IN%IVEC(1:Y_OUT%NFIELDG)
 Y_OUT%IDOM(:)   = Y_IN%IDOM(1:Y_OUT%NFIELDG)
 Y_OUT%IDMP(:,:) = Y_IN%IDMP(1:IDMP_SHAPE(1),1:Y_OUT%NFIELDG)

 IF ( LALLOFP ) &
 CALL INQUIRE_FPRQPHY(Y_OUT,'FPHOLD:YDRQPHY',NULOUT)

 IF (LHOOK) CALL DR_HOOK('YOMFPDYN:COPY_FPRQPHY',1,ZHOOK_HANDLE)

END SUBROUTINE COPY_FPRQPHY

END MODULE YOMFPHOLD
